var anno_9_11 = `
<div id="table_main">
<div id="table_name">সূচিপত্র</div></div>
<p class="namo">॥নমো তস্স ভগৰতো অরহতো সম্মাসম্বুদ্ধস্স॥</p>
<p class="bookname">পদমঞ্জরী</p>
<p class="chapter">পদমঞ্জরী <a name="V0.0001"></a></p>
<div class="chaptxt">
<p class="gatha1">নিরুত্তিকাযোদধিপারগং জিনং,</p>
<p class="gatha2">ৰিসুদ্ধধম্মঞ্চ গণং অনুত্তরং।</p>
<p class="gatha3">তিধা নমিত্বা পদমঞ্জরী মযা,</p>
<p class="gathalast">করীযতো বালকবুদ্ধিৰুদ্ধিযাতি॥</p>
<p class="centered">অথ অকারন্তপুল্লিঙ্গো বুদ্ধসদ্দো ৰুচ্চতে।</p>
<p class="unindented">বুদ্ধো দেৰমনুস্সানং ধম্মং দেসেসি</p>
<p class="unindented">বুদ্ধা দেৰমনুস্সানং ধম্মং অদেসিংসু</p>
<p class="unindented">ভো বুদ্ধ ত্বম্পিখো মং পালয</p>
<p class="unindented">ভো বুদ্ধা তুম্হেপি খো মং পালেথ।</p>
<p class="unindented">বুদ্ধং ভগৰন্তং সক্কচ্চং ৰন্দামহং</p>
<p class="unindented">বুদ্ধে ভগৰন্তে সক্কচ্চং ৰন্দাম মযং</p>
<p class="unindented">বুদ্ধেন ভগৰতা ধম্মো দেসীযতে</p>
<p class="unindented">বুদ্ধেহি ভগৰন্তেহি ধম্মো দেসিতো</p>
<p class="unindented">বুদ্ধেন ভগৰতা মহাজনো সুচরতি</p>
<p class="unindented">বুদ্ধেহি ভগৰন্তেহি সিৰপদং যন্তি</p>
<p class="unindented">বুদ্ধস্স ভগৰতো পুপ্ফং যজতি</p>
<p class="unindented">বুদ্ধানং ভগৰতং পুপ্ফানি যজতি</p>
<p class="unindented">বুদ্ধা ভগৰতা সিৰপদং লভেয্য</p>
<p class="unindented">বুদ্ধেহি ভগৰন্তেহি পভা নিচ্ছরতি</p>
<p class="unindented">বুদ্ধস্স ভগৰতো ইদ্ধি কিং ন করে</p>
<p class="unindented">বুদ্ধানং ভগৰন্তানং ইদ্ধিপাটিহারিযানি</p>
<p class="unindented">বুদ্ধে ভগৰন্তে মহাজনো পসীদতি।</p>
<p class="unindented">বুদ্ধেসু ভগৰন্তেসু মনং পতিট্ঠিতং।</p>
<p class="centered">ইতি পঠমো পাঠো।</p>
<p class="centered">অকারন্তপুল্লিঙ্গো অত্তসদ্দো ৰুচ্চতে।</p>
<p class="unindented">অত্তা সংসারদুক্খং পাপুণাতি</p>
<p class="unindented">অত্তানো সুখদুক্খং পাপুণন্তি</p>
<p class="unindented">ভো অত্ত সুখদুক্খং অনুভোসি</p>
<p class="unindented">ভো অত্তনো সুখদুক্খং অনুভোথ</p>
<p class="unindented">অত্তানং পস্সতি বুদ্ধো ভগৰা</p>
<p class="unindented">অত্তানো <a name="V0.0002"></a> পস্সতি সম্মা সম্বুদ্ধো</p>
<p class="unindented">অত্তনা সুখদুক্খং অনুভুত্তং</p>
<p class="unindented">অত্তনেহি কম্মফলং অনুভুত্তং</p>
<p class="unindented">অত্তনা সংসারসুখং নাম নত্থি</p>
<p class="unindented">অত্তনেহি ভৰসুখং নাম নত্থি</p>
<p class="unindented">অত্তনো অত্তাৰ পতিট্ঠা সিযা</p>
<p class="unindented">অত্তানং কম্মমেৰ পতিট্ঠা সিযা</p>
<p class="unindented">অত্তনাপি মহব্ভযং উপ্পজ্জতি</p>
<p class="unindented">অত্তনেহি মহব্ভযানি জাযন্তি</p>
<p class="unindented">অত্তনো মাতাপিতরো হোন্তি</p>
<p class="unindented">অত্তানং পঞ্চগতিযো হোন্তি</p>
<p class="unindented">অত্তনি সব্বং বলং হরতি রোগো</p>
<p class="unindented">অত্তনেসু সব্বং বলং হরন্তি রোগা।</p>
<p class="centered">ইতি দুতিযো পাঠো।</p>
<p class="centered">অকারন্ত পুল্লিঙ্গো রাজসদ্দো ৰুচ্চতে।</p>
<p class="unindented">রাজাপি মহাজনং তোসেতি</p>
<p class="unindented">রাজানো মহাজনং তোসেন্তি</p>
<p class="unindented">ভো রাজা মহাজনং পালয</p>
<p class="unindented">ভো রাজানো মহাজনং পালেথ</p>
<p class="unindented">রাজানং পস্সতি মহাজনো</p>
<p class="unindented">রাজানো পস্সন্তি মহাজনা</p>
<p class="unindented">রঞ্ঞা কারীযতে মহাপাসাদো</p>
<p class="unindented">রাজূহি কারাপিতা মহাৰিহারা</p>
<p class="unindented">রঞ্ঞা মহাজনো সুখং চরতি</p>
<p class="unindented">রাজূহী মহাজনা সুখং চরন্তি</p>
<p class="unindented">রঞ্ঞো পণ্ণাকারং দেতি মহাজনো</p>
<p class="unindented">রাজূনং পণ্ণাকারং দেন্তি মহাজনা</p>
<p class="unindented">রঞ্ঞা মহব্ভযং উপ্পজ্জতি</p>
<p class="unindented">রাজূহি মহব্ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">রঞ্ঞো ৰপ্পমঙ্গলং হোতি</p>
<p class="unindented">রাজূনং সব্বাভরণানি হোন্তি</p>
<p class="unindented">রঞ্ঞে মহাজনো পন পসীদতি</p>
<p class="unindented">রাজুসু মহাজনা পন পসীদন্তি।</p>
<p class="centered">ইতি ততিযো পাঠো।</p>
<p class="centered">অকারন্তপুল্লিঙ্গো গুণৰত্তুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">গুণৰা পুরিসো সুন্দরং নিব্বাণং গতো</p>
<p class="unindented">গুণৰন্তো <a name="V0.0003"></a> পুরিসা সুন্দরং নিব্বাণং গতা</p>
<p class="unindented">ভো গুণৰং পুরিস ত্বম্পি দানং দেহি</p>
<p class="unindented">ভো গুণৰন্তো পুরিসা তুম্হে দানং দেথ</p>
<p class="unindented">গুণৰন্তং পুরিসং ধম্মং বোধেতি আচরিযো</p>
<p class="unindented">গুণৰন্তে পুরিসে ধম্মং পাঠযতি আচরিযো</p>
<p class="unindented">গুণৰন্তেন পুরিসেন কারিতো ৰিহারো</p>
<p class="unindented">গুণৰন্তেহি পুরিসেহি কারিতা ৰিহারা</p>
<p class="unindented">গুণৰন্তেন পুরিসেন লোকো সুচরতি</p>
<p class="unindented">গুণৰন্তেহি পুরিসেহি লোকা সুচরন্তি</p>
<p class="unindented">গুণৰতো পুরিসস্স সক্কারং করোতি</p>
<p class="unindented">গুণৰতং পুরিসানং সক্কারং করোন্তি</p>
<p class="unindented">গুণৰতা পুরিসস্মা ভযং নূপ্পজ্জতি</p>
<p class="unindented">গুণৰন্তেহি পুরিসেহি ভযানি নূপ্পজ্জন্তি</p>
<p class="unindented">গুণৰতো পুরিসস্স কিত্তিসদ্দো অঙ্গুগ্গচ্ছতি</p>
<p class="unindented">গুণৰতং পুরিসানং গুণঘোসো হোতি</p>
<p class="unindented">গুণৰন্তে পুরিসে মে রমতি মতো</p>
<p class="unindented">গুণৰন্তেসু পুরিসেসু সপ্পুরিসো পসীদতি।</p>
<p class="centered">ইতি চতুত্থো পাঠো।</p>
<p class="centered">অকারন্তপুল্লিঙ্গো গচ্ছন্তসদ্দো ৰুচ্চতে।</p>
<p class="unindented">গচ্ছং যঞ্ঞদত্তো পুরিসং ভারং হারযতি</p>
<p class="unindented">গচ্ছন্তা যঞ্ঞদত্তা পুরিসং কম্মং কারযন্তি</p>
<p class="unindented">ভো গচ্ছং যঞ্ঞদত্ত ত্বং মং পালয</p>
<p class="unindented">ভো গচ্ছন্তা যঞ্ঞদত্তা মং পালেথ</p>
<p class="unindented">গচ্ছন্তং যঞ্ঞদত্তং কম্বলংযাচযতি দ্বিজো</p>
<p class="unindented">গচ্ছন্তে যঞ্ঞদত্তে কম্বলং যাচযতি দ্বিজো</p>
<p class="unindented">গচ্ছতা যঞ্ঞদত্তেন রুক্খো পুপ্ফানি অৰচীযতে</p>
<p class="unindented">গচ্ছন্তেহি যঞ্ঞদত্তেহি রুক্খো পুপ্ফানি অৰচিতো</p>
<p class="unindented">গচ্ছতা যঞ্ঞদত্তেন কোচি মগ্গং জানাতি</p>
<p class="unindented">গচ্ছন্তেহি যঞ্ঞদত্তেহি কেচিমগ্গং জানন্তি</p>
<p class="unindented">গচ্ছতো যঞ্ঞদত্তস্স ছত্তং ধারযতে</p>
<p class="unindented">গচ্ছতং যঞ্ঞদত্তানং ছত্তানি ধারযন্তে</p>
<p class="unindented">গচ্ছতা যঞ্ঞদত্তস্মা ভযং নূপ্পজ্জতি</p>
<p class="unindented">গচ্ছন্তেহি যঞ্ঞদত্তেহি ভযানি নূপ্পজ্জন্তি</p>
<p class="unindented">গচ্ছতো যঞ্ঞদত্তস্স ছত্তো হোতি</p>
<p class="unindented">গচ্ছতং যঞ্ঞদত্তানং আভরণানি হোন্তি</p>
<p class="unindented">গচ্ছন্তে যঞ্ঞদত্তে কোচি পসীদতি</p>
<p class="unindented">গচ্ছন্তেসু যঞ্ঞদত্তেসু কেচি পসীদন্তি।</p>
<p class="centered">ইতি <a name="V0.0004"></a> পঞ্চমো পাঠো।</p>
<p class="centered">ইকারন্তপুল্লিঙ্গো অগ্গিসদ্দো ৰুচ্চতে।</p>
<p class="unindented">অগ্গি পন কট্ঠমঙ্গারং করোতি</p>
<p class="unindented">অগ্গযো কট্ঠমঙ্গারং করোন্তি</p>
<p class="unindented">ভো অগ্গি ত্বং সীতং ৰিনোদেহি</p>
<p class="unindented">ভো অগ্গী তুম্হে সীতং ৰিনোদেথ</p>
<p class="unindented">অগ্গিং নিব্বাপেতি যো কোচি</p>
<p class="unindented">অগ্গযো নিব্বাপেন্তি যে কেচি</p>
<p class="unindented">অগ্গিনা কোচি অকারো দড্ঢো</p>
<p class="unindented">অগ্গীহি কেচি অগারা দড্ঢা</p>
<p class="unindented">অগ্গিনা কিঞ্চি আগারং ঝাপেতি</p>
<p class="unindented">অগ্গীহি কেচি অগারে ঝাপেতি</p>
<p class="unindented">অগ্গিনো উপাদানং দদাতি ব্রাহ্মণো</p>
<p class="unindented">অগ্গীনং উপাদানং দদন্তি ব্রাহ্মণা</p>
<p class="unindented">অগ্গিনা ধূমো অপেতি নিচ্চং</p>
<p class="unindented">অগ্গীহি’ধূমাপি অপেন্তি নিচ্চং</p>
<p class="unindented">অগ্গিনো আলোকো চ হোতি</p>
<p class="unindented">অগ্গীনং আলোকাপি হোন্তি</p>
<p class="unindented">অগ্গিম্হি যো কোচি পসীদতি</p>
<p class="unindented">অগ্গীসু যে কেচি পসীদন্তি।</p>
<p class="centered">ইতি ছট্ঠো পাঠো।</p>
<p class="centered">ইকারন্তপুল্লিঙ্গো আদিসদ্দো ৰুচ্চতে।</p>
<p class="unindented">আদি বন্ধীযতে সমগ্গেন সঙ্ঘেন</p>
<p class="unindented">আদযো বন্ধীযন্তে সমগ্গেহি ভিক্খুহি</p>
<p class="unindented">ভো আদি ত্বং দীঘকালং পৰত্তেহি</p>
<p class="unindented">ভো আদী তুম্হে দীঘকালং পৰত্তেথ</p>
<p class="unindented">আদিং পস্সতি সমগ্গো সঙ্ঘো চ</p>
<p class="unindented">আদযো পস্সতি ভিক্খু সঙ্ঘো চ</p>
<p class="unindented">আদিনা পরিসুদ্ধেন পন ভূযতে</p>
<p class="unindented">আদীহি পরিসুদ্ধেহি পন ভূযতে</p>
<p class="unindented">আদিনা সমগ্গো সঙ্ঘো সুচরতি</p>
<p class="unindented">আদীহি ভিক্খু সঙ্ঘো সুচরতি</p>
<p class="unindented">আদিনো কোচি উপকরণং দেতি</p>
<p class="unindented">আদীনং কেচি উপকরণং দেন্তি</p>
<p class="unindented">আদিনা সমগ্গো সঙ্ঘো অপেতি</p>
<p class="unindented">আদীহি ভিক্খু’সঙ্ঘো অপেতি</p>
<p class="unindented">আদিস্স <a name="V0.0005"></a> উপকারিকা খো পন হোতি</p>
<p class="unindented">আদীনং উপকারিকাযোপি হোন্তি</p>
<p class="unindented">আদিম্হি সমগ্গো সঙ্ঘো নিসীদতি</p>
<p class="unindented">আদীসূ ভিক্খু সঙ্ঘোপি নিসীদতি।</p>
<p class="centered">ইতি সত্তমো পাঠো।</p>
<p class="centered">ঈকারন্তপুল্লিঙ্গো দণ্ডীসদ্দো ৰুচ্চতে।</p>
<p class="unindented">দণ্ডী পুরিসোপি দণ্ডং ছড্ডেতু</p>
<p class="unindented">দণ্ডিনো পুরিসা দণ্ডং ছড্ডেন্তু</p>
<p class="unindented">ভো দণ্ডী পুরিস দণ্ডং ছড্ডেহি</p>
<p class="unindented">ভো দণ্ডিনো পুরিসা দণ্ডং ছড্ডেথ</p>
<p class="unindented">দণ্ডিং পুরিসং কম্মং কারযতি পুরিসো</p>
<p class="unindented">দণ্ডী পুরিসে কম্মে কারেন্তি পুরিসা</p>
<p class="unindented">দণ্ডিনা পুরিসেন দণ্ডো ছড্ডীযতু</p>
<p class="unindented">দণ্ডীহি পুরিসেহি দণ্ডা ছড্ডীযন্তু</p>
<p class="unindented">দণ্ডিনা পুরিসেন পুরিসো তিট্ঠতি</p>
<p class="unindented">দণ্ডীহি পুরিসেহি পুরিসা তিট্ঠন্তি</p>
<p class="unindented">দণ্ডিনো পুরিসস্স চিত্তং ন রুচ্চতি</p>
<p class="unindented">দণ্ডীনং পুরিসানং চিত্তং ন রুচ্চতি</p>
<p class="unindented">দণ্ডিনা পুরিসস্মা ভযং উপ্পজ্জতি</p>
<p class="unindented">দণ্ডীহি পুরিসেহি ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">দণ্ডিনো পুরিসস্স পরিগ্গহো হোতি</p>
<p class="unindented">দণ্ডীনং পুরিসানং পরিগ্গহা হোন্তি</p>
<p class="unindented">দণ্ডিস্মিং পুরিসে চিত্তং ন রমতি</p>
<p class="unindented">দণ্ডীসু পুরিসেসু একচ্চো নপ্পসীদতি।</p>
<p class="centered">ইতি অট্ঠমো পাঠো।</p>
<p class="centered">উকারন্তপুল্লিঙ্গো ভিক্খুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">ভিক্খু মহারাজানং ধম্মং ভণতি</p>
<p class="unindented">ভিক্খূ মহারাজানং ধম্মং ভণন্তি</p>
<p class="unindented">ভো ভিক্খু পণীতং ধম্মং দেসেহি</p>
<p class="unindented">ভো ভিক্খূ পণীতং ধম্মং দেসেথ</p>
<p class="unindented">ভিক্খুং সক্কচ্চং পণমামহং</p>
<p class="unindented">ভিক্খূ সক্কচ্চং পণমাম মযং</p>
<p class="unindented">ভিক্খুনা সদ্ধম্মো দেসীযতে</p>
<p class="unindented">ভিক্খূহি সদ্ধম্মো সুদেসিতো</p>
<p class="unindented">ভিক্খুনা লোকো সগ্গং গচ্ছতি</p>
<p class="unindented">ভিক্খূহি মহাজনা সগ্গং তচ্ছন্তি</p>
<p class="unindented">ভিক্খুস্স <a name="V0.0006"></a> দানং দেতি সপ্পুরিসো</p>
<p class="unindented">ভিক্খূনং দানং দেন্তি সপ্পুরিসা</p>
<p class="unindented">ভিক্খুনা সগ্গং লভেয্য সঙো</p>
<p class="unindented">ভিক্খূহি সগ্গং লভেয্যুং সপ্পুরিসা</p>
<p class="unindented">ভিক্খুনো পত্তচীৰরম্পি ভৰতি</p>
<p class="unindented">ভিক্খূনং পত্তচীৰরানি ভৰন্তি</p>
<p class="unindented">ভিক্খুস্মিং মে রমতি মনো</p>
<p class="unindented">ভিক্খূসু সদ্ধো সপ্পুরিসো পসীদতি।</p>
<p class="centered">ইতি নৰমো পাঠো।</p>
<p class="centered">উকারন্তপুল্লিঙ্গো জন্তুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">জন্তু দেৰদত্তং কটং কারাপেতি</p>
<p class="unindented">জন্তুনো দেৰদত্তে কটে কারাপেন্তি</p>
<p class="unindented">ভোজন্তু ত্বম্পি দেৰদত্তং কটং কারেসি</p>
<p class="unindented">ভো জন্তুনো দেৰদত্তে কটে কারেথ।</p>
<p class="unindented">জন্তুম্পেতং কটং কারেমি তেনেৰ কটে ৰা</p>
<p class="unindented">জন্তুপেতে কটং কারেম তেনেৰ কটে ৰা</p>
<p class="unindented">জন্তুনা পুরিসো ৰিহারং ৰিহারেৰা কারাপীযতে</p>
<p class="unindented">জন্তূহি পুরিসো ৰিহারং ৰিহারেৰা কারিতো</p>
<p class="unindented">জন্তুনা রিযেন যো কোচি সুখং পাপুণতি</p>
<p class="unindented">জন্তূহি অরিযেহি যে কেচি সুখং পাপুণন্তি</p>
<p class="unindented">জন্তুনো অরিযস্স ধনং দদাতি ধনৰন্তো</p>
<p class="unindented">জন্তুনমরিযানং ধনং দদন্তি ধনৰন্তা</p>
<p class="unindented">জন্তুনারিযম্হা অন্তরধাযতি যো কোচি</p>
<p class="unindented">জন্তূহি অরিযেহি অন্তরধাযন্তি যে কেচি</p>
<p class="unindented">জন্তুনো সকলস্স ফলংৰিপাকো হোতি</p>
<p class="unindented">জন্তূনং সকলানং পঞ্চগতিযো হোন্তি</p>
<p class="unindented">জন্তুম্হি অরিযে যো কোচি পসীদতি</p>
<p class="unindented">জন্তুসু অরিযেসু যে কেচি পসীদন্তি।</p>
<p class="centered">ইতি দসমো পাঠো।</p>
<p class="centered">উকারন্তপুল্লিঙ্গো সত্থুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">সত্থা দেৰমনুস্সানং ধম্মদেসনং অকাসি</p>
<p class="unindented">সত্থারো দেৰমনুস্সানং ধম্মদেসনং অকাসুং</p>
<p class="unindented">ভো সত্থা ত্বং সদেৰকং লোকং পালয</p>
<p class="unindented">ভো সত্থারো সদেৰকং লোকং পালেথ</p>
<p class="unindented">সত্থারং ধম্মরাজানং সক্কচ্চং পণমা মহং</p>
<p class="unindented">সত্থারে ধম্মরাজে সক্কচ্চং পণমাম মযং</p>
<p class="unindented">সত্থারা <a name="V0.0007"></a> ধম্মরাজেন সীৰং বোধীযতে লোকো</p>
<p class="unindented">সত্থারেহি ধম্মরাজেহি সিৰং বোধিতো লোকো</p>
<p class="unindented">সত্থারা ধম্মরাজেন অচ্চুতং পদং গচ্ছতি</p>
<p class="unindented">সত্থারেহি ধম্মরাজেহি অচ্চুতং পদং লভেয্য</p>
<p class="unindented">সত্থু ধম্মরাজস্স পুপ্ফানি যজতি লোকো</p>
<p class="unindented">সত্থানং ধম্মরাজানং পুপ্ফানি যজতি লোকো</p>
<p class="unindented">সত্থারা ধম্মরাজস্মা পরাজেন্তি অঞ্ঞতিত্থিযা</p>
<p class="unindented">সত্থারেহি ধম্মরাজেহি ছরংসিযো নিচ্ছরন্তি</p>
<p class="unindented">সত্থুনো ধম্মরাজস্স চরণং পণমাম্যহং</p>
<p class="unindented">সত্থানং ধম্মরাজানং পাদে সিরসা পণাম</p>
<p class="unindented">সত্থরি ধম্মরাজে কো ভত্তিং ন ঘটীযতি</p>
<p class="unindented">সত্থারেসু ধম্মরাজেসু ভত্তি ভৰভৰে অত্থু।</p>
<p class="centered">ইতি একাদসমো পাঠো।</p>
<p class="centered">উকারন্তপুল্লিঙ্গো নন্তুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">তত্তা পিতামহং ভোজনং ভোজযতি</p>
<p class="unindented">নত্তারো পিতামহং ভোজনং ভোজযন্তি</p>
<p class="unindented">ভো নত্তা ত্বম্পি সিপ্পং উগ্গণ্হাহি</p>
<p class="unindented">ভো নত্তারো তুম্হে সিপ্পানি উগ্গণ্হাথ</p>
<p class="unindented">নত্তারং সিপ্পং পাঠেতি আচরিযো</p>
<p class="unindented">নত্তারে সিপ্পানি পাঠেন্তি আচরিযা</p>
<p class="unindented">নত্তারা রুক্খো পুপ্ফানি অৰচীযতে</p>
<p class="unindented">নত্তারেহি রুক্খো পুপ্ফানি অৰচিতো</p>
<p class="unindented">নত্তারা পিতামহো সুখী জাতো</p>
<p class="unindented">নত্তারেহি পিত্তামহা সুখীজাতা</p>
<p class="unindented">নত্তুস্স খেত্তৰত্থুং দদাতি পিতামহো</p>
<p class="unindented">নত্তারানং খেত্তৰত্থুং দদন্তি পিতামহা</p>
<p class="unindented">নত্তারা পিতামহো অপেতো হোতি</p>
<p class="unindented">নত্তারেহি পিতামহো অপেতো হোতি</p>
<p class="unindented">নন্তুনো ৰত্থাভরনং পন হোতি</p>
<p class="unindented">নত্তারানং খো পন ৰত্থাভরনানি হোন্তি</p>
<p class="unindented">নত্তরি যো কোচি পিতামহো নপ্পসীদতি</p>
<p class="unindented">নত্তারেসু যে কেচি পিতামহা নপ্পসীদন্তি।</p>
<p class="centered">ইতি দ্বাদসমো পাঠো।</p>
<p class="centered">উকারন্ত পুল্লিঙ্গো পিতুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">পিতাপি পুত্তং ভোজনং ভোজযতি</p>
<p class="unindented">পিতরো পুত্তে ভোজনং ভোজযন্তি</p>
<p class="unindented">ভোপিতা <a name="V0.0008"></a> ত্বম্পি ভোজনং ভোজেহি</p>
<p class="unindented">ভো পিতরো তুম্হে ভোজনং ভোজেথ</p>
<p class="unindented">পিতরং সক্কচ্চং পোসেতি পুত্তো</p>
<p class="unindented">পিতরে সক্কচ্চং পোসেন্তি পুত্তা</p>
<p class="unindented">পিতরা পুত্তো কুসলং কারাপীযতে</p>
<p class="unindented">পিতরেহি পুত্তো কুসলং কারাপীযতে</p>
<p class="unindented">পিতরা পুত্তোপি সুখং পাপুণাতি</p>
<p class="unindented">পিতরেহি ভগিনিযো সুখং পাপুণন্তি</p>
<p class="unindented">পিতুস্স অন্নপানংদেতি পুত্তো</p>
<p class="unindented">পিতরানং অন্নপানং দেন্তি পুত্তা</p>
<p class="unindented">পিতরা অন্তরধাযাতি পুত্তো</p>
<p class="unindented">পিতুনো পাদে অভিৰন্দতি পুত্তো</p>
<p class="unindented">পিতরানং পাদে অভিৰন্দতি পুত্তা</p>
<p class="unindented">পিতরি পুত্তো ত্রজো পসীদতি</p>
<p class="unindented">পিতরেসু পুত্তোরসো পসীদতি।</p>
<p class="centered">ইতি তেরসমো পাঠো।</p>
<p class="centered">উকারন্ত পুল্লিঙ্গো ভাতুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">ভাতা ভগিনিং কুসলং কারাপযতি</p>
<p class="unindented">ভাতরো ভগিনী কুসলানি কারাপযন্তি</p>
<p class="unindented">ভো ভাতা ত্বম্পি কুসলং করোহি</p>
<p class="unindented">ভো ভাতরো তুম্হে কুসলানি করোথ</p>
<p class="unindented">ভাতরং কম্মং কারযতি পুব্বজো</p>
<p class="unindented">ভাতরে কম্মে কারযন্তি পুব্বজা</p>
<p class="unindented">ভাতরা সঙ্ঘো ভত্তং ভোজাপীযতে</p>
<p class="unindented">ভাতরেহি সঙ্ঘো ভত্তং ভোজাপিতো</p>
<p class="unindented">ভাতরা ভগিনীপি সুখং পাপুণাতি</p>
<p class="unindented">ভাতরেহি ভগিনিযো সুখং পাপুণন্তি</p>
<p class="unindented">ভাতুস্স ৰত্থঞ্চ দদাতি পুব্বজো</p>
<p class="unindented">ভাতরানং ৰত্থানি দদন্তি পুব্বজা</p>
<p class="unindented">ভাতরা অন্তরধাযতি ভগিনিপি</p>
<p class="unindented">ভাতরেহি অন্তরধাযন্তি ভগিনিযো</p>
<p class="unindented">ভাতুনো খেত্তৰত্থূনি পন ৰিজ্জন্তি</p>
<p class="unindented">ভাতরানং খেত্তৰত্থূনি পন ৰিজ্জন্তি</p>
<p class="unindented">ভাতরি জেট্ঠো সম্মা পসীদতি</p>
<p class="unindented">ভাতরেসু জেট্ঠা সম্মা পসীদন্তি।</p>
<p class="centered">ইতি চুদ্দসমো পাঠো।</p>
<p class="centered">ঊকারন্ত <a name="V0.0009"></a> পুল্লিঙ্গো অভিভূসদ্দো ৰুচ্চতে।</p>
<p class="unindented">অভিভূ তথাগতো ধম্মদেসনং অকাসি</p>
<p class="unindented">অভিভূ তথাগতা ধম্মদেসনং অকাসুং</p>
<p class="unindented">ভো অভিভূ তথাগত ধম্মং দেসেহি</p>
<p class="unindented">ভো অভিভূ তথাগতা ধম্মং দেসেথ</p>
<p class="unindented">অভিভুং তথাগতং সিরসা নমাম্যহং</p>
<p class="unindented">অভিভুৰো তথাগতে সিরসা নমাম মযং</p>
<p class="unindented">অভিভুনা তথাগতেন ধম্মো দেসিতো</p>
<p class="unindented">অভিভূহি তথাগতেহি ধম্মা দেসিতা</p>
<p class="unindented">অভিভুনা তথাগতেন মুনযো সুখীজাতা</p>
<p class="unindented">অভিভূহি তথাগতেহি লোকা সুখীজাতা</p>
<p class="unindented">অভিভূনো তথাগতস্স পুপ্ফানি যজতি</p>
<p class="unindented">অভিভূনং তথাগতানং পুপ্ফানি যজন্তি</p>
<p class="unindented">অভিভুনা তথাগতম্হা পভা নিচ্ছরতি</p>
<p class="unindented">অভিভূহি তথাগতেহি পভাযো নিচ্ছরন্তি</p>
<p class="unindented">অভিভুনো তথাগতস্স পাদে পণমামি</p>
<p class="unindented">অভিভূনং তথাগতানং চরণং পণমাম</p>
<p class="unindented">অভিভুম্হি তথাগতে মে রমতি মনো</p>
<p class="unindented">অভিভূসু তথাগতেসু মনং পতিট্ঠিতং।</p>
<p class="centered">ইতি পঞ্চদসমো পাঠো।</p>
<p class="centered">ঊকারন্ত পুল্লিঙ্গো সব্বঞ্ঞুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">সব্বঞ্ঞু লোকনাথো ধম্মং দেসেতি</p>
<p class="unindented">সব্বঞ্ঞু লোকনাথা ধম্মং দেসেন্তি</p>
<p class="unindented">ভো সব্বঞ্ঞু লোকনাথ ধম্মং দেসেহি</p>
<p class="unindented">ভো সব্বঞ্ঞু লোকনাথা ধম্মং দেসেথ</p>
<p class="unindented">সব্বঞ্ঞুং লোকনাথং পস্সতি মহাজনো</p>
<p class="unindented">সব্বঞ্ঞুনো লোকনাথে পস্সতি মহাজনো</p>
<p class="unindented">সব্বঞ্ঞুনা লোকনাথেন ধম্মো দেসীযতে</p>
<p class="unindented">সব্বঞ্ঞূহি লোকনাথেহি ধম্মো দেসিতো</p>
<p class="unindented">সব্বঞ্ঞুনা লোকনাথেন সিৰপদং যন্তি</p>
<p class="unindented">সব্বঞ্ঞূহি লোকনাথেহি লোকা সুখীজাতা</p>
<p class="unindented">সব্বঞ্ঞুনো লোকনাথস্স জীৰিতং পরিচ্চজামি</p>
<p class="unindented">সব্বঞ্ঞূনং লোকনাথানং জীৰিতং পরিচ্চজামি</p>
<p class="unindented">সব্বঞ্ঞুনা লোকনাথস্মা সিৰপদং লভেয্য</p>
<p class="unindented">সব্বঞ্ঞূহি লোকনাথেহি সিৰপদি লভেয্যুং</p>
<p class="unindented">সব্বঞ্ঞুনো <a name="V0.0010"></a> লোকনাথস্স চরণং ৰন্দামি</p>
<p class="unindented">সব্বঞুঞূনং লোকনাথানং পাদে ৰন্দাম</p>
<p class="unindented">সব্বঞ্ঞুস্মিং লোকনাথে লোকো পসীদতি</p>
<p class="unindented">সব্বঞ্ঞূসু লোকনাথেসু লোকা পসীদন্তি।</p>
<p class="centered">ইতি সোলসমো পাঠো।</p>
<p class="centered">ওকারন্ত পুল্লিঙ্গো গোসদ্দো ৰুচ্চতে।</p>
<p class="unindented">গো উসভো উজুং গচ্ছতি</p>
<p class="unindented">গাৰো উসভা উজুং গচ্ছন্তি</p>
<p class="unindented">ভো গো উসভা উজুং গচ্ছাহি</p>
<p class="unindented">গাৰুং ৰজং রুন্ধতি গোপালো</p>
<p class="unindented">গাৰো ৰজে রুন্ধতি গোপালা</p>
<p class="unindented">গাৰেন সকটো আনীযতে</p>
<p class="unindented">গোহি সকটা আনীযন্তে</p>
<p class="unindented">গাৰেন গোমিকো জীৰিকং কপ্পেতি</p>
<p class="unindented">গোহি গোমিকা জীৰিকং কপ্পেন্তি</p>
<p class="unindented">গাৰস্স তিণং দদাতি গোপালো</p>
<p class="unindented">গোনং তিণং দদন্তি গোপালা</p>
<p class="unindented">গাৰা উসভস্মা ভযং উপ্জজ্জতি</p>
<p class="unindented">গোহি উসভেহি ভযানি জাযন্তি</p>
<p class="unindented">গাৰস্স উসভস্স ধৰলো গুণো</p>
<p class="unindented">গৰং উসভানং গুণা পমাণং</p>
<p class="unindented">ভাৰে উসভে গোমিকো পসীদতি</p>
<p class="unindented">গোসু উসভেসু গোমিকা পসীদন্তি।</p>
<p class="centered">ইতি সত্তদসমো পাঠো।</p>
<p class="centered">ইতি পদমঞ্জরিযা পুল্লিঙ্গনামানং।</p>
<p class="centered">পঠমো পরিচ্ছেদো।</p>
<p class="centered">অথ অকারন্তেত্থিলিঙ্গো কঞ্ঞাসদ্দো ৰুচ্চতে।</p>
<p class="unindented">কঞ্ঞা দাসিং কম্মং কারাপযতি</p>
<p class="unindented">কঞ্ঞাযো দাসী কম্মে কারাপযন্তি</p>
<p class="unindented">ভো কঞ্ঞে ত্বম্পি কুসলং করোহি</p>
<p class="unindented">ভো কঞ্ঞাযো তুম্হে কুসলং করোথ</p>
<p class="unindented">কঞ্ঞং কুসলং কারাপেতি মাতা</p>
<p class="unindented">কঞ্ঞাযো কুসলানি কারেন্তি মাতাপিতরো</p>
<p class="unindented">কঞ্ঞায <a name="V0.0011"></a> তিলানিপি ভজ্জীযন্তে</p>
<p class="unindented">কঞ্ঞাহি ধঞ্ঞানিপি ভজ্জীযন্তে</p>
<p class="unindented">কঞ্ঞায কোচি পুরিসো সুচরতি</p>
<p class="unindented">কঞ্ঞাহি কেচি পুরিসা সুচরন্তি</p>
<p class="unindented">কঞ্ঞায আভরণানি দদাতি পুরিসো</p>
<p class="unindented">কঞ্ঞানং আভরণানি দদাতি পুরিসো</p>
<p class="unindented">কঞ্ঞায অপেতি কোচি পুরিসো</p>
<p class="unindented">কঞ্ঞাহি অপেন্তি কেচি পুরিসা</p>
<p class="unindented">কঞ্ঞায ৰত্থাভরণানিপি হোন্তি</p>
<p class="unindented">কঞ্ঞানং ৰত্থাভরণানিপি হোন্তি</p>
<p class="unindented">কঞ্ঞাযং কোচি পুরিসো পসীদতি</p>
<p class="unindented">কঞ্ঞাসু কেচি পুরিসা পসীদন্তি।</p>
<p class="centered">ইতি পঠমো পাঠো।</p>
<p class="centered">ইকারন্ত ইত্থিলিঙ্গো রত্তিসদ্দো ৰুচ্চতে।</p>
<p class="unindented">রত্তি জুণ্হা সম্মা ৰিরোচতি</p>
<p class="unindented">রত্তিযো জুণ্হাযো ৰিরোচন্তি</p>
<p class="unindented">ভো রত্তি জুণ্হা সম্মা ৰিরোচ</p>
<p class="unindented">ভো রত্তিযো জুণ্হাযো ৰিরোচথ</p>
<p class="unindented">রত্তিং ন ওলোকেত্বা ধম্মং সুণোমি</p>
<p class="unindented">রত্তিযো ন ওলোকেত্বা ধম্মং সুণোম</p>
<p class="unindented">রত্তিযা যো কোচি মগ্গো রুন্ধীযতি</p>
<p class="unindented">রত্তীহি যে কেচি মগ্গা রুন্ধীযন্তি</p>
<p class="unindented">রত্তিযা চোরজেট্ঠো চোরযতি</p>
<p class="unindented">রত্তীহি চোরজেট্ঠা চোরযন্তি</p>
<p class="unindented">রত্তিযা দীপং দদাতি দীপকালে</p>
<p class="unindented">রত্তীনং দীপং দদন্তি দীপকালে</p>
<p class="unindented">রত্তিযা ভোজনা অপ্পটিৰিরতো</p>
<p class="unindented">রত্তীহি ভোজনেহি অপ্পটিৰিরতো</p>
<p class="unindented">রত্তিযা ঘনান্ধকারোপি হোতি</p>
<p class="unindented">রত্তীনং ঘনান্ধকারাপি হোন্তি</p>
<p class="unindented">রত্তিযং সূরিযো ন পাতুভৰতি</p>
<p class="unindented">রত্তীসু উহুঙ্কারা গোচরং গণ্হন্তি।</p>
<p class="centered">ইতি দুতিযো পাঠো।</p>
<p class="centered">ঈকারন্ত ইত্থিলিঙ্গো নদীসদ্দো ৰুচ্চতে।</p>
<p class="unindented">নদী অৰিচ্ছেদপ্পৰত্তি সন্দতি</p>
<p class="unindented">নদিযো <a name="V0.0012"></a> অৰিচ্ছেদপ্পৰত্তী সন্দন্তী</p>
<p class="unindented">ভো নদী অৰিচ্ছেদপ্পৰত্তি জলং দদ</p>
<p class="unindented">ভো নদী অৰিচ্ছেদপ্পৰত্তী জলং দদথ</p>
<p class="unindented">নদিং অৰিচ্ছেদপ্পৰত্তিং পস্সতি</p>
<p class="unindented">নদিযো অৰিচ্ছেদপ্পৰত্তিযো পস্সতি</p>
<p class="unindented">নদিযা আপো নিচ্চং ৰুয্হতে</p>
<p class="unindented">নদীহি আপো নিচ্চং ৰুয্হতে</p>
<p class="unindented">নদিযা খেত্তং ৰপতি কস্সকো</p>
<p class="unindented">নদীহি খেত্তানি ৰপন্তি কস্সকা</p>
<p class="unindented">নদিযা ৰিসং দদাতি কোচি বালো</p>
<p class="unindented">নদীনং ৰিসং দদন্তি কেচি বালা</p>
<p class="unindented">নদিযা পভৰন্তি কুন্নদিযো</p>
<p class="unindented">নদিযা খো পন মহোঘো ভৰতি</p>
<p class="unindented">নদীনং খো পন মহোঘো ভৰতি</p>
<p class="unindented">নদিযং মচ্ছসমূহো পন ৰিচরতি</p>
<p class="unindented">নদীসু মচ্ছকচ্ছপাদযো ৰিচরন্তি।</p>
<p class="centered">ইতি ততিযো পাঠো।</p>
<p class="centered">উকারন্ত ইত্থিলিঙ্গো যাগুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">যাগু পচ্চতে যঞ্ঞদত্তেন</p>
<p class="unindented">যাগুযো পচ্চন্তে যঞ্ঞদত্তেহি</p>
<p class="unindented">ভো যাগু ত্বং পন খুদং ভন</p>
<p class="unindented">ভো যাগুযো তুম্হে খুদং ভনথ</p>
<p class="unindented">যাগুং পিবতি যো কোচি জনো</p>
<p class="unindented">যাগুযো পিবন্তি যে কেচি জনা</p>
<p class="unindented">যাগুযা পন উদরগ্গি হঞ্ঞতি</p>
<p class="unindented">যাগূহি পন উদরগ্গী হঞ্ঞন্তি</p>
<p class="unindented">যাগুযা কোচি রোগো ৰুপসম্মতি</p>
<p class="unindented">যাগূহি কেচি রোগা ৰুপসম্মন্তি</p>
<p class="unindented">যাগুযা পন লৰণং দদাতি সূদো</p>
<p class="unindented">যাগূনং লৰণানি দদন্তি সূদা</p>
<p class="unindented">যাগুযা খো পন ধূমো অপেতি</p>
<p class="unindented">যাগূহি খো পন ধূমা অপেন্তি</p>
<p class="unindented">যাগুযা খো পন উণ্হো ৰিজ্জতি</p>
<p class="unindented">যাগূনং খো পন উণ্হা ৰিজ্জন্তি।</p>
<p class="unindented">যাগুযং পন সিত্থানি হোন্তি</p>
<p class="unindented">যাগূসু পন সিত্থানি হোন্তি।</p>
<p class="centered">ইতি <a name="V0.0013"></a> চতুত্থো পাঠো।</p>
<p class="centered">উকারন্ত ইত্থিলিঙ্গো মাতুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">মাতা পুত্তং ভোজনং ভোজযতি</p>
<p class="unindented">মাতরো পুত্তে ভোজনং ভোজযন্তি</p>
<p class="unindented">ভো মাতা ত্বং পন চিরং জীৰ</p>
<p class="unindented">ভো মাতরো তুম্হে চিরং জীৰথ</p>
<p class="unindented">মাতরং পোসেতি পুত্তোত্রজোপি</p>
<p class="unindented">মাতরে পোসেন্তি পুত্তোত্রজাপি</p>
<p class="unindented">মাতরা পুত্তো ভত্তং ভোজাপীযতে</p>
<p class="unindented">মাতরেহি পুত্তো ভত্তং ভোজাপিতো</p>
<p class="unindented">মাতরা পুত্তোপি সুখং পাপুণাতি</p>
<p class="unindented">মাতরেহি পুত্তাপি সুখং পাপুণন্তি</p>
<p class="unindented">মাতুযা অন্নং দদাতি পুত্তোপি</p>
<p class="unindented">মাতরানং ৰত্থানি দদন্তি পুত্তাপি</p>
<p class="unindented">মাতরা পন অন্তরধাযতি পুত্তো</p>
<p class="unindented">মাতরেহি অন্তরধাযন্তি পুত্তা</p>
<p class="unindented">মাতুযা পন পুত্তাপি বহৰো হোন্তি</p>
<p class="unindented">মাতরানং পুত্তাপি বহৰো হোন্তি</p>
<p class="unindented">মাতরি পন ওরসো পুত্তো পসীদতি</p>
<p class="unindented">মাতরেসু যে কেচি পুত্তা পসীদন্তি।</p>
<p class="centered">ইতি পঞ্চমো পাঠো।</p>
<p class="centered">ঊকারন্ত ইত্থিলিঙ্গো জম্বুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">জম্বূ পন অনুভুত্তা তথাগতেন</p>
<p class="unindented">জম্বুযো অনুভুত্তাযো তথাগতেহি</p>
<p class="unindented">ভো জম্বূ জম্বোনদম্পি দেহি</p>
<p class="unindented">ভো জম্বুযো জম্বোনদম্পি দেথ</p>
<p class="unindented">জম্বুং পন পস্সতি যো কোচি</p>
<p class="unindented">জম্বুযো পস্সন্তি যে কেচি</p>
<p class="unindented">জম্বুযা উদরগ্গি পন পটিহঞ্ঞতে</p>
<p class="unindented">জম্বূহি উদরগ্গী পন পটিহঞ্ঞন্তে</p>
<p class="unindented">জম্বুযা খো পন যো কোচি জীৰতি</p>
<p class="unindented">জম্বূহি খো পন যে কেচি জীৰন্তি</p>
<p class="unindented">জম্বুযা পন সিলাঘতে যো কোচি</p>
<p class="unindented">জম্বূনং পন সিলাঘতে মহাজনো</p>
<p class="unindented">জম্বুযা <a name="V0.0014"></a> খো পন জম্বোনদং জাযতি</p>
<p class="unindented">জম্বূহি খো পন জম্বোনদং উপ্পজ্জতি</p>
<p class="unindented">জম্বুযা পন মধুররসোজা হোতি</p>
<p class="unindented">জম্বূনং মধুররসোজাযো হোন্তি</p>
<p class="unindented">জম্বুযং খো পন জম্বোনদং অত্থি</p>
<p class="unindented">জম্বুসু পন জম্বোনদানি ৰিজ্জন্তি।</p>
<p class="centered">ইতি ছট্ঠো পাঠো।</p>
<p class="centered">ইতি পদমঞ্জরিযা ইত্থিলিঙ্গনামানং।</p>
<p class="centered">দুতিযো পরিচ্ছেদো।</p>
<p class="centered">অথ অকারন্তপুংসকলিঙ্গো চিত্তসদ্দো ৰুচ্চতে।</p>
<p class="unindented">চিত্তং অত্তনো সন্তানং ৰিজানাতি</p>
<p class="unindented">চিত্তানি অত্তনো সত্তানং ৰিজানন্তি</p>
<p class="unindented">ভো চিত্ত অত্তনো সন্তানং ৰিজানাহি</p>
<p class="unindented">ভো চিত্তানি অত্তনো সন্তানং ৰিজানাথ</p>
<p class="unindented">চিত্তং সঞ্ঞমেস্সন্তি যে কেচি জনা</p>
<p class="unindented">চিত্তানি সঞ্ঞমেস্সন্তি যে কেচি</p>
<p class="unindented">চিত্তেন সব্বোপি জনো নীয্যতে</p>
<p class="unindented">চিত্তেহি সব্বোপি জনো নীয্যতে</p>
<p class="unindented">চিত্তেন সংকিলিস্সতি মানৰো</p>
<p class="unindented">চিত্তেহি ৰিসুজ্ঝতি কোচিমানৰো</p>
<p class="unindented">চিত্তস্স ওৰাদং দেতি কোচি জনো</p>
<p class="unindented">চিত্তানং ওৰাদং দেন্তি কেচি জনা</p>
<p class="unindented">চিত্তস্মা আরম্মণং উপ্পজ্জতি</p>
<p class="unindented">চিত্তেহি আরম্মণানি উপ্পজ্জন্তি</p>
<p class="unindented">চিত্তস্স অনিচ্চধম্মস্স ৰসমন্বগূ</p>
<p class="unindented">চিত্তানং পরিৰিতক্কো উদপাদি</p>
<p class="unindented">চিত্তে অরক্খিতে কাযকম্মং অরক্খিতং</p>
<p class="unindented">চিত্তেসু গুত্তেসু কাযকম্মং রক্খিতং।</p>
<p class="centered">ইতি পঠমো পাঠো।</p>
<p class="centered">অকারন্তনপুংসকলিঙ্গো মনসদ্দো ৰুচ্চতে।</p>
<p class="unindented">মনং অত্তনো সন্তানং মঞ্ঞতি</p>
<p class="unindented">মনানি অত্তনো সত্তানং মঞ্ঞন্তি</p>
<p class="unindented">ভো মন অত্তনো সন্তানং মঞ্ঞাহি</p>
<p class="unindented">ভো <a name="V0.0015"></a> মনানি অত্তনো সন্তানং মঞ্ঞথ</p>
<p class="unindented">মনং পসাদেত্বা সগ্গং গমিস্সামি</p>
<p class="unindented">মনে পসাদেত্বা সগ্গং গমিস্সাম</p>
<p class="unindented">মনেন কুসলাকুসলকম্মং কতং</p>
<p class="unindented">মনেহি কুসলাকুসলকম্মানি কতানি</p>
<p class="unindented">মনসা ধম্মং ৰিজানাতি যোগাৰচরো</p>
<p class="unindented">মনেহি ধম্মং ৰিজানন্তি যোগাৰচরা</p>
<p class="unindented">মনসো পদুট্ঠস্স ওৰাদং দদাতি</p>
<p class="unindented">মনানং পদূট্ঠানং ওৰাদং দদন্তি</p>
<p class="unindented">মনসাপন আরম্মনং উপ্পজ্জতি</p>
<p class="unindented">মনেহি আরম্মণানি উপ্পজ্জন্তি</p>
<p class="unindented">মনসো অনিচ্চধম্মস্স ৰসমন্বগূ</p>
<p class="unindented">মনানং পন পরিৰিতক্কো উদপাদি</p>
<p class="unindented">মনে অরক্খিতে কাযকম্মং অরক্খিতং</p>
<p class="unindented">মনেসু গুত্তেসু কাযকম্মং রক্খিতং।</p>
<p class="centered">ইতি দুতিযো পাঠো।</p>
<p class="centered">অকারন্তনপুংসকলিঙ্গো গুণৰন্তুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">গুণৰং কুলং পন পুঞ্ঞং করোতি</p>
<p class="unindented">গুণৰন্তা কুলানি পুঞ্ঞং করোন্তি</p>
<p class="unindented">ভো গুণৰং কুলং পুঞ্ঞং করোহি</p>
<p class="unindented">ভো গুণৰন্তা কুলানি পুঞ্ঞং করোথ</p>
<p class="unindented">গুণৰন্তং কুলং পস্সতি যো কোচি</p>
<p class="unindented">গুণৰন্তে কুলে পস্সন্তি যে কেচি</p>
<p class="unindented">গুণৰন্তেন কুলেন ৰিহারো কারিতো</p>
<p class="unindented">গুণৰন্তেহি কুলেহি ৰিহারা কারিতা</p>
<p class="unindented">গুণৰন্তেন কুলেন লোকো সুচরতি</p>
<p class="unindented">গুণৰন্তেহি কুলেহি লোকা সুচরন্তি</p>
<p class="unindented">গুণৰতো কুলস্স ধনং দদাতি ধনৰা</p>
<p class="unindented">গুণৰতং কুলানং ধনং দদন্তি ধনৰন্তা</p>
<p class="unindented">গুণৰতা কুলম্হা ন অপেতি যো কোচি</p>
<p class="unindented">গুণৰন্তেহি কুলেহি ন অপেন্তি যে কেচি</p>
<p class="unindented">গুণৰতো কুলস্স গুণঘোসো হোতি</p>
<p class="unindented">গুণৰন্তানং কুলানং গুণঘোসা হোন্তি</p>
<p class="unindented">গুণৰন্তে কুলেপি মে রমতি মনো</p>
<p class="unindented">গুণৰন্তেসু কুলেসু মনং পতিট্ঠিতং।</p>
<p class="centered">ইতি <a name="V0.0016"></a> ততিযো পাঠো।</p>
<p class="centered">অকারন্তনপুংসকলিঙ্গো গচ্চন্তসদ্দো ৰুচ্চতে।</p>
<p class="unindented">গচ্ছং গুণৰং সুন্দরং নিব্বাণং গচ্ছতি</p>
<p class="unindented">গচ্ছন্তা গুণৰন্তা নিব্বাণং গচ্ছন্তি</p>
<p class="unindented">ভো গচ্ছং গুণৰং ত্বং পন সুগতিং গচ্ছাহি</p>
<p class="unindented">ভো গচ্ছন্তা গুণৰন্তা সুগতিং গচ্ছথ</p>
<p class="unindented">গচ্ছন্তং গুণৰন্তং পস্সতি একচ্চো</p>
<p class="unindented">গৰ্ছন্তে গুণৰন্তে পস্সতি একচ্চো</p>
<p class="unindented">গচ্ছতা গুণৰন্তেন সত্থং সূযতে</p>
<p class="unindented">গচ্ছন্তেহি গুণৰন্তেহি পুপ্ফং গয্হতে</p>
<p class="unindented">গচ্ছতা গুণৰন্তেন লোকো সুচরতি</p>
<p class="unindented">গচ্ছন্তেহি গুণৰন্তেহি সুখং পাপুণাতি</p>
<p class="unindented">গচ্ছতো গুণৰন্তস্স অনুগিণাতি জনো</p>
<p class="unindented">গচ্ছতং গুণৰন্তানং পতিগিণাতি জনো</p>
<p class="unindented">গচ্ছতা গুণৰন্তম্হা অপেতি একচ্চো</p>
<p class="unindented">গচ্চন্তেহি গুণৰন্তেহি অপেন্তি একচ্চে</p>
<p class="unindented">গচ্ছতো গুণৰন্তস্স মাতাপিতরো</p>
<p class="unindented">গচ্ছতং গুণৰন্তানং নামগোত্তাদি</p>
<p class="unindented">গচ্ছন্তে গুণৰন্তে মে রমনি মনো</p>
<p class="unindented">গচ্ছন্তেসু গুণৰন্তেসু মনং পতিঠিতং।</p>
<p class="centered">ইতি চতুত্থো পাঠো।</p>
<p class="centered">ইকারন্তনপুংসকলিঙ্গো অট্ঠিসদ্দো ৰুচ্চতে।</p>
<p class="unindented">অট্ঠি সঙ্খলিকং সরীরং পটিক্কূলং হোতি</p>
<p class="unindented">অট্ঠিনি পুঞ্জকিতানি পটিক্কূলানি হোন্তি</p>
<p class="unindented">ভো অট্ঠি সঙ্খলিকং ত্বং অনিচ্চতো পস্স</p>
<p class="unindented">ভো অট্ঠিনি সেতানি অনিচ্চতো পস্সথ</p>
<p class="unindented">অট্ঠিং সমংসলোহিতং অসুভতো পস্সতি</p>
<p class="unindented">অট্ঠিনি পুঞ্জকিতানি অনিচ্চতো পস্সতি</p>
<p class="unindented">অট্ঠিনা কাযেন যং কিঞ্চি রূপং নিম্মিতং</p>
<p class="unindented">অট্ঠীহি কাযেহি যং কিঞ্চি রূপং নিম্মিতং</p>
<p class="unindented">অট্ঠিনা নিমিত্তেন ভিক্খূ মগ্গং ভাৰেতি</p>
<p class="unindented">অট্ঠীহি নিমিত্তেহি ভিক্খূ মগ্গং ভাৰেন্তি</p>
<p class="unindented">অট্ঠিনো কাযস্স ওৰাদং দেতি একচ্চো</p>
<p class="unindented">অট্ঠীনং কাযানং ওৰাদি দেন্তি একচ্চে</p>
<p class="unindented">অট্ঠিম্হা <a name="V0.0017"></a> কাযস্মা অপেতি যোগাৰচরো</p>
<p class="unindented">অট্ঠীহি কাযেহি অপেন্তি যোগাৰচরা</p>
<p class="unindented">অট্ঠিনো কাযস্স পরিগ্গহো হোতি</p>
<p class="unindented">অট্ঠীনং কাযানং পরিগ্গহো হোতি</p>
<p class="unindented">অট্ঠিনী কাযে যোগাৰচরো নপ্পসীদতি</p>
<p class="unindented">অট্ঠীসু কাযেসু যোগাৰচরা নপ্পসীদন্তি।</p>
<p class="centered">ইতি পঞ্চমো পাঠো।</p>
<p class="centered">ঈকারন্তনপুংসকলিঙ্গো দণ্ডিসদ্দো ৰুচ্চতে।</p>
<p class="unindented">দণ্ডী পন পুরিসং কম্মং কারাপযতি</p>
<p class="unindented">দণ্ডীনি পুরিসং কম্মং কারাপযন্তি</p>
<p class="unindented">ভো দণ্ডী ত্বং পন কম্মং করোহি</p>
<p class="unindented">ভো দণ্ডীনি তুম্হে কম্মং করোথ</p>
<p class="unindented">দণ্ডিং দণ্ডকম্মং কারযতি অমচ্চো</p>
<p class="unindented">দণ্ডীনি দণ্ডকম্মে কারযন্তি অমচ্চা</p>
<p class="unindented">দণ্ডিনা জনো দণ্ডকম্মং ৰেদীযতে</p>
<p class="unindented">দণ্ডীহি জনো দণ্ডকম্মং ৰেদিতো</p>
<p class="unindented">দণ্ডিনা যো কোচি পন সন্তজ্জেতি</p>
<p class="unindented">দণ্ডীহি যে কেচি পন সন্তজ্জেন্তি</p>
<p class="unindented">দণ্ডিনো দণ্ডকম্মং দেতি অমচ্চো</p>
<p class="unindented">দণ্ডীনং দণ্ডকম্মং দেন্তি অমচ্চা</p>
<p class="unindented">দণ্ডিনা অপেতি যো কোচি পুরিসো</p>
<p class="unindented">দণ্ডীহি অপেন্তি যে কেচি পুরিসা</p>
<p class="unindented">দণ্ডিনো যো কোচি পরিগ্গহো হোতি</p>
<p class="unindented">দণ্ডীনং যে কেচি পরিগ্গহা হোন্তি</p>
<p class="unindented">দণ্ডিনি পন মে মনো ন রমতি</p>
<p class="unindented">দণ্ডীসু খো পন মে মনা ন রমন্তি।</p>
<p class="centered">ইতি ছট্ঠো পাঠো।</p>
<p class="centered">উকারন্ত নপুংসকলিঙ্গো আযুসদ্দো ৰুচ্চতে।</p>
<p class="unindented">আযু চস্সা পন পরিক্খিণো অহোসি</p>
<p class="unindented">আযূনি পন তেসং পরিক্খীণা অহেসুং</p>
<p class="unindented">ভো আযু ত্বং পন জীৰিতং পালেহি</p>
<p class="unindented">ভো আযূনি তুম্হে জীৰিতং পালথে</p>
<p class="unindented">আযুং অরূপধম্মং পস্সতি সম্মা সম্বুদ্ধো</p>
<p class="unindented">আযূনি অরূপধম্মে পস্সতি লোকনাথো</p>
<p class="unindented">আযুনা অরূপধম্মেন জীৰিতং পৰত্তিতং</p>
<p class="unindented">আযূহি <a name="V0.0018"></a> অরূপধম্মেহি জীৰিতং পৰত্তিতং</p>
<p class="unindented">আযুনা অরূপধম্মেন লোকো জীৰতি</p>
<p class="unindented">আযূহি অরূপধম্মেহি লোকো জীৰন্তি</p>
<p class="unindented">আযুনো রুচ্চতি সব্বোপি জনো</p>
<p class="unindented">আযূনং রুচ্চন্তি সব্বেপি জনা</p>
<p class="unindented">আযূনা খো পন অপেতি জীৰিতম্পি</p>
<p class="unindented">আযূহি খো পন অপেন্তি জীৰিতানি</p>
<p class="unindented">আযূনো পন পরিহারো হোতি সব্বদা</p>
<p class="unindented">আযূনং পন পরিহারো হোতি সব্বদা</p>
<p class="unindented">আযূম্হি খো পন মনং পতিঠিতং সব্বদা</p>
<p class="unindented">আযূসু খো পন মনং পতিট্ঠিতং সব্বদা।</p>
<p class="centered">ইতি সত্তমো পাঠো।</p>
<p class="centered">ইতি পদমঞ্জরিযা নপুংসকলিঙ্গনামানং।</p>
<p class="centered">ততিযো পরিচ্ছেদো।</p>
<p class="gatha1">ইতো পরং পৰক্খামি সব্বনামংচ তস্সমং।</p>
<p class="gathalast">নামংচ যোজিতং নানা নামেহেৰ ৰিসেসতো॥</p>
<p class="gatha1">যানি হোন্তি তিলিঙ্গানি অনুকূলানি যানি চ।</p>
<p class="gathalast">তিলিঙ্গানং ৰিসেসেন পদানেতানি নামতো॥</p>
<p class="gatha1">সব্বসাধারণা কানি নামানিচ্চেৰ অত্থতো।</p>
<p class="gathalast">সব্বনামানি ৰুচ্চন্তি সত্তৰীসতি সঙ্খতো॥</p>
<p class="gatha1">তেসু কানিচি রূপেহি সেসাঞ্ঞেহিচ যুজ্জরে।</p>
<p class="gathalast">কানিচি পন সহেৰ এতেসং লক্খণং ইদং॥</p>
<p class="gatha1">এতস্মা লক্খণা মুত্তং নপদং সব্বনামিকং।</p>
<p class="gathalast">তস্মাতীতাদযো সদ্দা গুণনামানি ৰুচ্চরেতি॥</p>
<p class="centered">অথ পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="gatha1">সব্বো সোতরি নাৰাহি মহাতিত্থে মহাজনো।</p>
<p class="gathalast">সব্বে অন্তরধাযন্তি সতমাযুগতে সতি॥</p>
<p class="gatha1">ভো সব্বা ভুত কল্যাণং করোহি কুসলা সদা।</p>
<p class="gathalast">ভো সব্বে পুরিসা ভদ্দং করোথ কুসলং সদা॥</p>
<p class="gatha1">সব্বং ভণ্ডং সমোধায তুট্ঠচিত্তো মহীপতি।</p>
<p class="gathalast">সব্বে ভোজাপযী তে তু সা নখীযিত্থ ভোজনং॥</p>
<p class="gatha1">সব্বেন <a name="V0.0019"></a> সাধুলোকেন অনুভুত্তং সুভং ফলং।</p>
<p class="gathalast">সব্বেহি সাধুজন্তুহি অনুভুত্তং কম্মফলং॥</p>
<p class="gatha1">সব্বেন পুঞ্ঞকম্মেন পপ্পোতি ৰিপুলং সুখং।</p>
<p class="gathalast">সব্বেহি গুণৰন্তেহি পপ্পোন্তি ৰিপুলং সুখং॥</p>
<p class="gatha1">সব্বস্স ভিক্খুসঙ্ঘস্স মহাদানং দদন্তি চ।</p>
<p class="gathalast">সব্বেসং সীলৰন্তানং দানং দেন্তি মহাজনা॥</p>
<p class="gatha1">সব্বস্মা সাধুলোকস্মা অপেন্তীতি দুবুদ্ধিনো।</p>
<p class="gathalast">সব্বেহি ভগৰন্তেহি নিচ্ছরন্তি ছরংসিযো॥</p>
<p class="gatha1">সব্বস্স পুঞ্ঞকম্মস্স ৰিপাকো হোতি সব্বদা।</p>
<p class="gathalast">সব্বেসং সিলৰন্তানং সীলগন্ধো অনুত্তরো॥</p>
<p class="gatha1">সব্বস্মিং বুদ্ধধম্মে চ সদা রমতি মে মনো।</p>
<p class="gathalast">সব্বেসু চ ৰিহারেসু থূপে কারেসি খত্তিযোতি॥</p>
<p class="centered">ইতি পঠমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="gatha1">সব্বা অলঙ্কতা লঙ্কা থেরস্স ৰিয আসি চ।</p>
<p class="gathalast">সব্বা তে ফাসুকা ভগ্গা গহকূটং ৰিসং খিতং॥</p>
<p class="gatha1">ভো সব্বে চ পজে ত্বম্পি দানং দদাহি সব্বদা।</p>
<p class="gathalast">ভো সব্বাযো পজা তুম্হে সীলং রক্খথ সব্বদা॥</p>
<p class="gatha1">সব্বং দিট্ঠিং জহিত্বান সম্মাদিট্ঠিংচ ভাৰযে।</p>
<p class="gathalast">সব্বাযো দিট্ঠিযো হন্ত্বা খেমং গচ্ছন্তি পণ্ডিতা॥</p>
<p class="gatha1">সব্বস্সা অস্সু কঞ্ঞায নিচ্চং কম্মং করীয্যতে।</p>
<p class="gathalast">সব্বাহি চাপি ইত্থীহি পাপকম্মং করীয্যতে॥</p>
<p class="gatha1">সব্বস্সা পন ৰিজ্জায জীৰন্তীতি মহাজনা।</p>
<p class="gathalast">সব্বাহি চ নদীহেৰ খেত্তং ৰপতি কস্সকো॥</p>
<p class="gatha1">সব্বস্সা অস্সু কঞ্ঞায চিত্তং নদেতি পণ্ডিতো।</p>
<p class="gathalast">সব্বাসানং নদীনংচ ৰিসং নদেতি পণ্ডিতো॥</p>
<p class="gatha1">সব্বস্সা পন তণ্হায ৰিমুত্তস্স নত্থি ভযং।</p>
<p class="gathalast">সব্বাহি পন কঞ্ঞাহি অভিরূপাঙ্গনা অযং॥</p>
<p class="gatha1">সব্বস্সা অস্সু কঞ্ঞায আভরণং মনোরমং।</p>
<p class="gathalast">সব্বাসং পন গঙ্গানং মহোঘো হোতি সব্বদা॥</p>
<p class="gatha1">সব্বস্সা নেৰ কঞ্ঞায চিত্তং রমতি পণ্ডিতো।</p>
<p class="gathalast">সব্বাসু চেৰ গঙ্গাসু মচ্ছা চরন্তি সব্বদাতি॥</p>
<p class="centered">ইতি <a name="V0.0020"></a> দুতিযো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="gatha1">সব্বং পুঞ্ঞঞ্হি নিস্সেসং মনুস্সত্তে সমিজ্ঝতি।</p>
<p class="gathalast">সব্বানি অস্সু চিত্তানি সযমেৰপি ভিজ্জরে॥</p>
<p class="gatha1">ভো সব্বা ভূত কল্যাণং পুঞ্ঞং করোহি সব্বদা।</p>
<p class="gathalast">ভো সব্বানিচ ভূতানি পুঞ্ঞং করোথ সব্বদা॥</p>
<p class="gatha1">সব্বং ভণ্ডং সমাদায পারং তিণ্ণোসি ব্রাহ্মণো।</p>
<p class="gathalast">সব্বানি অস্সু পুঞ্ঞানি কত্বান তিদিৰং গতো॥</p>
<p class="gatha1">সব্বেন পন ভূতেন অনুভুত্তং কম্মফলং।</p>
<p class="gathalast">সব্বেহি গুণৰন্তেহি পুঞ্ঞকম্মং করীয্যতে॥</p>
<p class="gatha1">সব্বেন পুঞ্ঞকম্মেন পপ্পোতি ৰিপুলং সুখং।</p>
<p class="gathalast">সব্বেহি গুণৰন্তেহি সুচরন্তি বহুজ্জনা॥</p>
<p class="gatha1">সব্বস্স গুণৰন্তস্স দানং দদেয্য পণ্ডিতো।</p>
<p class="gathalast">সব্বেসং সীলৰন্তানং দানং দদেয্য পণ্ডিতো॥</p>
<p class="gatha1">সব্বস্মা পাপকম্মস্মা চিত্তং পন নিৰারযে।</p>
<p class="gathalast">সব্বেহি বলৰন্তেহি অপেন্তীতি কেচি জনা॥</p>
<p class="gatha1">সব্বস্স পাপকম্মস্স ৰিপাকো হোতি কিব্বিসং।</p>
<p class="gathalast">সব্বেসং পুঞ্ঞকম্মানং ৰিপাকো হোতি সোভনো॥</p>
<p class="gatha1">সব্বস্মিং পুঞ্ঞকম্মেচ সদা রমতি মে মনো।</p>
<p class="gathalast">সব্বেসু সীলৰন্তেসু পসীদতি মহাজনো॥</p>
<p class="centered">ইতি ততিযো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">পুব্বো কালো অতিক্কন্তো অহোসি</p>
<p class="unindented">পুব্বে কালা চ অতিক্কন্তা অহেসুং</p>
<p class="unindented">ভো পুব্ব কাল অতিক্কন্তো অভৰি</p>
<p class="unindented">ভো পুব্বে কালা অতিক্কন্তা অভৰিত্থ</p>
<p class="unindented">পুব্বং কালং পস্সতি লোকনাথো</p>
<p class="unindented">পুব্বে কালে পস্সতি লোকৰিদূ</p>
<p class="unindented">পুব্বেনাচরিযেন সিস্সো বোধীযী।</p>
<p class="unindented">পুব্বেহি আচরিযেহি সিস্সা বোধীযিংসু</p>
<p class="unindented">পুব্বেনাচরিযেন সিস্সো সুখীজাতো</p>
<p class="unindented">পুব্বেহি আচরিযেহি সিস্সা সুখীজাতি</p>
<p class="unindented">পুব্বস্সাচরিযস্স সক্কারং অকরী</p>
<p class="unindented">পুব্বেসং <a name="V0.0021"></a> আচরিযানং সক্কারং অকরুং</p>
<p class="unindented">পুব্বাচরিযস্মা অন্তরধাযী অন্তেৰাসিকো</p>
<p class="unindented">পুব্বেহি আচরিযেহি অন্তরধাযিংসু অন্তেৰাসিকা</p>
<p class="unindented">পুব্বস্সাচরিযস্স অন্তেৰাসিকা বহৰো</p>
<p class="unindented">পুব্বেসং আচরিযানং গুণঘোসা অহেসুং</p>
<p class="unindented">পুব্বে দীপঙ্করো নাম সত্থা উদপাদি</p>
<p class="unindented">পুব্বেসু অট্ঠৰীসতি চক্কৰত্তিরাজানো অহেসুং।</p>
<p class="centered">ইতি চতুত্থো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">পুব্বা যা কাচি কঞ্ঞা বহুং পুঞ্ঞং অকরী</p>
<p class="unindented">পুব্বা যা কাচি কঞ্ঞাযো বহুং পুঞ্ঞং অকরুং</p>
<p class="unindented">ভো পুব্বে কঞ্ঞে বহুং পুঞ্ঞং অকরো</p>
<p class="unindented">ভো পুব্বা কঞ্ঞাযো বহুং পুঞ্ঞং অকরিত্থ</p>
<p class="unindented">পুব্বং যং কিংচি কঞ্ঞং পুঞ্ঞং কারাপযী</p>
<p class="unindented">পুব্বা যা কাচি কঞ্ঞাযো পুঞ্ঞে কারাপযী</p>
<p class="unindented">পুব্বায যায কাযচি কঞ্ঞায পুঞ্ঞং কতং</p>
<p class="unindented">পুব্বাহি যাহি কাহিচি কঞ্ঞাহি পুঞ্ঞানি কতানি</p>
<p class="unindented">পুব্বায যায কাযচি কঞ্ঞায কোচি অনুচরী</p>
<p class="unindented">পুব্বাহি যাহি কাহিচি কঞ্ঞাহি কেচি অনুচরিংসু</p>
<p class="unindented">পুব্বায যায কাযচি কঞ্ঞায আভরণং অদদী</p>
<p class="unindented">পুব্বাসং যাসংচি কঞ্ঞানং আভরণাতি অদদিংসু</p>
<p class="unindented">পুব্বায যায কাযচি কঞ্ঞায কোচি পুরিসো অপেতো।</p>
<p class="unindented">পুব্বাহি যায কাহিচি কঞ্ঞাহি কেচি পুরিসা অপেতা</p>
<p class="unindented">পুব্বায যায কাযচি কঞ্ঞায মাতাপিতরো অহেসুং</p>
<p class="unindented">পুব্বাসং যাসং কাসংচি কঞ্ঞানং ৰত্থাভরণানি</p>
<p class="unindented">পুব্বাযং যায কাযচি কঞ্ঞাযং চিত্তং পতিট্ঠিতং</p>
<p class="unindented">পুব্বাসু যাসু কাসুচি কঞ্ঞাসু চিত্তং পতিট্ঠিতং।</p>
<p class="centered">ইতি পঞ্চমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">পুব্বং যং কিংচি পন বহুং পুচ্চং অকরী</p>
<p class="unindented">পুব্বানি যানি কানিচি বহুং পুঞ্ঞং অকরুং</p>
<p class="unindented">ভো পুব্ব ভূত ত্বং বহুং পুঞ্ঞং অকরো</p>
<p class="unindented">ভো পুব্বানি ভূতানি বহুং পুঞ্ঞং অকরিত্থ</p>
<p class="unindented">পুব্বং যং কিংচি পুঞ্ঞং কারাপযী একচ্চো</p>
<p class="unindented">পুব্বানি যানি কানিচি পুঞ্ঞে কারাপযিংসু একচ্চে</p>
<p class="unindented">পুব্বেন <a name="V0.0022"></a> যেন কেনচি ৰিহারো কারাপিতো</p>
<p class="unindented">পুব্বেহি যেহি কেহিচি ৰিহারা কারাপিতা</p>
<p class="unindented">পুব্বেন যেন কেনচি পুরিসো সুখীজাতো</p>
<p class="unindented">পুব্বেহি যেহি কেহিচি পুরিসা সুখীজাতা</p>
<p class="unindented">পুব্বস্স যস্স কস্সচি সিলাঘতে একচ্চো</p>
<p class="unindented">পুব্বেসং যেসং কেসংচি সিলাঘতে একচ্চো</p>
<p class="unindented">পুব্বা যস্মা কস্মাচ একচ্চো অপেতো</p>
<p class="unindented">পুব্বেহি যেহি কেহিচি একচ্চে অপেতা</p>
<p class="unindented">পুব্বস্স যস্স কস্সচি পরিগ্গহো অহোসি</p>
<p class="unindented">পুব্বেসং যেসং কেসংচি পরিগ্গহা অহেসুং</p>
<p class="unindented">পুব্বে যস্মিং কস্মিংচি চিত্তং পতিট্ঠিতং</p>
<p class="unindented">পুব্বেসু যেসু কেসুচি চিত্তং পতিট্ঠিতং।</p>
<p class="centered">ইতি ছট্ঠো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">একো পুরিসো দেৰদত্তং ওদনং পাচেতি</p>
<p class="unindented">একে পুরিসা দেৰদত্তং ওদনং পাচেন্তি</p>
<p class="unindented">একং সিস্সং ধম্মং পাঠেতি আচরিযো</p>
<p class="unindented">একে সিস্সে ধম্মং পাঠেন্তি আচরিযা</p>
<p class="unindented">একেন গরুনা সিস্সো ধম্মং বোধাপীযতে</p>
<p class="unindented">একেহি গরূহি সিস্সো ধম্মং বোধাপিতো</p>
<p class="unindented">একেন গরুনা অন্তেৰাসিকো সুখীজাতো</p>
<p class="unindented">একেহি গরূহি অন্তেৰাসিকা সুখীজাতা</p>
<p class="unindented">একস্স গরুনো সক্কারং করোতি সিস্সো</p>
<p class="unindented">একেসং গরূনং সক্কারং করোন্তি সিস্সা</p>
<p class="unindented">একম্হা গরুনা সিক্খং গণ্হাতি সিস্সো</p>
<p class="unindented">একেহি গরূহি সিক্খং গণ্হন্তি সিস্সা</p>
<p class="unindented">একস্স গরুনো খো পন পরিক্খারো হোতি</p>
<p class="unindented">একেসং গরূনং খো পন গুণঘোসো হোতি</p>
<p class="unindented">একম্হি গরুস্মিং পন সিস্সো পসীদতি</p>
<p class="unindented">একেসু গরূসু পন সিস্সা পসীদন্তি।</p>
<p class="centered">ইতি সত্তমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">একা কঞ্ঞা পন দেৰদত্তং কম্বলং যাচতে</p>
<p class="unindented">একা কঞ্ঞাযো দেৰদত্তং কম্বলং যাচন্তে</p>
<p class="unindented">একং কঞ্ঞং ওদনং পাচাপযতি পুরিসো</p>
<p class="unindented">একা <a name="V0.0023"></a> কঞ্ঞাযো ওদনং পাচাপযন্তি পুরিসা</p>
<p class="unindented">একায কঞ্ঞায ওদনো পচিত্বা ভুজ্জতে</p>
<p class="unindented">একাহি কঞ্ঞাহি ওদনো পচিত্বা ভুত্তো</p>
<p class="unindented">একায কঞ্ঞায সুখং পাপুণাতি একচ্চো</p>
<p class="unindented">একাহি কঞ্ঞাহি সুখং পাপুণন্তি একচ্চে</p>
<p class="unindented">একায কঞ্ঞায আভরণং দেতি পুরিসো</p>
<p class="unindented">একাসং কঞ্ঞানং আভরণানি দেন্তি পুরিসা</p>
<p class="unindented">একায কঞ্ঞায ভযং উপ্পজ্জতি সিলৰতং</p>
<p class="unindented">একাহি কঞ্ঞাহি ভযানি উপ্পজ্জন্তি সীলৰতং</p>
<p class="unindented">একায কঞ্ঞায পন ৰত্থাভরণং হোতি</p>
<p class="unindented">একাসং কঞ্ঞানং পন ৰত্থাভরণানি হোন্তি</p>
<p class="unindented">একাযং কঞ্ঞাযং যো কোচিপসীদতি</p>
<p class="unindented">একাসু কঞ্ঞাসু যে কেচি পসীদন্তি।</p>
<p class="centered">ইতি অট্ঠমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">একং কুলং পন বহুং পুঞ্ঞং পসৰতি</p>
<p class="unindented">একানি কুলানি বহুং পুঞ্ঞং পসৰন্তি</p>
<p class="unindented">একং কুলং পুঞ্ঞং কারাপেতি গুণৰা</p>
<p class="unindented">একানি কুলানি পুঞ্ঞং কারাপেতি গুণৰা</p>
<p class="unindented">একেন কুলেন ভিক্খু ভত্তং ভোজাপিতো</p>
<p class="unindented">একেহি কুলেহি ভিক্খূ ভত্তং ভোজাপিতা</p>
<p class="unindented">একেন কুলেন সুখং পাপুণাতি ভিক্খু</p>
<p class="unindented">একেহি কুলেহি সুখং পাপুণন্তি ভিক্খূ</p>
<p class="unindented">একস্স কুলস্স পন উসূযতি দুজ্জনো</p>
<p class="unindented">একেসং কুলানং পন উসূযন্তি দুজ্জনা</p>
<p class="unindented">একস্মা কুলম্হা যো কোচি পব্বজিতো</p>
<p class="unindented">একেহি কুলেহি যে কেচি পব্বজিতা</p>
<p class="unindented">একস্স কুলস্স পন নাম গোত্তাদি</p>
<p class="unindented">একেসং কুলানং পন নাম গোত্তাদযো</p>
<p class="unindented">একস্মিং কুলম্হি যো কোচি পসীদতি</p>
<p class="unindented">একেসু কুলেসু যে কেচি পসীদন্তি।</p>
<p class="centered">ইতি নৰমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">যো কোচি তং পুরিসং ওদনং পাচাপেতি</p>
<p class="unindented">যে কেচি তং পুরিসং ওদনং পাচাপেন্তি</p>
<p class="unindented">যং কিংচি দাসং গামং গমযতি সামিকো</p>
<p class="unindented">যে <a name="V0.0024"></a> কেচি দাসে গামং গমযতি সামিকো</p>
<p class="unindented">যেন কেনচি সূদেন ওদনো পাচাপীযতে</p>
<p class="unindented">যেহি কেহিচি সূদেহি ওদনো পাচাপিতো</p>
<p class="unindented">যেন কেনচি সুখং পাপুণাতি ভিক্খুসঙ্ঘো</p>
<p class="unindented">যেহি কেহিচি সুখং পাপুণাতি ভিক্খুসঙ্ঘো</p>
<p class="unindented">যস্স কস্সচি দানং দেতি সদ্ধো সপ্পুরিসো</p>
<p class="unindented">যেসং কেসংচি দানং দেন্তি সপ্পুরিসা</p>
<p class="unindented">যস্মা কস্মাচি গরুণা অন্তরধাযতি সিস্সো</p>
<p class="unindented">যেহি কেহিচি গরূহি অন্তরধাযন্তি সিস্সা</p>
<p class="unindented">যস্স কস্সচি ভিক্খুনো পাদে ৰন্দামি</p>
<p class="unindented">যেসং কেসংচি ভিক্খূনং পাদে ৰন্দাম</p>
<p class="unindented">যস্মিং কস্মিংচি আসনে নিসীদতি কোচি</p>
<p class="unindented">যেসু কেসুচি আসনেসু নিসীদন্তি কেচি।</p>
<p class="centered">ইতি দসমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">যা কাচি ৰনিতা পন দাসিং কম্মং কারাপেতি</p>
<p class="unindented">যা কাচি ৰনিতাযো দাসী কম্মে কারাপেন্তি</p>
<p class="unindented">যং কিংচি ৰনিতং পুঞ্ঞং কারাপেতি পুরিসো</p>
<p class="unindented">যা কাচি ৰনিতাযো পুঞ্ঞং কারেন্তি পুরিসা</p>
<p class="unindented">যায কাযচি ৰনিতায সামি ভত্তং ভোজাপীযতে</p>
<p class="unindented">যাহি কাহিচি ৰনিতাহি সামি ভত্তং ভোজাপিতো</p>
<p class="unindented">যায কাযচি ৰনিতায সুখং পাপুণাতি সামিকো</p>
<p class="unindented">যাহি কাহিচি ৰনিতাহি সুখং পাপুণন্তি সামিকা</p>
<p class="unindented">যায কাযচি ৰনিতায আভরণং দেতি সামিকো</p>
<p class="unindented">যাসং কাসংচি ৰনিতানং আভরণং দেতি সামিকো</p>
<p class="unindented">যায কাযচি ৰনিতায অপেতি যো কোচি</p>
<p class="unindented">যাহি কাহিচি ৰনিতাহি অপেতি যো কোচি</p>
<p class="unindented">যায কাযচি ৰনিতায পুত্তাপি বহৰো</p>
<p class="unindented">যাসং কাসংচি ৰনিতানং আভরণানি হোন্তি</p>
<p class="unindented">যাযং কাযংচি ৰনিতাযং মে চিত্তং ন রমতি</p>
<p class="unindented">যাসু কাসুচি ৰনিতাসু মে চিত্তানি ন রমন্তি।</p>
<p class="centered">ইতি একাদসমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">যং কিংচি কুলং পন বহুং পুঞ্ঞং পসৰতি</p>
<p class="unindented">যানি কানিচি কুলানি বহুং পুঞ্ঞং পসৰন্তি</p>
<p class="unindented">যং কিংচি বহুং পুঞ্ঞং কারাপেতি কোচি</p>
<p class="unindented">যানি <a name="V0.0025"></a> কানিচি বহুং পুঞ্ঞং কারেন্তি কেচি</p>
<p class="unindented">যেন কেনচি কুলেন সক্কারো কতো</p>
<p class="unindented">যেহি কেহিচি কুলেহি সক্কারা কতা</p>
<p class="unindented">যেন কেনচি কুলেন একচ্চো জীৰতি</p>
<p class="unindented">যেহি কেহিচি কুলেহি একচ্চে জীৰন্তি</p>
<p class="unindented">যস্স কস্সচি কুলস্স উপকারং অকাসি</p>
<p class="unindented">যেসং কেসংচি কুলানং উপকারং অকাসুং</p>
<p class="unindented">যস্মা কস্মাচি কুলম্হা অপেতি একচ্চো</p>
<p class="unindented">যেহি কেহিচি কুলেহি অপেন্তি একচ্চে</p>
<p class="unindented">যস্স কস্সচি কুলস্স নাম গোত্তাদি</p>
<p class="unindented">যেসং কেসংচি কুলানং নাম গোত্তাদযো</p>
<p class="unindented">যস্মিং কস্মিংচি কুলে একচ্চো পসীদতি</p>
<p class="unindented">যেসু কেসুচি কুলেসু একচ্চে পসীদন্তি।</p>
<p class="centered">ইতি দ্বাদসমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">সো সূদজেট্ঠো সূদেন ওদনং পাচেতি</p>
<p class="unindented">তে সূদজেট্ঠা সূদেহি ওদনং পাচেন্তি</p>
<p class="unindented">তং যঞ্ঞদত্তং কম্বলং যাচতে ব্রাহ্মণো</p>
<p class="unindented">তে যঞ্ঞদত্তেন কম্বলং যাচন্তে ব্রাহ্মণা</p>
<p class="unindented">তেন ব্রাহ্মণেন গহপতি ধনং যাচীযতে</p>
<p class="unindented">তেহি সিস্সেহি গরু সত্থং পুচ্ছীযতে</p>
<p class="unindented">তেন পুপ্ফেন বুদ্ধং যজতি সপ্পুরিসো</p>
<p class="unindented">তেহি পুপ্ফেহি বুদ্ধং যজন্তি সপ্পুরিসা</p>
<p class="unindented">তস্স ভিক্খুস্স দানং দেতি সপ্পুরিসো</p>
<p class="unindented">তেসং যাচকানং ধনং দদাতি ধনৰা</p>
<p class="unindented">তম্হা হিমৰতা পভৰন্তি পঞ্চমহা নদিযো</p>
<p class="unindented">তেহি লোভনীযেহি ধম্মেহি সুদ্ধো অসংসট্ঠো</p>
<p class="unindented">তস্স বুদ্ধস্স পচ্ছতো পচ্ছতো অনুবন্ধিংসু</p>
<p class="unindented">তেসং ভিক্খূনংযেৰ পত্তচীৰরানি হোন্তি</p>
<p class="unindented">তস্মিং আসনেযেৰ নিসীদতি ভিক্খু</p>
<p class="unindented">তেসু ভিক্খূসু পন মে মনো রমতি।</p>
<p class="centered">ইতি তেরসমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">সা খত্তিযকঞ্ঞা পন বহুং পুঞ্ঞং পসৰতি</p>
<p class="unindented">তা খত্তিযকঞ্ঞাযো বহুং পুঞ্ঞং পসৰন্তি</p>
<p class="unindented">তং খত্তীযকঞ্ঞং পুঞ্ঞং কারাপেতি রাজা</p>
<p class="unindented">তা <a name="V0.0026"></a> খত্তিযকঞ্ঞাযো পুঞ্ঞং কারাপেতি রাজা</p>
<p class="unindented">তায খত্তিযকঞ্ঞায পুঞ্ঞং কারাপীযতে</p>
<p class="unindented">তাহি খত্তিযকঞ্ঞাহি পুঞ্ঞং কারাপিতো</p>
<p class="unindented">তায খত্তিযকঞ্ঞায মহাজনো সুচরতি</p>
<p class="unindented">তাহি খত্তিযকঞ্ঞাহি মহাজনা সুচরন্তি</p>
<p class="unindented">তায খত্তিযকঞ্ঞায উপতিট্ঠেয্য অমচ্চো</p>
<p class="unindented">তাসং খত্তিযকঞ্ঞানং উপতিট্ঠেয্যুং অমচ্চা</p>
<p class="unindented">তায খত্তিযকঞ্ঞায পন ভযং উপ্পজ্জতি</p>
<p class="unindented">তাহি খত্তিযকঞ্ঞাহি পন ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">তায খত্তিযকঞ্ঞায পন ৰত্থাভরণানি</p>
<p class="unindented">তাসং খত্তিযকঞ্ঞানং ৰত্থাভরণানি হোন্তি</p>
<p class="unindented">তাযং খত্তিয কঞ্ঞাযং পসীদতি যো কোচি</p>
<p class="unindented">তাসু খত্তিযকঞ্ঞাসু পসীদন্তি যে কেচি।</p>
<p class="centered">ইতি চুদ্দসমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">তং কুলং নিচ্চং বহুং পুঞ্ঞং পসৰতি</p>
<p class="unindented">তানি কুলানি পন বহুং পুঞ্ঞং পসৰন্তি</p>
<p class="unindented">তং কুলং উদ্দিস্স পুঞ্ঞং করোতি কোচি</p>
<p class="unindented">তানি কুলানি উদ্দিস্স পুঞ্ঞানি করোন্তি কেচি</p>
<p class="unindented">তেন কুলেন পুঞ্ঞকম্মং কারাপীযতে</p>
<p class="unindented">তেহি কুলেহি পুঞ্ঞকম্মং কারাপিতো</p>
<p class="unindented">তেন কুলেন বহুজ্জনো সুচরতি</p>
<p class="unindented">তেহি কুলেহি বহুজ্জনা সুচরন্তি</p>
<p class="unindented">তস্স কুলস্স উপকারঞ্চ অকাসি</p>
<p class="unindented">তেসং কুলানং উপকারঞ্চ অকংসু</p>
<p class="unindented">তস্মা কুলম্হা যো কোচি অপেতি</p>
<p class="unindented">তেহি কুলেহি যে কেচি অপেন্তি</p>
<p class="unindented">তস্স কুলস্স মহাভোগো হোতি</p>
<p class="unindented">তেসং কুলানং মহদ্ধনো চ হোতি</p>
<p class="unindented">তম্হি কুলস্মিং পসীদতি যো কোচি</p>
<p class="unindented">তেসু কুলেসু পসীদন্তি যে কেচি।</p>
<p class="centered">ইতি পঞ্চদসমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">এসো সিস্সো চ গরুং ধম্মং পুচ্ছতি</p>
<p class="unindented">এতে সিস্সা চ গরুং ধম্মং পুচ্ছন্তি</p>
<p class="unindented">এতং সিস্সং ধম্মং বোধযতি গরু</p>
<p class="unindented">এতে <a name="V0.0027"></a> সিস্সে ধম্মং বোধযন্তি গরূ</p>
<p class="unindented">এতেন গরুনা সিস্সো ধম্মং বোধাপীযতে</p>
<p class="unindented">এতেহি গরূহি সিস্সো ধম্মং বোধাপিতো</p>
<p class="unindented">এতেন গরুনং সুখং পাপুণাতি সিস্সো</p>
<p class="unindented">এতেহি গরূহি সুখং পাপুণন্তি সিস্সা</p>
<p class="unindented">এতস্স গরুনো সক্কারং করোতি সিস্সো</p>
<p class="unindented">এতেসং গরূনং সক্কারং করোন্তি সিস্সা</p>
<p class="unindented">এতস্মা গরুনা পন অন্তরধাযতি সিস্সো</p>
<p class="unindented">এতেহি গরূহি পন অন্তরধাযন্তি সিস্সা</p>
<p class="unindented">এতস্স গরুনো অন্তেৰাসিকা বহৰো</p>
<p class="unindented">এতেসং গরূনং অন্তেৰাসিকা বহৰো</p>
<p class="unindented">এতস্মিং গরুম্হি পসীদতি অন্তেৰাসিকো</p>
<p class="unindented">এতেসু গরূসু পসীদন্তি অন্তেৰাসিকা।</p>
<p class="centered">ইতি সোল়সমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">এসা ৰনিতা পন দাসিং কম্মং কারাপেতি।</p>
<p class="unindented">এতা ৰনিতাযো দাসিং কম্মং কারাপেন্তি</p>
<p class="unindented">এতং ৰনিতং পুঞ্ঞং কারযতি পুরিসো</p>
<p class="unindented">এতা ৰনিতাযো পুঞ্ঞং কারযন্তি পুরিসা</p>
<p class="unindented">এতায ৰনিতায ওদনো পচিত্বা ভুজ্জতে</p>
<p class="unindented">এতাহি ৰনিতাহি ওদনো পচিত্বা ভুত্তো</p>
<p class="unindented">এতায ৰনিতায কোচি জীৰিকং কপ্পেতি</p>
<p class="unindented">এতাহি ৰনিতাহি কেচি জীৰিকং কপ্পেন্তি</p>
<p class="unindented">এতিস্সা ৰনিতায পিলন্ধনং দেতি পুরিসো</p>
<p class="unindented">এতাসং ৰনিতানং পিলন্ধনং দেন্তি পুরিসা</p>
<p class="unindented">এতায ৰনিতায পন যো কোচি অপেতি</p>
<p class="unindented">এতাহি ৰনিতাহি পন যে কেচি অপেন্তি</p>
<p class="unindented">এতিস্সা ৰনিতায পন ৰত্থাভরণানি হোন্তি</p>
<p class="unindented">এতাসানং ৰনিতানং নাম গোত্তাদযো</p>
<p class="unindented">এতিস্সং ৰনিতাযং অভিরমতি একচ্চো</p>
<p class="unindented">এতাসু ৰনিতাসু অভিরমন্তি একচ্চে।</p>
<p class="centered">ইতি সত্তদসমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">এতং কুলং পন বহুং পুঞ্ঞং পসৰতি</p>
<p class="unindented">এতানি কুলানি বহুং পুঞ্ঞং পসৰন্তি</p>
<p class="unindented">এতং কুলং পন পস্সতি যো কোচি</p>
<p class="unindented">এতানি <a name="V0.0028"></a> কুলানি পন পস্সন্তি যে কেচি</p>
<p class="unindented">এতেন কুলেন সঙ্ঘো ভত্তং ভোজাপীযতে</p>
<p class="unindented">এতেহি কুলেহি সঙ্ঘো ভত্তং ভোজাপীতো</p>
<p class="unindented">এতেন কুলেন পন জনো সুখং পাপুণাতি</p>
<p class="unindented">এতেহি কুলেহি পন জনা সুখং পাপুণন্তি</p>
<p class="unindented">এতস্স কুলস্স খো পন ধনং দদাতি ধনৰা</p>
<p class="unindented">এতেসং কুলানং পন ধনং দদন্তি ধনৰন্তা</p>
<p class="unindented">এতস্মা কুলম্হা খো পন একচ্চো ন অপেতি</p>
<p class="unindented">এতেহি কুলেহি খো পন একচ্চে ন অপেন্তি</p>
<p class="unindented">এতস্স কুলস্স পন মহাভোগো হোতি</p>
<p class="unindented">এতেসং কুলানং পন মহাভোগা হোন্তি</p>
<p class="unindented">এতস্মিং কুলম্হি পন মে মনো রমতি</p>
<p class="unindented">এতেসু কুলেসু মে মনানি ন রমন্তি।</p>
<p class="centered">ইতি অট্ঠাদসমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">অযং জনো পন তং পুরিসং পুঞ্ঞং কারাপেতি</p>
<p class="unindented">ইমে জনা তে পুরিসে পুঞ্ঞং কারাপেন্তি</p>
<p class="unindented">ইমং জনা পুঞ্ঞং কারাপেতি সপ্পুরিসো</p>
<p class="unindented">ইমে জনে পুঞ্ঞং কারাপেন্তি সপ্পুরিসা</p>
<p class="unindented">ইমিনা জনেন কম্মফলং অনুভূযতে</p>
<p class="unindented">ইমেহি জনেহি কম্মফলানি অনুভুত্তানি</p>
<p class="unindented">ইমিনা জনেন যো কোচি সুচরতি</p>
<p class="unindented">ইমেহি জনেহি যে কেচি সুচরন্তি</p>
<p class="unindented">ইমস্স জনস্স সক্কারঞ্চ করোতি</p>
<p class="unindented">ইমেসং জনানং সক্কারং করোন্তি</p>
<p class="unindented">ইমম্হা জনম্হা ৰিঞ্ঞুতং পত্তোস্মি</p>
<p class="unindented">ইমেহি জনেহি ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">ইমস্স জনস্স খেত্তৰত্থূনি হোন্তি</p>
<p class="unindented">ইমেসং জনানঞ্চ পহূতধনধঞ্ঞানি</p>
<p class="unindented">ইমম্হি জনস্মিং পসীদতি যো কোচি</p>
<p class="unindented">ইমেসু জনেসু পসীদন্তি যে কেচি।</p>
<p class="centered">ইতি একূনৰীসতিমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">অযং কঞ্ঞা পন বহুং পুঞ্ঞং পসৰতি</p>
<p class="unindented">ইমা কঞ্ঞাযো বহুং পুঞ্ঞং পসৰন্তি</p>
<p class="unindented">ইমং কঞ্ঞং পুঞ্ঞং কারাপেতি মাতা</p>
<p class="unindented">ইমা কঞ্ঞাযো পুঞ্ঞং কারাপেতি মাতা</p>
<p class="unindented">ইমায <a name="V0.0029"></a> কঞ্ঞায পন তিলানি ভজ্জীযন্তে</p>
<p class="unindented">ইমাহি কঞ্ঞাহি পন ধঞ্ঞানি ভজ্জীযন্তে</p>
<p class="unindented">ইমায কঞ্ঞায সুখং পাপুণাতি মাতা</p>
<p class="unindented">ইমাহি কঞ্ঞাহি সুখং পাপুণাতি মাতা</p>
<p class="unindented">ইমিস্সা কঞ্ঞায আভরণং দেতি সামি</p>
<p class="unindented">ইমাসং কঞ্ঞানং আভরণং দেতি সামি</p>
<p class="unindented">ইমায কঞ্ঞায পন অপেতি যো কোচি</p>
<p class="unindented">ইমাহি কঞ্ঞাহি পন অপেতি যো কোচি</p>
<p class="unindented">ইমিস্সা কঞ্ঞায পন আভরণানি হোন্তি</p>
<p class="unindented">ইমাসং কঞ্ঞানং পন আভরণানি হোন্তি</p>
<p class="unindented">ইমিস্সং কঞ্ঞাযং পন চিত্তং পতিট্ঠিতং</p>
<p class="unindented">ইমাসু কঞ্ঞাসু চিত্তং পন নপতিট্ঠিতং।</p>
<p class="centered">ইতি ৰীসতিমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">ইমং চিত্তং পন অত্তনো সন্তানং ৰিজানাতি</p>
<p class="unindented">ইমানি চিত্তানি অত্তনো সন্তানং ৰিজানন্তি</p>
<p class="unindented">ইমং চিত্তং সঞ্ঞমেস্সন্তি যে কেচি</p>
<p class="unindented">ইমে চিত্তে সঞ্ঞমেস্সন্তি যে কেচি</p>
<p class="unindented">ইমিনা চিত্তেন সব্বোপি জনো নীয্যতি</p>
<p class="unindented">ইমেহি চিত্তেহি সব্বে জনা নীয্যন্তি</p>
<p class="unindented">ইমিনা চিত্তেন যো কোচি সংকিলিস্সতি</p>
<p class="unindented">ইমেহি চিত্তেহি যো কোচি ৰিসুজ্ঝতি</p>
<p class="unindented">ইমস্স চিত্তস্স ওৰাদং দেতি যো কোচি</p>
<p class="unindented">ইমেসং চিত্তানং ওৰাদং দেন্তি যে কেচি</p>
<p class="unindented">ইমস্মা চিত্তম্হা আরম্মণং উপ্পজ্জতি</p>
<p class="unindented">ইমেহি চিত্তেহি আরম্মণানি উপ্পজ্জন্তি</p>
<p class="unindented">ইমস্স চিত্তস্স অনিচ্চধম্মস্স ৰসং অন্বগূ</p>
<p class="unindented">ইমেসানং চিত্তানং পরিৰিতক্কো উদপাদি</p>
<p class="unindented">অস্মিং চিত্তে অরক্খিতে কাযকম্মং অরক্খিতং</p>
<p class="unindented">ইমেসু চিত্তেসু গুত্তেসু কাযকম্মং রক্খিতং।</p>
<p class="centered">ইতি একৰীসতিমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">অসু মহারাজা চতুহি সঙ্গহৰত্থূহি জনং তোসেতি</p>
<p class="unindented">অমূ মহারাজা চতূহিসঙ্গহৰত্থূহি জনং তোসেন্তি</p>
<p class="unindented">অমুং মহারাজানং সক্কচ্চং উপসঙ্কমতি মহাজনো</p>
<p class="unindented">অমূযো মহারাজে সক্কচ্চং উপসঙ্কমতি মহাজনো</p>
<p class="unindented">অমুনা <a name="V0.0030"></a> মহারাজেনপি মহাপাসাদো কারাপীযতে</p>
<p class="unindented">অমূহি মহারাজেহি মহাৰিহারোপি কারাপিতো</p>
<p class="unindented">অমুনা মহারাজেন খো পন মহাজনো সুচরতি</p>
<p class="unindented">অমূহি মহারাজেহি খো পন মহাজনো সুচরতি</p>
<p class="unindented">অমুস্স মহারাজস্স পণ্ণাকারং দেতি মহাজনো</p>
<p class="unindented">অমূসানং মহারাজানং পণ্ণাকারং দেন্তি মহাজনা</p>
<p class="unindented">অমুস্মা মহারাজম্হা পন মহব্ভযং উপ্পজ্জতি</p>
<p class="unindented">অমূহি মহারাজেহি মহব্ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">অমূস্স মহারাজস্স ৰপ্পমঙ্গলঞ্চ হোতি</p>
<p class="unindented">অমূসানং মহারাজানং ৰপ্পমঙ্গলানি হোন্তি</p>
<p class="unindented">অমুস্মিং মহারাজে খো পন মহাজনো পসীদতি</p>
<p class="unindented">অমূসু মহারাজেসু খো পন মহাজনা পসীদন্তি।</p>
<p class="centered">ইতি দ্বেৰীসতিমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">অসু উপাসিকা পন সক্কচ্চং ধম্মং সুণাতি</p>
<p class="unindented">অমুযো উপাসিকাযো সক্কচ্চং ধম্মং সুণন্তি</p>
<p class="unindented">অমুং উপাসিকং পুঞ্ঞং কারাপেতি সদ্ধো</p>
<p class="unindented">অমুযো উপাসিকাযো পুঞ্ঞং কারাপেতি সদ্ধো</p>
<p class="unindented">অমুযা উপাসিকায ভিক্খু ভত্তং ভোজাপীযতে</p>
<p class="unindented">অমূহি উপাসিকাহি সঙ্ঘো ভত্তং ভোজাপিতো</p>
<p class="unindented">অমুযা উপাসিকায যো কোচি পন সুচরতি</p>
<p class="unindented">অমূহি উপাসিকাহি যে কেচি পন সুচরন্তি</p>
<p class="unindented">অমুস্সা উপাসিকায দানং দেতি সপ্পুরিসো</p>
<p class="unindented">অমূসং উপাসিকানং দানং দেন্তি সপ্পুরিসা</p>
<p class="unindented">অমুযা উপাসিকাযপি যো কোচি অপেতি</p>
<p class="unindented">অমূহি উপাসিকাহি যে কেচি পন অপেন্তি</p>
<p class="unindented">অমুস্সা উপাসিকায পুত্তাপি বহৰো হোন্তি</p>
<p class="unindented">অমূসানং উপাসিকানং পরিসাপি বহৰো</p>
<p class="unindented">অমুস্সং উপাসিকাযং যো কোচি পসীদতি</p>
<p class="unindented">অমূসু উপাসিকাসু পন যে কেচি পসীদন্তি।</p>
<p class="centered">ইতি তেৰীসতিমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">অদুং ধনৰং নিচ্চং বহুং পুঞ্ঞং পসৰতি</p>
<p class="unindented">অমূনি ধনৰন্তানি বহুং পুঞ্ঞং পসৰন্তি</p>
<p class="unindented">অদুং ধনৰন্তং পুঞ্ঞং কারাপেতি সদ্ধো</p>
<p class="unindented">অমূনি ধনৰন্তানি পুঞ্ঞং কারাপেতি সদ্ধো</p>
<p class="unindented">অমুনা <a name="V0.0031"></a> ধনৰন্তেন ভিক্খু ভত্তং ভোজাপীযতে</p>
<p class="unindented">অমূহি ধনৰন্তেহি ভিক্খু ভত্তং ভোজাপিতো</p>
<p class="unindented">অমুনা ধনৰন্তেন মহাজনোপি সুখীজাতো</p>
<p class="unindented">অমূহি ধনৰত্তেহি মহাজনোপি সুখীজাতো</p>
<p class="unindented">অমুনো ধনৰন্তস্স সুৰণ্ণছত্তং ধারযতে</p>
<p class="unindented">অমূসং ধনৰন্তানং উপতিট্ঠেয্য একচ্চো</p>
<p class="unindented">অমুস্মা ধনৰন্তম্হা লাভসক্কারং লভেয্য</p>
<p class="unindented">অমূহি ধনৰন্তেহি লাভসক্কারানি লভেয্যুং</p>
<p class="unindented">অমুনো ধনৰন্তস্স মহাপরিৰারো অত্থি</p>
<p class="unindented">অমূসানং ধনৰন্তানং মহাপরিৰারা ৰিজ্জন্তি</p>
<p class="unindented">অমুম্হি ধনৰন্তস্মিং যো কোচি পসীদতি</p>
<p class="unindented">অমূসু ধনৰন্তেসু যে কেচি পসীদন্তি।</p>
<p class="centered">ইতি চতুৰীসতিমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="gatha1">কোহি নাম বুধো লোকে ৰসং কোধস্স গচ্ছতি।</p>
<p class="gathalast">কে হিত্বা মানুসং দেহং দিব্বং যোগং উপচ্চগুং॥</p>
<p class="gatha1">কংসি ত্বং অস্সু উদ্দিস্স পব্বজিতো চ আৰুসো।</p>
<p class="gathalast">কেচি পুঞ্ঞানি কত্বান কিত্তকা তিদিৰং গতা॥</p>
<p class="gatha1">কেনাযং পকতো সত্তো কুৰং সত্তস্স কারকো।</p>
<p class="gathalast">কেহিদং পকতং বিম্বং ক্বন্নু বিব্বস্স কারকো॥</p>
<p class="gatha1">কেন তে তাদিসো ৰণ্ণো কেন তে ইধ মিজ্ঝতি।</p>
<p class="gathalast">কেহি মে পুঞ্ঞকম্মেহি মমং রক্খন্তি দেৰতা॥</p>
<p class="gatha1">কস্স চাভিরতো সত্তো সব্বদুক্খা পমুচ্চতি।</p>
<p class="gathalast">কেসং দিৰাচ রত্তোচ সদা পুঞ্ঞং পৰড্ঢতি॥</p>
<p class="gatha1">কস্মা নপরিদেৰেসি এৰরূপে মহব্ভযে।</p>
<p class="gathalast">কেহি নাম অরিযেহি পুথগেৰ জনো অযং॥</p>
<p class="gatha1">কস্স ত্বং ধম্মমঞ্ঞায ৰাচং ভসযি ঈদিসং।</p>
<p class="gathalast">কেসং তে ধম্মমঞ্ঞায অচ্ছিদুং ভৰভন্ধনং॥</p>
<p class="gatha1">কম্হি কালে তযা ৰীর পত্থিতা বোধিমুত্তমা।</p>
<p class="gathalast">কেসুদ্ধানেসু মুনিন্দ সাৰকো পরিতিব্বুতোতি॥</p>
<p class="centered">ইতি পঞ্চৰীসতিমো পাঠো।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="gatha1">কা চ সুফস্সযং দানং মঞ্চপীঠাদিকং অদা।</p>
<p class="gathalast">কাযো নানাৰিধং পুঞ্ঞং কত্বান তিদিৰং গতা॥</p>
<p class="gatha1">কং <a name="V0.0032"></a> ভাৰনঞ্চ ভাৰেতি কং সীলং পরিপালযী।</p>
<p class="gathalast">কা নাম দাসিযো কম্মে কারাপযতি সামিকো॥</p>
<p class="gatha1">কায উপাসিকাযস্সু ধম্মো চ সূযতে সদা।</p>
<p class="gathalast">কাহি চ সীলৰতীহি ধম্মো চ সূযতে সদা॥</p>
<p class="gatha1">কায ৰিজ্জায মে পুত্তো পাপুণাতি ইদং সুখং।</p>
<p class="gathalast">কাহি সিক্খাহি মে পুত্তা পাপুণন্তি ইদং সুখং॥</p>
<p class="gatha1">কস্সা উপাসিকাযস্সু দানং দদেয্য ধনৰা।</p>
<p class="gathalast">কাসং উপাসিকানঞ্চ দানং দদেয্য গুণৰা॥</p>
<p class="gatha1">কায গঙ্গায সব্বাচ পভৰন্তীতি কুন্নদী।</p>
<p class="gathalast">কাহি চ পন নদীহি পভৰন্তি মহানদী॥</p>
<p class="gatha1">কস্সা খো পন গঙ্গায মহোঘো হোতি সব্বদা।</p>
<p class="gathalast">কাসং খো পন কঞ্ঞানং আভরণা ভৰন্তি চ॥</p>
<p class="gatha1">কস্সং নদিং পন মচ্ছা নিচ্চং ৰিচরন্তি সদা।</p>
<p class="gathalast">কাসু গঙ্গাসু খো মচ্ছা নিচ্চং ৰিচরন্তি সদা॥</p>
<p class="centered">ইতি ছব্বীসতিমো পাঠো।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="gatha1">কিং তে জটাহি দুম্মেধ কিং তে অজিনসাটিযা।</p>
<p class="gathalast">কানি চিত্তানি জাযন্তি কথং জানেম তং মযং॥</p>
<p class="gatha1">কিং ত্বং অত্তৰসং দিস্বা মম দজ্জাসিমং ধনং।</p>
<p class="gathalast">কানি পুঞ্ঞানি কত্বান কিত্তকা তিদিৰং গতা॥</p>
<p class="gatha1">কেনস্সু নীযতি লোকো কেনস্সু পরিকস্সতি।</p>
<p class="gathalast">কেহি মে পুঞ্ঞকম্মস্স নান্তমেৰঞ্চ দিস্সতি॥</p>
<p class="gatha1">কেনাসি দুম্মনো তাত পুরিসং কন্নু যোচসি।</p>
<p class="gathalast">কেহি পুপ্ফেহি সক্কচ্চং সদ্ধো যজতি গোতমং॥</p>
<p class="gatha1">কস্স সো কযিরা মেত্তিং তমাহু চরিযং বুধা।</p>
<p class="gathalast">কেসং দানৰরং এতং দাতব্বঞ্চ সদাদরা॥</p>
<p class="gatha1">কস্মা চোরো অহু মে ত্বং ইতি রাজা অপুচ্ছিতং।</p>
<p class="gathalast">কেহি নামপি হেতূহি জাযন্তীতি ইমে জনা॥</p>
<p class="gatha1">কস্স তে ধম্মমঞ্ঞায অচ্ছিদুং ভৰভন্ধনং।</p>
<p class="gathalast">কেসং মজ্ঝগতো ভাতি চন্দোৰ নভমজ্ঝগো॥</p>
<p class="gatha1">কস্মিং মে সিৰযো কুদ্ধা নাহং পস্সামি দুক্কটং।</p>
<p class="gathalast">কেসু পুঞ্ঞেসু যোজেতি সখীনং সো সখাহিতোতি॥</p>
<p class="centered">ইতি <a name="V0.0033"></a> সত্তৰীসতিমো পাঠো।</p>
<p class="centered">ইতি পদমঞ্জরিযা সব্বনামানং।</p>
<p class="centered">চতুত্থো পরিচ্ছেদো।</p>
<p class="centered">অথ অলিঙ্গতুম্হাম্হসদ্দা ৰুচ্চন্তে।</p>
<p class="unindented">ত্বং পন পুরিসো পুঞ্ঞং করোহি</p>
<p class="unindented">তুম্হে পুরিসা পুঞ্ঞং করোথ</p>
<p class="unindented">তুৰং পন পুরিসং পুঞ্ঞং কারাপেতি</p>
<p class="unindented">তুম্হে পুরিসে পুঞ্ঞানি কারাপেতি</p>
<p class="unindented">তযা পুরিসেন ওদনো পচ্চতে</p>
<p class="unindented">তুম্হেহি পুরিসেহি ওদনা পচ্চন্তে</p>
<p class="unindented">তযা পুরিসেন একচ্চো জীৰতি</p>
<p class="unindented">তুম্হেহি পুরিসেহি একচ্চে জীৰন্তি</p>
<p class="unindented">তুয্হং পুরিসস্স ধনং দেতি ধনী</p>
<p class="unindented">তুম্হাকং পুরিসানং ধনং দেতি ধনী</p>
<p class="unindented">তযা পুরিসম্হা অপেতি যো কোচি</p>
<p class="unindented">তুম্হেহি পুরিসেহি অপেন্তি যে কেচি</p>
<p class="unindented">তুয্হং পুরিসস্স নাম গোত্তাদযো</p>
<p class="unindented">তুম্হাকং পুরিসানং পরিগ্গহো</p>
<p class="unindented">তযি পুরিসস্মিং কোচি পসীদতি</p>
<p class="unindented">তুম্হেসু পুরিসেসু কেচি পসীদন্তি।</p>
<p class="centered">ইতি পঠমো পাঠো।</p>
<p class="unindented">ত্বং ইত্থীপি ওদনং ভুত্বা গচ্ছাহি</p>
<p class="unindented">তুম্হে ইত্থিযো ওদনং ভুত্বা গচ্ছথ</p>
<p class="unindented">তুৰং ইত্থিং পুঞ্ঞং কারযতি পুরিসো</p>
<p class="unindented">তুম্হে ইত্থিযো পুঞ্ঞানি কারেন্তি পুরিসা</p>
<p class="unindented">তযা ইত্থিযাপি ধঞ্ঞং ভজ্জতে</p>
<p class="unindented">তুম্হেহি ইত্থীহি ধঞ্ঞানি ভজ্জন্তে</p>
<p class="unindented">তযা ইত্থিযা দুক্খং পাপুণাতি কোচি</p>
<p class="unindented">তুম্হেহি ইত্থীহি সুখং পাপুণাতি সামি</p>
<p class="unindented">তুয্হং ইত্থিযা আভরণং দেতি সামি</p>
<p class="unindented">তুম্হাকং ইত্থীনং আভরণং দেতি সামি</p>
<p class="unindented">তযা ইত্থিযা অপেতি যো কোচি</p>
<p class="unindented">তুম্হেহি ইত্থীহি অপেন্তি যে কেচি</p>
<p class="unindented">তুয্হং ইত্থিযা পুত্তাপি বহৰো হোন্তি</p>
<p class="unindented">তুম্হাকং ইত্থীনং ৰত্থাভরণানি হোন্তি</p>
<p class="unindented">ত্বযি ইত্থিযা পন মনং পতিট্ঠিতং</p>
<p class="unindented">তুম্হেসু ইত্থীসু পন মনানি পতিট্ঠিতানি।</p>
<p class="centered">ইতি <a name="V0.0034"></a> দুতিযো পাঠো।</p>
<p class="unindented">ত্বং চিত্তং পন আরম্মণং চিন্তেসি</p>
<p class="unindented">তুম্হে চিত্তানি আরম্মণং চিন্তেথ</p>
<p class="unindented">ত্বং চিত্তং সঞ্ঞমেস্সন্তি যে কেচি</p>
<p class="unindented">তুম্হে চিত্তানি সঞ্ঞমেস্সন্তি যে কেচি</p>
<p class="unindented">তযা চিত্তেন কম্মফলং অনুভুত্তং</p>
<p class="unindented">তুম্হেহি চিত্তেহি কম্মফলং অনুভুত্তং</p>
<p class="unindented">তযা চিত্তেন বুদ্ধং সরতি সপ্পুরিসো</p>
<p class="unindented">তুম্হেহি চিত্তেহি বুদ্ধং সরন্তি সপ্পুরিসা</p>
<p class="unindented">তুয্হং চিত্তস্স ওৰাদং দেতি কোচি</p>
<p class="unindented">তুম্হাকং চিত্তানং ওৰাদং দেন্তি কেচি</p>
<p class="unindented">তযা চিত্তম্হা খো পন ভযং উপ্পজ্জতি</p>
<p class="unindented">তুম্হেহি চিত্তেহি পন ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">তুয্হং চিত্তস্স পরিৰিতক্কো উদপাদি</p>
<p class="unindented">তুম্হাকং চিত্তানং পরিৰিতক্কো উদপাদি</p>
<p class="unindented">তযি চিত্তে খো পন কুসলচিত্তং পতিঠিতং</p>
<p class="unindented">তুম্হেসু চিত্তেসু কুসলচিত্তানি পতিট্ঠিতানি।</p>
<p class="centered">ইতি ততিযো পাঠো।</p>
<p class="unindented">অহং পুরিসোপি পুঞ্ঞং করোমি</p>
<p class="unindented">মযং পুরিসা পন পুঞ্ঞং করোম</p>
<p class="unindented">মমং পুরিসং পুঞ্ঞং কারাপেতি</p>
<p class="unindented">অম্হে পুরিসে পুঞ্ঞানি কারাপেতি</p>
<p class="unindented">মযা পুরিসেন কম্মফলং অনুভুত্তং</p>
<p class="unindented">অম্হেহি পুরিসেহি কম্মফলং অনুভুত্তং</p>
<p class="unindented">মযা পুরিসেন একচ্চো সুচরতি</p>
<p class="unindented">অম্হেহি পুরিসেহি একচ্চে সুচরন্তি</p>
<p class="unindented">অম্হং পুরিসস্স ধনং দদাতি ধনৰা</p>
<p class="unindented">অম্হাকং পুরিসানং ফলং দদাতি ফলৰা</p>
<p class="unindented">মযা পুরিসস্মা অপেতি একচ্চো</p>
<p class="unindented">অম্হেহি পুরিসেহি ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">অম্হং পুরিসস্স নাম গোত্তাদি</p>
<p class="unindented">অম্হাকং পুরিসানং পরিগ্গহো হোতি</p>
<p class="unindented">মযি পুরিসস্মিং পসীদতি যো কোচি</p>
<p class="unindented">অম্হেসু পুরিসেসু একচ্চো সূরতমো।</p>
<p class="centered">ইতি চতুত্থো পাঠো।</p>
<p class="unindented">অহং কঞ্ঞা পন পুঞ্ঞং করোমি</p>
<p class="unindented">মযং কঞ্ঞাযো পুঞ্ঞানি করোম</p>
<p class="unindented">মমং কঞ্ঞং পুঞ্ঞং কারাপেতি</p>
<p class="unindented">অম্হে <a name="V0.0035"></a> কঞ্ঞাযো পুঞ্ঞং কারাপেতি</p>
<p class="unindented">মযা কঞ্ঞায ওদনো পচ্চতে</p>
<p class="unindented">অম্হেহি কঞ্ঞাহি ওদনো পচ্চতে</p>
<p class="unindented">মযা কঞ্ঞায সুখদুক্খা পাপুণাতি</p>
<p class="unindented">অম্হেহি কঞ্ঞাহি সুখদুক্খং পাপুণাতি</p>
<p class="unindented">অম্হং কঞ্ঞায আভরণং দেতি</p>
<p class="unindented">অম্হাকং কঞ্ঞানং আভরণং দেতি</p>
<p class="unindented">মযা কঞ্ঞায অযং কঞ্ঞা হীণা</p>
<p class="unindented">অম্হেহি কঞ্ঞাহি অযং কঞ্ঞা অধিকা</p>
<p class="unindented">অম্হং কঞ্ঞায ৰত্থাভরণানি হোন্তি</p>
<p class="unindented">অম্হাকং কঞ্ঞানং পরিগ্গহো হোতি</p>
<p class="unindented">মযি কঞ্ঞাযং মে মনং নপতিট্ঠিতং</p>
<p class="unindented">অম্হেসু কঞ্ঞাসু মে মনং পতিট্ঠিতং।</p>
<p class="centered">ইতি পঞ্চমো পাঠো।</p>
<p class="unindented">অহং চিত্তং পন আরম্মণং ৰিজানাহি</p>
<p class="unindented">মযং চিত্তানি আরম্মণং ৰিজানাথ</p>
<p class="unindented">মমং চিত্তং সঞ্ঞমেস্সন্তি একচ্চে</p>
<p class="unindented">অম্হে চিত্তানি সঞ্ঞমেস্সন্তি কেচি</p>
<p class="unindented">মযা চিত্তেন কম্মফলং অনুভুত্তং</p>
<p class="unindented">অম্হেহি চিত্তেহি কম্মফলং অনুভুত্তং</p>
<p class="unindented">মযা চিত্তেন বুদ্ধং সরতি সপ্পুরিসো</p>
<p class="unindented">অম্হেহি চিত্তেহি বুদ্ধং সরতি সদ্ধো</p>
<p class="unindented">মমং চিত্তস্স ওৰাদং দেতি কোচি</p>
<p class="unindented">অম্হাকং চিত্তানং ওৰাদং দেন্তি কেচি</p>
<p class="unindented">মযা চিত্তস্মা পন ভযং উপ্পজ্জতি</p>
<p class="unindented">অম্হেহি চিত্তেহি ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">মমং চিত্তস্স পরিৰিতক্কো উদপাদি</p>
<p class="unindented">অম্হাকং চিত্তানং পরিৰিতক্কো হোতি</p>
<p class="unindented">মযি চিত্তে পন কুসলচিত্তং পতিট্ঠিতং</p>
<p class="unindented">অম্হেসু চিত্তেসু কুসলচিত্তানি পতিট্ঠিতানি।</p>
<p class="centered">ইতি ছট্ঠো পাঠো।</p>
<p class="unindented">গামং ৰো পন গচ্ছেয্যাথ</p>
<p class="unindented">গামং নো পন গচ্ছেয্যাম</p>
<p class="unindented">পহায ৰো ভিক্খৰে গমিস্সামি</p>
<p class="unindented">মা নো অজ্জ পন ৰিকন্তিসু</p>
<p class="unindented">কতমেৰ তে পন তং কম্মং</p>
<p class="unindented">কতমেৰ <a name="V0.0036"></a> মে পন তং কম্মং</p>
<p class="unindented">কতমেৰ ৰো পন কুসলকম্মং</p>
<p class="unindented">কতমেৰ নো পন কুসলকম্মং</p>
<p class="unindented">দদামি তে পন গামৰরানি পঞ্চ</p>
<p class="unindented">দদাহি মে গামৰরং ত্বম্পি</p>
<p class="unindented">ধম্মং ৰো ভিক্খৰে দেসিস্সামি</p>
<p class="unindented">সংৰিভাজেথ নো রজ্জেন</p>
<p class="unindented">মনুস্সস্সেৰ তে সীসং পন</p>
<p class="unindented">পহূতং মে পন ধনং সক্ক</p>
<p class="unindented">তুট্ঠোস্মিযা ৰো পন পকতিযা</p>
<p class="unindented">সত্থা নো ভগৰা অনুপ্পত্তো।</p>
<p class="gatha1">ৰো নো তে মেতি রূপানি পদানি পদতো যতো।</p>
<p class="gathalast">ততো নামিকপন্তীসু নতূ ৰুত্তানি তানি মে॥</p>
<p class="gatha1">পচ্চত্তে উপযোগে চ করণে সম্পদানিযে।</p>
<p class="gathalast">সামিস্স ৰচনে চেৰ ৰো নো সদ্দো পৰত্ততি॥</p>
<p class="gatha1">করণে সম্পদানে চ সামিঅত্থে চ আগতো।</p>
<p class="gathalast">তে মে সদ্দোতি ৰিঞ্ঞেয্যো ৰিঞ্ঞুনা নযদস্সিনাতি॥</p>
<p class="centered">ইতি সত্তমো পাঠো।</p>
<p class="centered">ইতি পদমঞ্জরিযা অলিঙ্গসব্বনামানং।</p>
<p class="centered">পঞ্চমো পরিচ্ছেদো।</p>
<p class="unindented">ইমানি পুল্লিঙ্গরূপানি ৰুচ্চন্তে</p>
<p class="unindented">দ্বে মহারাজানো রজ্জং কারেন্তি</p>
<p class="unindented">দ্বেপি মহারাজানো উপসঙ্কমতি</p>
<p class="unindented">দ্বীহি মহারাজেহি সঙ্গামো কতো</p>
<p class="unindented">দ্বীহি মহারাজেহি রট্ঠৰাসিনো জীৰন্তি</p>
<p class="unindented">দ্বিন্নং মহারাজানং পন্নাকারং দেতি</p>
<p class="unindented">দ্বীহি মহারাজেহি ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">দ্বিন্নং মহারাজানং পরিগ্গহো হোতি</p>
<p class="unindented">দ্বীসু মহারাজেসু মনানি পতিট্ঠিতানি।</p>
<p class="centered">ইমানি ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">দ্বে কঞ্ঞাযো পুঞ্ঞানি করোন্তি</p>
<p class="unindented">দ্বে কঞ্ঞাযো পুঞ্ঞানি কারাপেতি</p>
<p class="unindented">দ্বীহি কঞ্ঞাহি পুঞ্ঞানি কতানি</p>
<p class="unindented">দ্বীহি কঞ্ঞাহি সুখদুক্খং পাপুণাতি</p>
<p class="unindented">দ্বিন্নং কঞ্ঞানং আভরণানি দেতি</p>
<p class="unindented">দ্বীহি <a name="V0.0037"></a> কঞ্ঞাহি অযং কঞ্ঞা অধিকা</p>
<p class="unindented">দ্বিন্নং কঞ্ঞানং ৰত্থাভরণং হোতি</p>
<p class="unindented">দ্বীসু কঞ্ঞাসু মনানি পতিট্ঠিতানি</p>
<p class="centered">ইমানি নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">দ্বে কুলানি দানাদিকুসলং করোন্তি</p>
<p class="unindented">দ্বে কুলানি দানাদিকুসলং কারাপেতি</p>
<p class="unindented">দ্বীহি কুলেহি সঙ্ঘো ভত্তং ভোজাপিতো</p>
<p class="unindented">দ্বীহি কুলেহি সুখং পাপুণাতি সঙ্ঘো</p>
<p class="unindented">দ্বিন্নং কুলানং সক্কারং করোন্তি কেচি</p>
<p class="unindented">দ্বীহি কুলেহি অপেতি একচ্চো পুগ্গলো</p>
<p class="unindented">দ্বিন্নং কুলানং নাম গোত্তাদযো</p>
<p class="unindented">দ্বীসু কুলেসু মে চিত্তং পতিট্ঠিতং।</p>
<p class="centered">ইতি পঠমো পাঠো।</p>
<p class="centered">ইমানি পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">তযো পুরিসা পন ৰিহারং করোন্তি</p>
<p class="unindented">তযো পুরিসে উপগচ্ছতি একচ্চো</p>
<p class="unindented">তীহি পুরিসেহি ৰিহারো কারাপিতো</p>
<p class="unindented">তীহি পুরিসেহি জীৰন্তি যে কেচি</p>
<p class="unindented">তিণ্ণন্নং পুরিসানং ধনং দেতি ধনৰা</p>
<p class="unindented">তীহি পুরিসেহি ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">তিণ্ণন্নং পুরিসানং পরিগ্গহো হোতি</p>
<p class="unindented">তীসু পুরিসেসু পসীদতি যো কোচি।</p>
<p class="centered">ইমানি ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">তিস্সো ইত্থিযো পুঞ্ঞানি করোন্তি</p>
<p class="unindented">তিস্সো ইত্থিযো পুঞ্ঞানি কারাপেতি</p>
<p class="unindented">তীহি ইত্থীহি সঙ্ঘো ভত্তং ভোজাপিতো</p>
<p class="unindented">তীহি ইত্থীহি জীৰন্তি একচ্চো পুরিসো</p>
<p class="unindented">তিস্সন্নং ইত্থীনং আভরণানি দেতি</p>
<p class="unindented">তীহি ইত্থীহি অপেতি একচ্চো পুরিসো</p>
<p class="unindented">তিস্সন্নং ইত্থীনং আভরণানি হোন্তি</p>
<p class="unindented">তীসু ইত্থীসু পসীদতি একচ্চো পুরিসো।</p>
<p class="centered">ইমানি নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">তীনি কুলানি পুঞ্ঞানি করোন্তি</p>
<p class="unindented">তীনি কুলানি পুঞ্ঞানি কারাপেতি</p>
<p class="unindented">তীহি কুলেহি পুঞ্ঞানি করিয্যন্তে</p>
<p class="unindented">তীহি কুলেহি জীৰন্তি যে কেচি</p>
<p class="unindented">তিণ্ণন্নং <a name="V0.0038"></a> কুলানং ধনং দেতি ধনৰা</p>
<p class="unindented">তীহি কুলেহি ভযানি ন উপ্পজ্জন্তি</p>
<p class="unindented">তিণ্ণন্নং কুলানং মহাভোগো হোতি</p>
<p class="unindented">তীসু কুলেসু পসীদতি একচ্চো পুরিসো।</p>
<p class="centered">ইতি দুতিযো পাঠো।</p>
<p class="centered">ইমানি পুল্লিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">চত্তারো মহারাজা রজ্জং করোন্তি</p>
<p class="unindented">চত্তারো মহারাজে উপগচ্ছতি একচ্চো</p>
<p class="unindented">চতূহি মহারাজেহি পুঞ্ঞানি করিয্যন্তে</p>
<p class="unindented">চতূহি মহারাজেহি জীৰন্তি মহাজনা</p>
<p class="unindented">চতুন্নং মহারাজানং পন্নাকারং দেন্তি</p>
<p class="unindented">চতূহি মহারাজেহি ভযানি উপ্পজ্জন্তি</p>
<p class="unindented">চতুন্নং মহারাজানং আভরণং হোতি</p>
<p class="unindented">চতূসু মহারাজেসু পসীদতি মহাজনো।</p>
<p class="centered">ইমানি ইত্থিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">চতস্সো কঞ্ঞাযো পুঞ্ঞানি করোন্তি</p>
<p class="unindented">চতস্সো কঞ্ঞাযো পুঞ্ঞানি কারাপেতি</p>
<p class="unindented">চতূহি কঞ্ঞাহি সঙ্ঘো ভত্তং ভোজাপিতো</p>
<p class="unindented">চতূহি কঞ্ঞাহি ৰধং পাপুণন্তি পুরিসা</p>
<p class="unindented">চতস্সন্নং কঞ্ঞানং আভরণানি দেন্তি</p>
<p class="unindented">চতূহি কঞ্ঞাহি অযং কঞ্ঞা অধিকা</p>
<p class="unindented">চতস্সন্নং কঞ্ঞানং আভরণং হোতি</p>
<p class="unindented">চতূসু কঞ্ঞাসু পসীদতি একচ্চো পুরিসো।</p>
<p class="centered">ইমানি নপুংসকলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">চত্তারি কুলানি বহুং পুঞ্ঞং করোন্তি</p>
<p class="unindented">চত্তারি কুলানি উপগচ্ছন্তি একচ্চে</p>
<p class="unindented">চতূহি কুলেহি ৰিহারো কারাপীযতে</p>
<p class="unindented">চতূহি কুলেহি জীৰন্তি একচ্চে পুরিসা</p>
<p class="unindented">চতুন্নং কুলানং সক্কারং করোন্তি</p>
<p class="unindented">চতূহি কুলেহি অপেন্তি একচ্চে</p>
<p class="unindented">চতুন্নং কুলানং নাম গোত্তাদযো</p>
<p class="unindented">চতুসু কুলেসু পসীদতি মহাজনো।</p>
<p class="centered">ইতি ততিযো পাঠো।</p>
<p class="unindented">পঞ্চ মহাভূতা তিট্ঠন্তি</p>
<p class="unindented">পঞ্চ মহাভূতে পস্সতি</p>
<p class="unindented">পঞ্চহি <a name="V0.0039"></a> মহাভূতেহি কতানি</p>
<p class="unindented">পঞ্চহি মহাভূতেহি সুচরতি</p>
<p class="unindented">পঞ্চন্নং মহাভূতানং দীযতে</p>
<p class="unindented">পঞ্চহি মহাভূতেহি অপেতি</p>
<p class="unindented">পঞ্চন্নং মহাভূতানং সন্তকং</p>
<p class="unindented">পঞ্চসু মহাভূতেসু পতিট্ঠিতং।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">পঞ্চ-মহাভূতা পন তিট্ঠন্তি</p>
<p class="unindented">পঞ্চ-অভিভৰিতারো তিট্ঠন্তি</p>
<p class="unindented">পঞ্চ-পুরিসা পন তিট্ঠন্তি</p>
<p class="unindented">পঞ্চ-ভূমিযো পন হোন্তি</p>
<p class="unindented">পঞ্চ-কঞ্ঞাযো পন তিট্ঠন্তি</p>
<p class="unindented">পঞ্চ-মহাভূতানি তিট্ঠন্তি</p>
<p class="unindented">পঞ্চ-চিত্তানি উপ্পজ্জন্তি</p>
<p class="unindented">এৰং সব্বত্থ যোজেতব্বং।</p>
<p class="centered">ইতি চতুত্থো পাঠো।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">ছ মহাভূতা পন তিট্ঠন্তি</p>
<p class="unindented">ছ অভিভৰিতারো পস্সতি</p>
<p class="unindented">ছহি পুরিসেহি কম্মং কতং</p>
<p class="unindented">ছন্নং ভূমীনং রুচ্চতি কোচি</p>
<p class="unindented">ছহি কঞ্ঞাহি অপেতি একচ্চো</p>
<p class="unindented">ছন্নং ভূতানং সন্তকং হোতি</p>
<p class="unindented">ছসু পন চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">সত্ত মহাভূতা পন তিট্ঠন্তি</p>
<p class="unindented">সত্ত অভিভৰিতারো পস্সতি</p>
<p class="unindented">সত্তহি পুরিসেহি কম্মং কতং</p>
<p class="unindented">সত্তন্নং ভূমীনং রুচ্চতি কোচি</p>
<p class="unindented">সত্তহি কঞ্ঞাহি অপেতি একচ্চো</p>
<p class="unindented">সত্তন্নং ভূতানং সন্তকং হোতি</p>
<p class="unindented">সত্তসু পন চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি <a name="V0.0040"></a> পঞ্চমো পাঠো।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">অট্ঠ মহাভূতা পন তিট্ঠন্তি</p>
<p class="unindented">অট্ঠ অভিভৰিতারো পস্সতি</p>
<p class="unindented">অট্ঠহিপুরিসেহি কম্মং কতং</p>
<p class="unindented">অট্ঠন্নং ভূমীনং রুচ্চতি কোচি</p>
<p class="unindented">অট্ঠহি কঞ্ঞাহি অপেতি কোচি</p>
<p class="unindented">অট্ঠন্নংভূতানং সন্তকং হোতি</p>
<p class="unindented">অট্ঠসু পন চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">নৰ মহাভূতা পন তিট্ঠন্তি</p>
<p class="unindented">নৰ অভিভৰিতারো পস্সতি</p>
<p class="unindented">নৰহি পুরিসেহি কম্মং কতং</p>
<p class="unindented">নৰন্নং ভূমীনং রুচ্চতি কোচি</p>
<p class="unindented">নৰহি কঞ্ঞাহি অপেতি কোচি</p>
<p class="unindented">নৰন্নং ভূতানং সন্তকং হোতি</p>
<p class="unindented">নৰসু পন চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি ছট্ঠো পাঠো।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">দস মহাভূতা পন তিট্ঠন্তি</p>
<p class="unindented">দস অভিভৰিতারো পস্সতি</p>
<p class="unindented">দসহি পুরিসেহি কম্মং কতং</p>
<p class="unindented">দসন্নং ভূতানং রুচ্চতি কোচি</p>
<p class="unindented">দসহি কঞ্ঞাহি অপেতি কোচি</p>
<p class="unindented">দসন্নং ভূতানং সন্তকং হোতি</p>
<p class="unindented">দসসু পন চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">একাদস-মহাভূতা তিট্ঠন্তি</p>
<p class="unindented">দ্বাদস-অভিভৰিতারো তিট্ঠন্তি</p>
<p class="unindented">তেরস-পুরিসা পন তিট্ঠন্তি</p>
<p class="unindented">চুদ্দস-ভূমিযো পন হোন্তি</p>
<p class="unindented">পঞ্চদস-কঞ্ঞাযো পন তিট্ঠন্তি</p>
<p class="unindented">সোলস-ভূতানি পন তিট্ঠন্তি</p>
<p class="unindented">সত্তরস-চিত্তানি উপ্পজ্জন্তি।</p>
<p class="centered">তিলিঙ্গরূপানি <a name="V0.0041"></a> ৰুচ্চন্তে।</p>
<p class="unindented">অট্ঠারস মহাভূতা পন তিট্ঠন্তি</p>
<p class="unindented">অট্ঠারস অভিভৰিতারো পস্সতি</p>
<p class="unindented">অট্ঠারসহি পুরিসেহি কম্মং কতং</p>
<p class="unindented">অট্ঠারসন্নং ভূমীনং রুচ্চতি</p>
<p class="unindented">অট্ঠারসহি কঞ্ঞাহি অপেতি কোচি</p>
<p class="unindented">অট্ঠারসন্নং ভূতানং সন্তকং</p>
<p class="unindented">অট্ঠারসসু চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি সত্তমো পাঠো।</p>
<p class="centered">ইতি পদমঞ্জরিযা বহুৰচনসঙ্খ্যানামানং ছট্ঠো পরিচ্ছেদো।</p>
<p class="centered">তিলিঙ্গরূপানি ৰুচ্চন্তে।</p>
<p class="unindented">একূনৰীসতি একূনৰীসং ইচ্চাদিপি</p>
<p class="unindented">একূনৰীসায একূনৰীসাযং</p>
<p class="unindented">একূনৰীসতি ভিক্খূপি তিট্ঠন্তি</p>
<p class="unindented">একূনৰীসং ভিক্খূপি পস্সতি</p>
<p class="unindented">একূনৰীসায ভিক্খূহি ধম্মো দেসিতো</p>
<p class="unindented">একূনৰীসায কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">একূনৰীসায চিত্তেহি কম্মং কতং</p>
<p class="unindented">একূনৰীসায ভিক্খূনং চীৰরং দেতি</p>
<p class="unindented">একূনৰীসায কঞ্ঞানং ধনং দেতি</p>
<p class="unindented">একূনৰীসায চিত্তানং পন রুচ্চতি</p>
<p class="unindented">একূনৰীসায ভিক্খূহি অপেতি কোচি</p>
<p class="unindented">একূনৰীসায কঞ্ঞাহি অপেতি কোচি</p>
<p class="unindented">একূনৰীসায চিত্তেহি অপেতি কোচি</p>
<p class="unindented">একূনৰীসায ভিক্খূনং সন্তকং</p>
<p class="unindented">একূনৰীসায কঞ্ঞানং সন্তকং</p>
<p class="unindented">একূনৰীসায চিত্তানং সন্তকং</p>
<p class="unindented">একূনৰীসায ভিক্খূসু পতিট্ঠিতং</p>
<p class="unindented">একূনৰীসায কঞ্ঞাসু পতিট্ঠিতং</p>
<p class="unindented">একূনৰীসাযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি <a name="V0.0042"></a> পঠমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">একূনৰীসতি ভিক্খূপি তিট্ঠন্তি</p>
<p class="unindented">একূনৰীসতিং ভিক্খূপি পস্সতি</p>
<p class="unindented">একূনৰীসতিযা ভিক্খূহি দেসিতো</p>
<p class="unindented">একূনৰীসতিযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">একূনৰীসতি কঞ্ঞাযো তিট্ঠন্তি</p>
<p class="unindented">একূনৰীসতিং কঞ্ঞাযো পস্সতি</p>
<p class="unindented">একূনৰীসতিযা কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">একূনৰীসতিযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">একূনৰীসতি চিত্তানি উপ্পজ্জন্তি</p>
<p class="unindented">একূনৰীসতিং চিত্তানি পস্সতি</p>
<p class="unindented">একূনৰীসতিযা চিত্তেহি কম্মং কতং</p>
<p class="unindented">একূনৰীসতিযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি দুতিযো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">ৰীসতি ভিক্খৰো তিট্ঠন্তি</p>
<p class="unindented">ৰীসতিং ভিক্খৰো পস্সতি</p>
<p class="unindented">ৰীসতিযা ভিক্খূহি দেসিতো</p>
<p class="unindented">ৰীসতিযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">ৰীসতি কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">ৰিসতিং কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">ৰীসতিযা কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">ৰীসতিযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">ৰীসতি চিত্তানি উপ্পজ্জন্তি</p>
<p class="unindented">ৰীসতিং চিত্তানিপি পস্সতি</p>
<p class="unindented">ৰীসতিযা চিত্তেহি কম্মং কতং</p>
<p class="unindented">ৰীসতিযং চিত্তেসু পতিট্ঠিতং</p>
<p class="unindented">ৰীসং ৰীসং ৰীসায ৰীসাযং</p>
<p class="unindented">তথা একৰীস দ্বাৰীস বাৰীস</p>
<p class="unindented">তেৰীস চতুৰীস-ইচ্চাদিপি।</p>
<p class="centered">ইতি <a name="V0.0043"></a> ততিযো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">তিংস ভিক্খৰো তিট্ঠন্তি</p>
<p class="unindented">তিংস ভিক্খৰো পস্সতি</p>
<p class="unindented">তিংসায ভিক্খূহি দেসিতো</p>
<p class="unindented">তিংসাযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">তিংস কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">তিংস কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">তিংসায কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">তিংসাযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">তিংস চিত্তানি উপ্পজ্জন্তি</p>
<p class="unindented">তিংস চিত্তানিপি পস্সতি</p>
<p class="unindented">তিংসায চিত্তেহি কম্মং কতং</p>
<p class="unindented">তিংসাযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি চতুত্থো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">চত্তালীস ভিক্খৰো তিট্ঠন্তি</p>
<p class="unindented">চত্তালীসং ভিক্খৰো পস্সতি</p>
<p class="unindented">চত্তালীসায ভিক্খূহি দেসিতো</p>
<p class="unindented">চত্তালীসাযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">চত্তালীস কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">চত্তালীসং কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">চত্তালীসায কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">চত্তালীসাযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">চত্তালীস চিত্তানিপি উপ্পজ্জন্তি</p>
<p class="unindented">চত্তালীসং চিত্তানিপি পস্সতি</p>
<p class="unindented">চত্তালীসায চিত্তেহি কম্মং কতং</p>
<p class="unindented">চত্তালীসাযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="unindented">চত্তারীস ইচ্চাদিপি।</p>
<p class="centered">ইতি <a name="V0.0044"></a> পঞ্চমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">পঞ্ঞায ভিক্খৰো তিট্ঠন্তি</p>
<p class="unindented">পঞ্ঞাযং ভিক্খৰো পস্সতি</p>
<p class="unindented">পঞ্ঞাসায ভিক্খূহি দেসিতো</p>
<p class="unindented">পঞ্ঞাসাযং ভিক্খূসু ৰতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">পঞ্ঞায কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">পঞ্ঞাসং কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">পঞ্ঞাসায কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">পঞ্ঞাসাযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">পঞ্ঞাস চিত্তানিপি উপ্পজ্জন্তি</p>
<p class="unindented">পঞ্ঞাসং চিত্তানিপি পস্সতি।</p>
<p class="unindented">পঞ্ঞাসায চিত্তেহি কম্মং কতং</p>
<p class="unindented">পঞ্ঞাসাযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="unindented">তথা পণ্ণাস পণ্ণাসং</p>
<p class="unindented">পণ্ণাসায পণ্ণাসাযং।</p>
<p class="centered">ইতি ছট্ঠো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">সট্ঠি ভিক্খৰোপি তিট্ঠন্তি</p>
<p class="unindented">সট্ঠিং ভিক্খৰোপি পস্সতি</p>
<p class="unindented">সট্ঠিযা ভিক্খূহি দেসিতো</p>
<p class="unindented">সট্ঠিযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">সট্ঠি কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">সট্ঠিং কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">সট্ঠিযা কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">সট্ঠিযং কঞ্ঞাসু পতিট্ঠিতং</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">সট্ঠি চিত্তানিপি উপ্পজ্জন্তি</p>
<p class="unindented">সট্ঠিং চিত্তানিপি পস্সতি</p>
<p class="unindented">সট্ঠিযা চিত্তেহি কম্মং কতং</p>
<p class="unindented">সট্ঠিযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি <a name="V0.0045"></a> সত্তমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">সত্ততি ভিক্খৰোপি তিট্ঠন্তি</p>
<p class="unindented">সত্ততিং ভিক্খৰোপি পস্সতি</p>
<p class="unindented">সত্ততিযা ভিক্খূহি দেসিতো</p>
<p class="unindented">সত্ততিযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">সত্ততি কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">সত্ততিং কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">সত্ততিযা কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">সত্ততিযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">সত্ততি চিত্তানিপি উপ্পজ্জন্তি</p>
<p class="unindented">সত্ততিং চিত্তানিপি পস্সতি</p>
<p class="unindented">সত্ততিযা চিত্তেহি কম্মং কতং</p>
<p class="unindented">সত্ততিযং চিত্তেসু পতিট্ঠিতং</p>
<p class="unindented">সত্তরি ইচ্চাদিপি।</p>
<p class="centered">ইতি অট্ঠমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">অসীতি ভিক্খৰোপি তিট্ঠন্তি</p>
<p class="unindented">অসীতিং ভিক্খৰোপি পস্সতি</p>
<p class="unindented">অসীতিযা ভিক্খূহি দেসিতো</p>
<p class="unindented">অসীতিযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি।</p>
<p class="unindented">অসীতি কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">অসীতিং কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">অসীতিযা কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">অসীতিযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">অসীতি চিত্তানিপি উপ্পজ্জন্তি</p>
<p class="unindented">অসীতিং চিত্তানিপি পস্সতি</p>
<p class="unindented">অসিতিযা চিত্তেহি কম্মং কতং</p>
<p class="unindented">অসীতিযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">ইতি নৰমো পাঠো।</p>
<p class="centered">পুল্লিঙ্গরূপানি।</p>
<p class="unindented">নৰুতি ভিক্খৰোপি তিট্ঠন্তি</p>
<p class="unindented">নৰুতিং ভিক্খৰোপি পস্সতি</p>
<p class="unindented">নৰুতিযা ভিক্খূহি দেসিতো</p>
<p class="unindented">নৰুতিযং ভিক্খূসু পতিট্ঠিতং।</p>
<p class="centered">ইত্থিলিঙ্গরূপানি <a name="V0.0046"></a></p>
<p class="unindented">নৰুতি কঞ্ঞাযোপি তিট্ঠন্তি</p>
<p class="unindented">নৰুতিং কঞ্ঞাযোপি পস্সতি</p>
<p class="unindented">নৰুতিযা কঞ্ঞাহি কম্মং কতং</p>
<p class="unindented">নৰুতিযং কঞ্ঞাসু পতিট্ঠিতং।</p>
<p class="centered">নপুংসকলিঙ্গরূপানি।</p>
<p class="unindented">নৰুতি চিত্তানিপি উপ্পজ্জন্তি</p>
<p class="unindented">নৰুতিং চিত্তানিপি পস্সতি</p>
<p class="unindented">নৰুতিযা চিত্তেহি কম্মং কতং</p>
<p class="unindented">নৰুতিযং চিত্তেসু পতিট্ঠিতং।</p>
<p class="centered">তথা একনৰুতি ইচ্চাদিপি।</p>
<p class="centered">ইতি দসমো পাঠো।</p>
<p class="unindented">সতং ভিক্খৰো পন তিট্ঠন্তি</p>
<p class="unindented">সতানি ভিক্খৰো পন তিট্ঠন্তি</p>
<p class="unindented">সতং ভিক্খৰো পন পস্সতি</p>
<p class="unindented">সতানি ভিক্খৰো পন পস্সতি</p>
<p class="unindented">সতেন ভিক্খূহি ধম্মো দেসিতো</p>
<p class="unindented">সতেহি ভিক্খূহি ধম্মা দেসিতা</p>
<p class="unindented">সতস্স ভিক্খূনং দানং দদেয্য</p>
<p class="unindented">সতানং ভিক্খূনং দানং দদেয্যুং</p>
<p class="unindented">সতস্মা ভিক্খূহি অপেতি কোচি</p>
<p class="unindented">সতেহি ভিক্খূহি অপেন্তি কেচি</p>
<p class="unindented">সতস্স ভিক্খূনং পত্তচীৰরানি</p>
<p class="unindented">সতানং ভিক্খুনং পত্তচীৰরানি</p>
<p class="unindented">সতস্মিং ভিক্খূসু মনং পতিট্ঠিতং</p>
<p class="unindented">সতেসু ভিক্খূসু মনং পতিট্ঠিতং।</p>
<p class="centered">এৰং সহস্সং সহস্সানীতি।</p>
<p class="unindented">যোজেতব্বং দসসহস্সং</p>
<p class="unindented">সতসহস্সং দসসতসহস্সন্তি</p>
<p class="unindented">এত্থাপি এসেৰনযো</p>
<p class="unindented">অযং পনেত্থ নযো</p>
<p class="unindented">সতং খো ভিক্খূ হোন্তি</p>
<p class="unindented">সতং খো ইত্থিযো হোন্তি</p>
<p class="unindented">সতং খো পিযাতি হোন্তি</p>
<p class="unindented">সহস্সাদিসুপি এসেৰ নযো।</p>
<p class="centered">ইতি <a name="V0.0047"></a> একাদসমো পাঠো।</p>
<p class="unindented">দসস্স গণনস্স দসগুণিতং কত্বা সতং হোতি।</p>
<p class="unindented">সতস্স দসগুণিতং কত্বা সহস্সং হোতি।</p>
<p class="unindented">দসসহস্সস্স দসগুণিতং কত্বা সতসহস্সং হোতি।</p>
<p class="unindented">তং লক্খন্তি ৰুচ্চতি, সতসহস্সস্স দসগুণিতং কত্বা দসসতসহস্সং হোতি।</p>
<p class="unindented">দসসতসহস্সস্স দসগুণিতং কত্বা কোটি হোতি।</p>
<p class="unindented">সতসহস্সানং সতং কোটি নামাতি অত্থো।</p>
<p class="unindented">কোটিসতসহস্সানং সতং পকোটি।</p>
<p class="unindented">পকোটিসতসহস্সানং সতং কোটিপ্পকোটি।</p>
<p class="unindented">কোটিপ্পকোটি সতসহস্সানং সতং নহুতং।</p>
<p class="unindented">নহুতসতসহস্সানং সতং নিন্নহুতং</p>
<p class="unindented">নিন্নহুতসতসহস্সানং সতং অক্খোহিণি।</p>
<p class="unindented">অপরো নযো-একং দসং সতং সহস্সং</p>
<p class="unindented">দসসহস্সং সতসহস্সং দসসতসহস্সং</p>
<p class="unindented">কোটি পকোটি কোটিপ্পকোটি নহুতং</p>
<p class="unindented">নিন্নহুতং অক্খোহিণীতি এৰং</p>
<p class="unindented">একতো পট্ঠায গুণীযমানা অক্খোহিণি</p>
<p class="unindented">তেরসম ঠানং হুত্বা তিট্ঠতি।</p>
<p class="unindented">নৰ নাগসহস্সানি নাগে নাগে সতং রথা</p>
<p class="unindented">রথে রথে সতং অস্সা অস্সে অস্সে সতং নরা</p>
<p class="unindented">নরে নরে সতং কঞ্ঞা একে কিস্সং সতিত্থিযো</p>
<p class="unindented">এসা অক্খোহিণী নাম পুব্বাচরিযেহি ভাসিতাতি।</p>
<p class="unindented">অক্খোহিণীচ ভিন্দূচ অব্বুদংচ নিরব্বুদং</p>
<p class="unindented">অহহং অববঞ্চেৰ অটটংচ সুগন্ধিকং</p>
<p class="unindented">উপ্পলং কুমুদঞ্চেৰ পুণ্ডরীকং পদুমং তথা</p>
<p class="unindented">কথানং মহাকথানং অসংখেয্যন্তি ভাসিতো।</p>
<p class="unindented">কমো কচ্চাযনে এসো পালিযা সো ৰিরুজ্ঝতি</p>
<p class="unindented">পালিযন্তু কমো এৰং ৰেদিতব্বো নিরব্বুদা</p>
<p class="unindented">অববং অটটং অহহং কুমুদংচ সুগন্ধিকং</p>
<p class="unindented">উপ্পলং পুণ্ডরীকংচ পদুমন্তি জিনোব্রৰীতি।</p>
<p class="centered">ইতি দ্বাদসমো পাঠো।</p>
<p class="centered">ইতি পদমঞ্জরিযা সঙ্খ্যানামানং।</p>
<p class="centered">সত্তমো পরিচ্ছেদো।</p>
<p class="centered">পদমঞ্জরিযা পকরণী সমত্তা।</p>
<p class="centered">সিদ্ধি রত্থু।</p></div>
<div end="ed" class="end"></div>`

document.getElementById('loaddata').innerHTML = anno_9_11 
searchhelper()
bookhelper()
var chapterhelper = document.createElement('script')
chapterhelper.src = `chaptertoggle.js`
loaddata.appendChild(chapterhelper)