var mulaen_2_4_2 = `
<div id="table_main">
<div id="table_name">Table of contents</div></div>
<p class="namo">॥ Namo tassa bhagavato arahato sammāsambuddhassa ॥</p>
<p class="bookname"> 2. Dukanipāta</p>
<p class="author">Translated by Bhikkhu Sujato</p>
<p class="centered">Numbered Discourses 2</p>
<h1 class="chapter">1–⁠10. Kammakaraṇa Vagga</h1>
<div class="chaptxt">
<p class="chaphead">Paṭhamapaṇṇāsaka</p>
<p class="title">1. Punishments</p>
<h3 class="subhead"> AN 2.1 : Faults </h3>
<p class="bodytext"> So I have heard.  At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. There the Buddha addressed the mendicants, “Mendicants!”</p>
<p class="bodytext">“Venerable sir,” they replied. The Buddha said this:</p>
<p class="bodytext">“There are, mendicants, these two faults. What two? The fault apparent in the present life, and the fault to do with lives to come.</p>
<p class="bodytext">What is the fault apparent in the present life? It’s when someone sees that kings have arrested a bandit, a criminal, and subjected them to various punishments— whipping, caning, and clubbing; cutting off hands or feet, or both; cutting off ears or nose, or both; the ‘porridge pot’, the ‘shell-shave’, the ‘demon’s mouth’, the ‘garland of fire’, the ‘burning hand’, the ‘grass blades’, the ‘bark dress’, the ‘antelope’, the ‘meat hook’, the ‘coins’, the ‘acid pickle’, the ‘twisting bar’, the ‘straw mat’; being splashed with hot oil, being fed to the dogs, being impaled alive, and being beheaded.</p>
<p class="bodytext">It occurs to them: ‘If I were to commit the kinds of bad deeds for which the kings arrested that bandit, that criminal, the rulers would arrest me and subject me to the same punishments. Afraid of the fault apparent in the present life, they do not steal the belongings of others. This is called the fault apparent in the present life.</p>
<p class="bodytext">What is the fault to do with lives to come? It’s when someone reflects: ‘Bad conduct of body, speech, or mind has a bad, painful result in the next life. If I conduct myself badly, then, when my body breaks up, after death, won’t I be reborn in a place of loss, a bad place, the underworld, hell?’ Afraid of the fault to do with lives to come, they give up bad conduct by way of body, speech, and mind, and develop good conduct by way of body, speech, and mind, keeping themselves pure. This is called the fault to do with lives to come.</p>
<p class="bodytext">These are the two faults.</p>
<p class="bodytext">So you should train like this: ‘We will fear the fault apparent in the present life, and we will fear the fault to do with lives to come. We will fear faults, seeing the danger in faults.’ That’s how you should train. If you fear faults, seeing the danger in faults, you can expect to be freed from all faults.”</p>
<h3 class="subhead"> AN 2.2 : Endeavor </h3>
<p class="bodytext">“These two endeavors are challenging in the world. What two? The endeavor of laypeople staying in a home to provide robes, alms-food, lodgings, and medicines and supplies for the sick. And the endeavor of those gone forth from the lay life to homelessness to let go of all attachments. These are the two endeavors that are challenging in the world.</p>
<p class="bodytext">The better of these two endeavors is the effort to let go of all attachments.</p>
<p class="bodytext">So you should train like this: ‘We shall endeavor to let go of all attachments.’ That’s how you should train.”</p>
<h3 class="subhead"> AN 2.3 : Mortifying </h3>
<p class="bodytext">“These two things, mendicants, are mortifying. What two? It’s when someone has done bad things and not done good things, by way of body, speech, and mind. Thinking, ‘I’ve done bad things by way of body, speech, and mind’, they’re mortified. Thinking, ‘I haven’t done good things by way of body, speech, and mind’, they’re mortified. These are the two things that are mortifying.”</p>
<h3 class="subhead"> AN 2.4 : Not Mortifying </h3>
<p class="bodytext">“These two things, mendicants, are not mortifying. What two? It’s when someone has done good things and not done bad things, by way of body, speech, and mind. Thinking, ‘I’ve done good things by way of body, speech, and mind’, they’re not mortified. Thinking, ‘I haven’t done bad things by way of body, speech, and mind’, they’re not mortified. These are the two things that are not mortifying.”</p>
<h3 class="subhead"> AN 2.5 : Learned for Myself </h3>
<p class="bodytext">“Mendicants, I have learned these two things for myself— to never be content with skillful qualities, and to never stop trying.</p>
<p class="bodytext">I never stopped trying, thinking: ‘Gladly, let only skin, sinews, and bones remain! Let the flesh and blood waste away in my body! I will not stop trying until I have achieved what is possible by manly strength, energy, and vigor.’</p>
<p class="bodytext">It was by diligence that I achieved awakening, and by diligence that I achieved the supreme sanctuary.</p>
<p class="bodytext">If you too never stop trying, thinking: ‘Gladly, let only skin, sinews, and bones remain! Let the flesh and blood waste away in my body! I will not stop trying until I have achieved what is possible by manly strength, energy, and vigor.’ You will soon realize the supreme culmination of the spiritual path in this very life. You will live having achieved with your own insight the goal for which gentlemen rightly go forth from the lay life to homelessness.</p>
<p class="bodytext">So you should train like this: ‘We will never stop trying, thinking: “Gladly, let only skin, sinews, and bones remain! Let the flesh and blood waste away in my body! I will not stop trying until I have achieved what is possible by manly strength, energy, and vigor.”’ That’s how you should train.”</p>
<h3 class="subhead"> AN 2.6 : Fetters </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Seeing things that are prone to being fettered as gratifying, and seeing things that are prone to being fettered as boring. When you keep seeing things that are prone to being fettered as gratifying, you don’t give up greed, hate, and delusion. When these are not given up, you’re not freed from rebirth, old age, and death, from sorrow, lamentation, pain, sadness, and distress. You’re not freed from suffering, I say.</p>
<p class="bodytext">When you keep seeing things that are prone to being fettered as boring, you give up greed, hate, and delusion. When these are given up, you’re freed from rebirth, old age, and death, from sorrow, lamentation, pain, sadness, and distress. You’re freed from suffering, I say. These are the two things.”</p>
<h3 class="subhead"> AN 2.7 : Dark </h3>
<p class="bodytext">“These two things, mendicants, are dark. What two? Lack of conscience and prudence. These are the two things that are dark.”</p>
<h3 class="subhead"> AN 2.8 : Bright </h3>
<p class="bodytext">“These two things, mendicants, are bright. What two? Conscience and prudence. These are the two things that are bright.”</p>
<h3 class="subhead"> AN 2.9 : Conduct </h3>
<p class="bodytext">“These two bright things, mendicants, protect the world. What two? Conscience and prudence. If these two bright things did not protect the world, there would be no recognition of the status of mother, aunts, or wives and partners of teachers and respected people. The world would become promiscuous, like goats and sheep, chickens and pigs, and dogs and jackals. But because the two bright things protect the world, there is recognition of the status of mother, aunts, and wives and partners of teachers and respected people.”</p>
<h3 class="subhead"> AN 2.10 : Entering the Rainy Season </h3>
<p class="bodytext">“There are, mendicants, these two entries to the rainy season. What two? Earlier and later. These are the two entries to the rainy season.”</p></div>
<h1 class="chapter">11–⁠20. Adhikaraṇa Vagga</h1>
<div class="chaptxt">
<p class="title">2. Issues</p>
<h3 class="subhead"> AN 2.11 </h3>
<p class="bodytext">“There are, mendicants, these two powers. What two? The power of reflection and the power of development. And what, mendicants, is the power of reflection? It’s when someone reflects: ‘Bad conduct of body, speech, or mind has a bad, painful result in both this life and the next.’ Reflecting like this, they give up bad conduct by way of body, speech, and mind, and develop good conduct by way of body, speech, and mind, keeping themselves pure. This is called the power of reflection.</p>
<p class="bodytext">And what, mendicants, is the power of development? In this context, the power of development is the power of the trainees. For when you rely on the power of a trainee, you give up greed, hate, and delusion. Then you don’t do anything unskillful, or practice anything bad. This is called the power of development. These are the two powers.”</p>
<h3 class="subhead"> AN 2.12 </h3>
<p class="bodytext">“There are, mendicants, these two powers. What two? The power of reflection and the power of development. And what, mendicants, is the power of reflection? It’s when someone reflects: ‘Bad conduct of body, speech, or mind has a bad, painful result in both this life and the next.’ Reflecting like this, they give up bad conduct by way of body, speech, and mind, and develop good conduct by way of body, speech, and mind, keeping themselves pure. This is called the power of reflection.</p>
<p class="bodytext">And what, mendicants, is the power of development? It’s when a mendicant develops the awakening factors of mindfulness, investigation of principles, energy, rapture, tranquility, immersion, and equanimity, which rely on seclusion, fading away, and cessation, and ripen as letting go. This is called the power of development. These are the two powers.”</p>
<h3 class="subhead"> AN 2.13 </h3>
<p class="bodytext">“There are, mendicants, these two powers. What two? The power of reflection and the power of development. And what, mendicants, is the power of reflection? It’s when someone reflects: ‘Bad conduct of body, speech, or mind has a bad, painful result in both this life and the next.’ Reflecting like this, they give up bad conduct by way of body, speech, and mind, and develop good conduct by way of body, speech, and mind, keeping themselves pure. This is called the power of reflection.</p>
<p class="bodytext">And what, mendicants, is the power of development? It’s when a mendicant, quite secluded from sensual pleasures, secluded from unskillful qualities, enters and remains in the first absorption, which has the rapture and bliss born of seclusion, while placing the mind and keeping it connected. As the placing of the mind and keeping it connected are stilled, they enter and remain in the second absorption, which has the rapture and bliss born of immersion, with internal clarity and confidence, and unified mind, without placing the mind and keeping it connected. And with the fading away of rapture, they enter and remain in the third absorption, where they meditate with equanimity, mindful and aware, personally experiencing the bliss of which the noble ones declare, ‘Equanimous and mindful, one meditates in bliss.’ Giving up pleasure and pain, and ending former happiness and sadness, they enter and remain in the fourth absorption, without pleasure or pain, with pure equanimity and mindfulness. This is called the power of development. These are the two powers.”</p>
<h3 class="subhead"> AN 2.14 </h3>
<p class="bodytext">“There are, mendicants, these two ways of teaching the Dhamma. What two? In brief and in detail. These are two ways of teaching the Dhamma.”</p>
<h3 class="subhead"> AN 2.15 </h3>
<p class="bodytext">“Mendicants, in a disciplinary issue, if neither the offending mendicant nor the accusing mendicant carefully checks themselves, you can expect that issue will lead to lasting acrimony and enmity, and the mendicants won’t live comfortably. But in a disciplinary issue, if both the offending mendicant and the accusing mendicant carefully check themselves, you can expect that issue won’t lead to lasting acrimony and enmity, and the mendicants will live comfortably.</p>
<p class="bodytext">And how, mendicants, does an offending mendicant carefully check themselves? An offending mendicant reflects: ‘I have committed a certain unskillful offense with the body. That mendicant saw me do this. If I hadn’t committed that offense, they wouldn’t have seen me. But since I did commit that offense, they did see me. When they saw me, they were upset, and they voiced their unhappiness to me. Then I also got upset, so I told others. So the mistake is mine alone, like someone who owes customs duty on their goods.’ That’s how, mendicants, an offending mendicant carefully checks themselves.</p>
<p class="bodytext">And how, mendicants, does an accusing mendicant carefully check themselves? An accusing mendicant reflects: ‘This mendicant has committed a certain unskillful offense with the body. I saw them do that. If they hadn’t committed that offense, I wouldn’t have seen them. But since they did commit that offense, I did see them. When I saw them, I was upset, and I voiced my unhappiness to them. Then they also got upset, so they told others. So the mistake is mine alone, like someone who owes customs duty on their goods.’ That’s how, mendicants, an accusing mendicant carefully checks themselves.</p>
<p class="bodytext">In a disciplinary issue, if neither the offending mendicant nor the accusing mendicant carefully checks themselves, you can expect that issue will lead to lasting acrimony and enmity, and the mendicants won’t live comfortably. But in a disciplinary issue, if both the offending mendicant and the accusing mendicant carefully checks themselves, you can expect that issue won’t lead to lasting acrimony and enmity, and the mendicants will live comfortably.”</p>
<h3 class="subhead"> AN 2.16 </h3>
<p class="bodytext">Then a certain brahmin went up to the Buddha and exchanged greetings with him. When the greetings and polite conversation were over, he sat down to one side and said to the Buddha:</p>
<p class="bodytext">“What is the cause, Master Gotama, what is the reason why some sentient beings, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell?”</p>
<p class="bodytext">“Unprincipled and immoral conduct is the reason why some sentient beings, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell.”</p>
<p class="bodytext">“What is the cause, Master Gotama, what is the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm?”</p>
<p class="bodytext">“Principled and moral conduct is the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.”</p>
<p class="bodytext">“Excellent, Master Gotama! Excellent! As if he was righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with good eyes can see what’s there, Master Gotama has made the teaching clear in many ways. I go for refuge to Master Gotama, to the teaching, and to the mendicant Saṅgha. From this day forth, may Master Gotama remember me as a lay follower who has gone for refuge for life.”</p>
<h3 class="subhead"> AN 2.17 </h3>
<p class="bodytext">Then the brahmin Jāṇussoṇi went up to the Buddha, and exchanged greetings with him. When the greetings and polite conversation were over, he sat down to one side and said to the Buddha:</p>
<p class="bodytext">“What is the cause, Master Gotama, what is the reason why some sentient beings, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell?”</p>
<p class="bodytext">“What they’ve done and what they’ve not done. That’s why some sentient beings, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell.”</p>
<p class="bodytext">“But what is the cause, Master Gotama, what is the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm?”</p>
<p class="bodytext">“What they’ve done and what they’ve not done. That’s why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.”</p>
<p class="bodytext">“I don’t understand the meaning of what Master Gotama has said in brief, without explaining the details. Master Gotama, please teach me this matter in detail so I can understand the meaning.”</p>
<p class="bodytext">“Well then, brahmin, listen and pay close attention, I will speak.”</p>
<p class="bodytext">“Yes sir,” Jāṇussoṇi replied. The Buddha said this:</p>
<p class="bodytext">“Firstly, brahmin, someone has done bad things and not done good things by way of body, speech, and mind. So what they’ve done and what they’ve not done is why some sentient beings, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell. Furthermore, brahmin, someone has done good things and not done bad things by way of body, speech, and mind. So what they’ve done and what they’ve not done is why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.”</p>
<p class="bodytext">“Excellent, Master Gotama! … From this day forth, may Master Gotama remember me as a lay follower who has gone for refuge for life.”</p>
<h3 class="subhead"> AN 2.18 </h3>
<p class="bodytext">Then Venerable Ānanda went up to the Buddha, bowed, and sat down to one side. The Buddha said to him, “Ānanda, I absolutely say that you should not do bad things by way of body, speech, and mind.”</p>
<p class="bodytext">“But, sir, if someone does these things that should not be done, what drawbacks should they expect?”</p>
<p class="bodytext">“They should expect these drawbacks. They blame themselves. After examination, sensible people criticize them. They get a bad reputation. They feel lost when they die. And when their body breaks up, after death, they are reborn in a place of loss, a bad place, the underworld, hell. These are the drawbacks they should expect.”</p>
<p class="bodytext">“Ānanda, I absolutely say that you should do good things by way of body, speech, and mind.”</p>
<p class="bodytext">“But, sir, if someone does these things that should be done, what benefits should they expect?”</p>
<p class="bodytext">“They should expect these benefits. They don’t blame themselves. After examination, sensible people praise them. They get a good reputation. They don’t feel lost when they die. And when the body breaks up, after death, they are reborn in a good place, a heavenly realm. These are the benefits they should expect.”</p>
<h3 class="subhead"> AN 2.19 </h3>
<p class="bodytext">“Mendicants, give up the unskillful. It is possible to give up the unskillful. If it wasn’t possible, I wouldn’t say: ‘Give up the unskillful.’ But it is possible, and so I say: ‘Give up the unskillful.’ And if giving up the unskillful led to harm and suffering, I would not say: ‘Give up the unskillful.’ But giving up the unskillful leads to welfare and happiness, so I say: ‘Give up the unskillful.’</p>
<p class="bodytext">Mendicants, develop the skillful. It is possible to develop the skillful. If it wasn’t possible, I wouldn’t say: ‘Develop the skillful.’ But it is possible, and so I say: ‘Develop the skillful.’ If developing the skillful led to harm and suffering I wouldn’t say: ‘Develop the skillful.’ But developing the skillful leads to welfare and happiness, so I say: ‘Develop the skillful.’”</p>
<h3 class="subhead"> AN 2.20 </h3>
<p class="bodytext">“These two things, mendicants, lead to the decline and disappearance of the true teaching. What two? The words and phrases are misplaced, and the meaning is misinterpreted. When the words and phrases are misplaced, the meaning is misinterpreted. These two things lead to the decline and disappearance of the true teaching.</p>
<p class="bodytext">These two things lead to the continuation, persistence, and enduring of the true teaching. What two? The words and phrases are well organized, and the meaning is correctly interpreted. When the words and phrases are well organized, the meaning is correctly interpreted. These two things lead to the continuation, persistence, and enduring of the true teaching.”</p></div>
<h1 class="chapter">21–⁠31. Bāla Vagga</h1>
<div class="chaptxt">
<p class="title">3. Fools</p>
<h3 class="subhead"> AN 2.21 </h3>
<p class="bodytext">“Mendicants, there are two fools. What two? One who doesn’t recognize when they’ve made a mistake. And one who doesn’t properly accept the confession of someone who’s made a mistake. These are the two fools.</p>
<p class="bodytext">There are two who are astute. What two? One who recognizes when they’ve made a mistake. And one who properly accepts the confession of someone who’s made a mistake. These are the two who are astute.”</p>
<h3 class="subhead"> AN 2.22 </h3>
<p class="bodytext">“Mendicants, these two misrepresent the Realized One. What two? One who is hateful and hides it, and one whose faith is mistaken. These two misrepresent the Realized One.”</p>
<h3 class="subhead"> AN 2.23 </h3>
<p class="bodytext">“Mendicants, these two misrepresent the Realized One. What two? One who explains what was not spoken by the Realized One as spoken by him. And one who explains what was spoken by the Realized One as not spoken by him. These two misrepresent the Realized One.</p>
<p class="bodytext">These two don’t misrepresent the Realized One. What two? One who explains what was not spoken by the Realized One as not spoken by him. And one who explains what was spoken by the Realized One as spoken by him. These two don’t misrepresent the Realized One.”</p>
<h3 class="subhead"> AN 2.24 </h3>
<p class="bodytext">“Mendicants, these two misrepresent the Realized One. What two? One who explains a discourse in need of interpretation as a discourse whose meaning is explicit. And one who explains a discourse whose meaning is explicit as a discourse in need of interpretation. These two misrepresent the Realized One.”</p>
<h3 class="subhead"> AN 2.25 </h3>
<p class="bodytext">“These two don’t misrepresent the Realized One. What two? One who explains a discourse in need of interpretation as a discourse in need of interpretation. And one who explains a discourse whose meaning is explicit as a discourse whose meaning is explicit. These two don’t misrepresent the Realized One.”</p>
<h3 class="subhead"> AN 2.26 </h3>
<p class="bodytext">“Mendicants, when you hide your misdeeds, you can expect one of two destinies: hell or the animal realm.</p>
<p class="bodytext">When you don’t hide your misdeeds, you can expect one of two destinies: as a god or a human.”</p>
<h3 class="subhead"> AN 2.27 </h3>
<p class="bodytext">“Mendicants, when you have wrong view, you can expect one of two destinies: hell or the animal realm.”</p>
<h3 class="subhead"> AN 2.28 </h3>
<p class="bodytext">“Mendicants, when you have right view, you can expect one of two destinies: as a god or a human.”</p>
<h3 class="subhead"> AN 2.29 </h3>
<p class="bodytext">“There are two places waiting to receive an unethical person: hell and the animal realm.</p>
<p class="bodytext">There are two places waiting to receive an ethical person: the realms of gods and humans.”</p>
<h3 class="subhead"> AN 2.30 </h3>
<p class="bodytext">“Mendicants, I see two reasons to frequent remote lodgings in the wilderness and the forest. What two? Seeing a happy life for oneself in the present, and having compassion for future generations. I see two reasons to frequent remote lodgings in the wilderness and the forest.”</p>
<h3 class="subhead"> AN 2.31 </h3>
<p class="bodytext">“These two things play a part in realization. What two? Serenity and discernment.</p>
<p class="bodytext">What is the benefit of developing serenity? The mind is developed. What is the benefit of developing the mind? Greed is given up.</p>
<p class="bodytext">What is the benefit of developing discernment? Wisdom is developed. What is the benefit of developing wisdom? Ignorance is given up.</p>
<p class="bodytext">The mind contaminated by greed is not free; and wisdom contaminated by ignorance does not grow. In this way, freedom of heart comes from the fading away of greed, while freedom by wisdom comes from the fading away of ignorance.”</p></div>
<h1 class="chapter">32–⁠41. Samacitta Vagga</h1>
<div class="chaptxt">
<p class="title">4. Peaceful Mind</p>
<h3 class="subhead"> AN 2.32 </h3>
<p class="bodytext">“Mendicants, I will teach you the level of the bad person and the level of the good person. Listen and pay close attention, I will speak.”</p>
<p class="bodytext">“Yes, sir,” they replied. The Buddha said this:</p>
<p class="bodytext">“What is the level of the bad person? The bad person is ungrateful and thankless, for the wicked only know how to be ungrateful and thankless. It is totally the level of a bad person to be ungrateful and thankless. The good person is grateful and thankful, for the virtuous only know how to be grateful and thankful. It is totally the level of a good person to be grateful and thankful.”</p>
<h3 class="subhead"> AN 2.33 </h3>
<p class="bodytext">“Mendicants, I say that these two people cannot easily be repaid. What two? Mother and father.</p>
<p class="bodytext">You would not have done enough to repay your mother and father even if you were to carry your mother around on one shoulder, and your father on the other, and if you lived like this for a hundred years, and if you were to anoint, massage, bathe, and rub them; and even if they were to defecate and urinate right there.</p>
<p class="bodytext">Even if you were to establish your mother and father as supreme monarchs of this great earth, abounding in the seven treasures, you would still not have done enough to repay them. Why is that? Parents are very helpful to their children, they raise them, nurture them, and show them the world.</p>
<p class="bodytext">But you have done enough, more than enough, to repay them if you encourage, settle, and ground unfaithful parents in faith, unethical parents in ethical conduct, stingy parents in generosity, or ignorant parents in wisdom.”</p>
<h3 class="subhead"> AN 2.34 </h3>
<p class="bodytext">Then a certain brahmin went up to the Buddha, and exchanged greetings with him. When the greetings and polite conversation were over, he sat down to one side and said to the Buddha, “What does Master Gotama teach? What does he explain?”</p>
<p class="bodytext">“Brahmin, I teach action and inaction.”</p>
<p class="bodytext">“But in what way does Master Gotama teach action and inaction?”</p>
<p class="bodytext">“I teach inaction regarding bad bodily, verbal, and mental conduct, and the many kinds of unskillful things. I teach action regarding good bodily, verbal, and mental conduct, and the many kinds of skillful things. This is the kind of action and inaction that I teach.”</p>
<p class="bodytext">“Excellent, Master Gotama! … From this day forth, may Master Gotama remember me as a lay follower who has gone for refuge for life.”</p>
<h3 class="subhead"> AN 2.35 </h3>
<p class="bodytext">Then the householder Anāthapiṇḍika went up to the Buddha, bowed, sat down to one side, and said to the Buddha, “How many kinds of people in the world are worthy of a religious donation? And where should a gift be given?”</p>
<p class="bodytext">“Householder, there are two kinds of people in the world who are worthy of a religious donation: the trainee and the master. These are two kinds of people in the world who are worthy of a religious donation, and that’s where you should give a gift.”</p>
<p class="bodytext">That is what the Buddha said. Then the Holy One, the Teacher, went on to say:</p>
<p class="gatha0">“In this world, the trainee and the master, </p>
<p class="gatha">are worthy of the offerings of those who sponsor sacrifices. </p>
<p class="gatha">They are upright in body, </p>
<p class="gatha">speech, and mind. </p>
<p class="gatha">This is the field for sponsors of sacrifice— </p>
<p class="gatha">what’s given here is very fruitful.”</p>
<h3 class="subhead"> AN 2.36 </h3>
<p class="bodytext"> So I have heard.  At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery.</p>
<p class="bodytext">Now at that time Venerable Sāriputta was staying near Sāvatthī in the Eastern Monastery, the stilt longhouse of Migāra’s mother. There Sāriputta addressed the mendicants: “Reverends, mendicants!”</p>
<p class="bodytext">“Reverend,” they replied. Sāriputta said this:</p>
<p class="bodytext">“I will teach you about a person fettered internally and one fettered externally. Listen and pay close attention, I will speak.”</p>
<p class="bodytext">“Yes, reverend,” they replied. Sāriputta said this:</p>
<p class="bodytext">“Who is a person fettered internally? It’s a mendicant who is ethical, restrained in the monastic code, conducting themselves well and seeking alms in suitable places. Seeing danger in the slightest fault, they keep the rules they’ve undertaken. When their body breaks up, after death, they’re reborn in one of the orders of gods. When they pass away from there, they’re a returner, who comes back to this state of existence. This is called a person who is fettered internally, a returner, who comes back to this state of existence.</p>
<p class="bodytext">Who is a person fettered externally? It’s a mendicant who is ethical, restrained in the monastic code, conducting themselves well and seeking alms in suitable places. Seeing danger in the slightest fault, they keep the rules they’ve undertaken. They enter and remain in a certain peaceful state of freed mind. When their body breaks up, after death, they’re reborn in one of the orders of gods. When they pass away from there, they’re a non-returner, not coming back to this state of existence. This is called a person who is fettered externally, a non-returner, who does not come back to this state of existence.</p>
<p class="bodytext">Furthermore, a mendicant is ethical … they keep the rules they’ve undertaken. They simply practice for disillusionment, dispassion, and cessation regarding sensual pleasures. They simply practice for disillusionment, dispassion, and cessation regarding future lives. They practice for the ending of craving. They practice for the ending of greed. When their body breaks up, after death, they are reborn in one of the orders of gods. When they pass away from there, they are non-returners, not coming back to this state of existence. This is called a person who is fettered externally, a non-returner, who does not come back to this state of existence.”</p>
<p class="bodytext">Then several peaceful-minded deities went up to the Buddha, bowed, stood to one side, and said to the Buddha, “Sir, Venerable Sāriputta is in the Eastern Monastery, the stilt longhouse of Migāra’s mother, where he is teaching the mendicants about a person with internal fetters and one with external fetters. The assembly is overjoyed! Sir, please go to Venerable Sāriputta out of compassion.” The Buddha consented in silence.</p>
<p class="bodytext">Then the Buddha, as easily as a strong person would extend or contract their arm, vanished from Jeta’s Grove and reappeared in the Eastern Monastery, the stilt longhouse of Migāra’s mother, in front of Sāriputta. He sat on the seat spread out. Sāriputta bowed to the Buddha and sat down to one side. The Buddha said to him:</p>
<p class="bodytext">“Just now, Sāriputta, several peaceful-minded deities came up to me, bowed, and stood to one side. Those deities said to me: ‘Sir, Venerable Sāriputta is in the Eastern Monastery, the stilt longhouse of Migāra’s mother, where he is teaching the mendicants about a person with internal fetters and one with external fetters. The assembly is overjoyed! Sir, please go to Venerable Sāriputta out of compassion.’</p>
<p class="bodytext">Those deities, though they number ten, twenty, thirty, forty, fifty, or sixty, can stand on the point of a needle without bumping up against each other.</p>
<p class="bodytext">Sāriputta, you might think: ‘Surely those deities, since so many of them can stand on the point of a needle without bumping up against each other, must have developed their minds in that place.’ But you should not see it like this. It was right here that those deities developed their minds.</p>
<p class="bodytext">So you should train like this: ‘We shall have peaceful faculties and peaceful minds.’ That’s how you should train. When your faculties and mind are peaceful, your acts of body, speech, and mind will be peaceful, thinking: ‘We shall present the gift of peace to our spiritual companions.’ That’s how you should train.</p>
<p class="bodytext">Those wanderers who follow other paths, Sāriputta, who have not heard this exposition of the teaching are lost.”</p>
<h3 class="subhead"> AN 2.37 </h3>
<p class="bodytext"> So I have heard.  At one time Venerable Mahākaccāna was staying at Varaṇā, on the bank of the Kaddama Lake.</p>
<p class="bodytext">Then the brahmin Ārāmadaṇḍa went up to Mahākaccāna, and exchanged greetings with him. When the greetings and polite conversation were over, he sat down to one side and said to Mahākaccāna:</p>
<p class="bodytext">“What is the cause, Master Kaccāna, what is the reason why aristocrats fight with aristocrats, brahmins fight with brahmins, and householders fight with householders?”</p>
<p class="bodytext">“It is because of their insistence on sensual desire, their shackles, avarice, and attachment, that aristocrats fight with aristocrats, brahmins fight with brahmins, and householders fight with householders.”</p>
<p class="bodytext">“What is the cause, Master Kaccāna, what is the reason why ascetics fight with ascetics?”</p>
<p class="bodytext">“It is because of their insistence on views, their shackles, avarice, and attachment, that ascetics fight with ascetics.”</p>
<p class="bodytext">“Master Kaccāna, is there anyone in the world who has gone beyond the insistence on sensual desire and the insistence on views?”</p>
<p class="bodytext">“There is, brahmin.”</p>
<p class="bodytext">“Who in the world has gone beyond the insistence on sensual desire and the insistence on views?”</p>
<p class="bodytext">“In the eastern lands there is a city called Sāvatthī. There the Blessed One is now staying, the perfected one, the fully awakened Buddha. He, brahmin, has gone beyond the insistence on sensual desire and the insistence on views.”</p>
<p class="bodytext">When this was said, the brahmin Ārāmadaṇḍa got up from his seat, arranged his robe over one shoulder, knelt on his right knee, raised his joined palms toward the Buddha, and was inspired to exclaim three times:</p>
<p class="bodytext">“Homage to that Blessed One, the perfected one, the fully awakened Buddha!</p>
<p class="bodytext">Homage to that Blessed One, the perfected one, the fully awakened Buddha!</p>
<p class="bodytext">Homage to that Blessed One, the perfected one, the fully awakened Buddha!</p>
<p class="bodytext">He who has gone beyond the insistence on sensual desire and the insistence on views.</p>
<p class="bodytext">Excellent, Master Kaccāna! Excellent! As if he were righting the overturned, or revealing the hidden, or pointing out the path to the lost, or lighting a lamp in the dark so people with good eyes can see what’s there, Master Kaccāna has made the teaching clear in many ways. I go for refuge to Master Gotama, to the teaching, and to the mendicant Saṅgha. From this day forth, may Master Kaccāna remember me as a lay follower who has gone for refuge for life.”</p>
<h3 class="subhead"> AN 2.38 </h3>
<p class="bodytext">At one time Venerable Mahākaccāna was staying near Madhurā, in Gunda’s Grove.</p>
<p class="bodytext">Then the brahmin Kandarāyana went up to Mahākaccāna, and exchanged greetings with him … He sat down to one side and said to Mahākaccāna:</p>
<p class="bodytext">“I have heard, Master Kaccāna, that the ascetic Kaccāna doesn’t bow to old brahmins, the elderly and senior, who are advanced in years and have reached the final stage of life; nor does he rise in their presence or offer them a seat. And this is indeed the case, for the ascetic Kaccāna does not bow to old brahmins, elderly and senior, who are advanced in years and have reached the final stage of life; nor does he rise in their presence or offer them a seat. This is not appropriate, Master Kaccāna.”</p>
<p class="bodytext">“There is the stage of an elder and the stage of youth as explained by the Blessed One, who knows and sees, the perfected one, the fully awakened Buddha. If an elder, though eighty, ninety, or a hundred years old, still dwells in the midst of sensual pleasures, enjoying them, consumed by thoughts of them, burning with fever for them, and eagerly seeking more, they are reckoned as a child, not a senior. If a youth, young, black-haired, blessed with youth, in the prime of life, does not dwell in the midst of sensual pleasures, enjoying them, consumed by thoughts of them, burning with fever for them, and eagerly seeking more, they are reckoned as astute, a senior.”</p>
<p class="bodytext">When this was said, the brahmin Kandarāyana got up from his seat, placed his robe over one shoulder, and bowed with his head at the feet of the young mendicants, saying, “The masters are elders, at the stage of the elder; we are youths, at the stage of youth.</p>
<p class="bodytext">Excellent, Master Kaccāna! … From this day forth, may Master Kaccāna remember me as a lay follower who has gone for refuge for life.”</p>
<h3 class="subhead"> AN 2.39 </h3>
<p class="bodytext">“At a time when bandits are strong, kings are weak. Then the king is not at ease when going out or coming back or when touring the provinces. The brahmins and householders, likewise, are not at ease when going out or coming back, or when inspecting their business activities. In the same way, at a time when bad mendicants are strong, good-hearted mendicants are weak. Then the good-hearted mendicants continually adhere to silence in the midst of the Saṅgha, or they stay in the borderlands. This is for the hurt and unhappiness of the people, for the harm, hurt, and suffering of many people, of gods and humans.</p>
<p class="bodytext">At a time when kings are strong, bandits are weak. Then the king is at ease when going out or coming back or when inspecting the provinces. The brahmins and householders, likewise, are at ease when going out or coming back, or when inspecting their business activities. In the same way, at a time when good-hearted mendicants are strong, bad mendicants are weak. Then the bad mendicants continually adhere to silence in the midst of the Saṅgha, or they leave for some place or other. This is for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans.”</p>
<h3 class="subhead"> AN 2.40 </h3>
<p class="bodytext">“Mendicants, I don’t praise wrong practice for these two, for laypeople and renunciates. Because of wrong practice, neither laypeople nor renunciates succeed in completing the procedure of the skillful teaching.</p>
<p class="bodytext">I praise right practice for these two, for laypeople and renunciates. Because of right practice, both laypeople and renunciates succeed in completing the procedure of the skillful teaching.”</p>
<h3 class="subhead"> AN 2.41 </h3>
<p class="bodytext">“Mendicants, by memorizing the discourses incorrectly, taking only a semblance of the phrasing, some mendicants shut out the meaning and the teaching. They act for the hurt and unhappiness of the people, for the harm, hurt, and suffering of many people, of gods and humans. They make much bad karma and make the true teaching disappear.</p>
<p class="bodytext">But by memorizing the discourses well, not taking only a semblance of the phrasing, some mendicants reinforce the meaning and the teaching. They act for the welfare and happiness of the people, for the benefit, welfare, and happiness of the people, of gods and humans. They make much merit and make the true teaching continue.”</p></div>
<h1 class="chapter">42–⁠51. Parisa Vagga</h1>
<div class="chaptxt">
<p class="title">5. Assemblies</p>
<h3 class="subhead"> AN 2.42 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? A shallow assembly and a deep assembly. And what is a shallow assembly? An assembly where the mendicants are restless, insolent, fickle, gossipy, loose-tongued, unmindful, lacking situational awareness and immersion, with straying minds and undisciplined faculties. This is called a shallow assembly.</p>
<p class="bodytext">And what is a deep assembly? An assembly where the mendicants are not restless, insolent, fickle, gossipy, or loose-tongued, but have established mindfulness, situational awareness, immersion, unified minds, and restrained faculties. This is called a deep assembly. These are the two assemblies. The better of these two assemblies is the deep assembly.”</p>
<h3 class="subhead"> AN 2.43 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? A divided assembly and a harmonious assembly. And what is a divided assembly? An assembly where the mendicants argue, quarrel, and fight, continually wounding each other with barbed words. This is called a divided assembly.</p>
<p class="bodytext">And what is a harmonious assembly? An assembly where the mendicants live in harmony, appreciating each other, without quarreling, blending like milk and water, and regarding each other with kindly eyes. This is called a harmonious assembly. These are the two assemblies. The better of these two assemblies is the harmonious assembly.”</p>
<h3 class="subhead"> AN 2.44 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An assembly of the worst and an assembly of the best. And what is an assembly of the worst? An assembly where the senior mendicants are indulgent and slack, leaders in backsliding, neglecting seclusion, not rousing energy for attaining the unattained, achieving the unachieved, and realizing the unrealized. Those who come after follow their example. They too become indulgent and slack, leaders in backsliding, neglecting seclusion, not rousing energy for attaining the unattained, achieving the unachieved, and realizing the unrealized. This is called an assembly of the worst.</p>
<p class="bodytext">And what is an assembly of the best? An assembly where the senior mendicants are not indulgent or slack, nor are they backsliders; instead, they take the lead in seclusion, rousing energy for attaining the unattained, achieving the unachieved, and realizing the unrealized. Those who come after follow their example. They too are not indulgent or slack, nor are they backsliders; instead, they take the lead in seclusion, rousing energy for attaining the unattained, achieving the unachieved, and realizing the unrealized. This is called an assembly of the best. These are the two assemblies. The better of these two assemblies is the assembly of the best.”</p>
<h3 class="subhead"> AN 2.45 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An ignoble assembly and a noble assembly. And what is an ignoble assembly? An assembly where the mendicants don’t truly understand: ‘This is suffering’ … ‘This is the origin of suffering’ … ‘This is the cessation of suffering’ … ‘This is the practice that leads to the cessation of suffering’. This is called an ignoble assembly.</p>
<p class="bodytext">And what is a noble assembly? An assembly where the mendicants truly understand: ‘This is suffering’ … ‘This is the origin of suffering’ … ‘This is the cessation of suffering’ … ‘This is the practice that leads to the cessation of suffering’. This is called a noble assembly. These are the two assemblies. The better of these two assemblies is the noble assembly.”</p>
<h3 class="subhead"> AN 2.46 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An assembly of the dregs and an assembly of the cream. And what is an assembly of the dregs? An assembly where the mendicants make decisions prejudiced by favoritism, hostility, stupidity, and cowardice. This is called an assembly of the dregs.</p>
<p class="bodytext">And what is an assembly of the cream? An assembly where the mendicants make decisions unprejudiced by favoritism, hostility, stupidity, and cowardice. This is called an assembly of the cream. These are the two assemblies. The better of these two assemblies is the assembly of the cream.”</p>
<h3 class="subhead"> AN 2.47 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An assembly educated in fancy talk, not in questioning, and an assembly educated in questioning, not in fancy talk. And what is an assembly educated in fancy talk, not in questioning? It is an assembly where, when discourses spoken by the Realized One—deep, profound, transcendent, dealing with emptiness—are being recited the mendicants do not want to listen. They don’t pay attention or apply their minds to understand them, nor do they think those teachings are worth learning and memorizing. But when discourses composed by poets—poetry, with fancy words and phrases, composed by outsiders or spoken by disciples—are being recited the mendicants do want to listen. They pay attention and apply their minds to understand them, and they think those teachings are worth learning and memorizing. But when they’ve learned those teachings they don’t question or examine each other, saying: ‘Why does it say this? What does that mean?’ So they don’t clarify what is unclear, or reveal what is obscure, or dispel doubt regarding the many doubtful matters. This is called an assembly educated in fancy talk, not in questioning.</p>
<p class="bodytext">And what is an assembly educated in questioning, not in fancy talk? It is an assembly where, when discourses composed by poets—poetry, with fancy words and phrases, composed by outsiders or spoken by disciples—are being recited the mendicants do not want to listen. They don’t pay attention or apply their minds to understand them, nor do they think those teachings are worth learning and memorizing. But when discourses spoken by the Realized One—deep, profound, transcendent, dealing with emptiness—are being recited the mendicants do want to listen. They pay attention and apply their minds to understand them, and they think those teachings are worth learning and memorizing. And when they’ve learned those teachings they question and examine each other, saying: ‘Why does it say this? What does that mean?’ So they clarify what is unclear, reveal what is obscure, and dispel doubt regarding the many doubtful matters. This is called an assembly educated in questioning, not in fancy talk. These are the two assemblies. The better of these two assemblies is the assembly educated in questioning, not in fancy talk.”</p>
<h3 class="subhead"> AN 2.48 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An assembly that values material things, not the true teaching, and an assembly that values the true teaching, not material things. And what is an assembly that values material things, not the true teaching? It is an assembly where the mendicants praise each other in front of the white-clothed laypeople, saying: ‘The mendicant so-and-so is freed both ways; so-and-so is freed by wisdom; so-and-so is a personal witness; so-and-so is attained to view; so-and-so is freed by faith; so-and-so is a follower of the teachings; so-and-so is a follower by faith; so-and-so is ethical, of good character; so-and-so is unethical, of bad character.’ In this way they get material things. And when they get these things, they use them tied, infatuated, attached, blind to the drawbacks, and not understanding the escape. This is called an assembly that values material things, not the true teaching.</p>
<p class="bodytext">And what is an assembly that values the true teaching, not material things? It is an assembly where the mendicants don’t praise each other in front of the white-clothed laypeople, saying: ‘The mendicant so-and-so is freed both ways; so-and-so is freed by wisdom; so-and-so is a personal witness; so-and-so is attained to view; so-and-so is freed by faith; so-and-so is a follower of the teachings; so-and-so is a follower by faith; so-and-so is ethical, of good character; so-and-so is unethical, of bad character.’ In this way they get material things. And when they get these things, they use them untied, uninfatuated, unattached, seeing the drawbacks, and understanding the escape. This is called an assembly that values the true teaching, not material things. These are the two assemblies. The better of these two assemblies is the assembly that values the true teaching, not material things.”</p>
<h3 class="subhead"> AN 2.49 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An unjust assembly and a just assembly. And what is an unjust assembly? An assembly where legal acts against the teaching proceed, while legal acts in line with the teaching don’t proceed. Legal acts against the training proceed, while legal acts in line with the training don’t proceed. Legal acts against the teaching are explained, while legal acts in line with the teaching aren’t explained. Legal acts against the training are explained, while legal acts in line with the training aren’t explained. This is called an unjust assembly.</p>
<p class="bodytext">And what is a just assembly? An assembly where legal acts in line with the teaching proceed, while legal acts against the teaching don’t proceed. Legal acts in line with the training proceed, while legal acts against the training don’t proceed. Legal acts in line with the teaching are explained, while legal acts against the teaching aren’t explained. Legal acts in line with the training are explained, while legal acts against the training aren’t explained. This is called a just assembly. These are the two assemblies. The better of these two assemblies is the just assembly.”</p>
<h3 class="subhead"> AN 2.50 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An unprincipled assembly and a principled assembly … The better of these two assemblies is the principled assembly.”</p>
<h3 class="subhead"> AN 2.51 </h3>
<p class="bodytext">“There are, mendicants, these two assemblies. What two? An assembly with unprincipled speech, and an assembly with principled speech. And what is an assembly with unprincipled speech? It is an assembly where the mendicants take up disciplinary issues, whether legitimate or not. But they don’t persuade each other or allow themselves to be persuaded, nor do they convince each other or allow themselves to be convinced. Unable to persuade or convince each other, they can’t let go of their opinions. They obstinately stick to that disciplinary issue, insisting that: ‘This is the only truth, other ideas are silly.’ This is called an assembly with unprincipled speech.</p>
<p class="bodytext">And what is an assembly with principled speech? It is an assembly where the mendicants take up disciplinary issues, whether legitimate or not. Then they persuade each other or allow themselves to be persuaded, and they convince each other or allow themselves to be convinced. Since they are able to persuade and convince each other, they let go of their opinions. They don’t obstinately stick to that disciplinary issue or insist that: ‘This is the only truth, other ideas are silly.’ This is called an assembly with principled speech. These are the two assemblies. The better of these two assemblies is the assembly with principled speech.”</p></div>
<h1 class="chapter">52–⁠63. Puggala Vagga</h1>
<div class="chaptxt">
<p class="chaphead">Dutiyapaṇṇāsaka</p>
<p class="title">6. Persons</p>
<h3 class="subhead"> AN 2.52 </h3>
<p class="bodytext">“Two people, mendicants, arise in the world for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans. What two? The Realized One, the perfected one, the fully awakened Buddha; and the wheel-turning monarch. These two people arise in the world for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans.”</p>
<h3 class="subhead"> AN 2.53 </h3>
<p class="bodytext">“Two people, mendicants, arise in the world who are incredible human beings. What two? The Realized One, the perfected one, the fully awakened Buddha; and the wheel-turning monarch. These are the two people who arise in the world who are incredible human beings.”</p>
<h3 class="subhead"> AN 2.54 </h3>
<p class="bodytext">“There are two people, mendicants, whose death is regretted by many people. What two? The Realized One, the perfected one, the fully awakened Buddha; and the wheel-turning monarch. These are the two people, mendicants, whose death is regretted by many people.”</p>
<h3 class="subhead"> AN 2.55 </h3>
<p class="bodytext">“Mendicants, these two are worthy of a monument. What two? The Realized One, the perfected one, the fully awakened Buddha; and the wheel-turning monarch. These are the two who are worthy of a monument.”</p>
<h3 class="subhead"> AN 2.56 </h3>
<p class="bodytext">“Mendicants, there are two kinds of Buddhas. What two? The Realized One, the perfected one, the fully awakened Buddha; and the Buddha awakened for themselves. These are the two kinds of Buddhas.”</p>
<h3 class="subhead"> AN 2.57 </h3>
<p class="bodytext">“These two, mendicants, are not startled by a crack of thunder. What two? A mendicant who has ended defilements; and a thoroughbred elephant. These are the two who are not startled by a crack of thunder.”</p>
<h3 class="subhead"> AN 2.58 </h3>
<p class="bodytext">“These two, mendicants, are not startled by a crack of thunder. What two? A mendicant who has ended defilements; and a thoroughbred horse. These are the two who are not startled by a crack of thunder.”</p>
<h3 class="subhead"> AN 2.59 </h3>
<p class="bodytext">“These two, mendicants, are not startled by a crack of thunder. What two? A mendicant who has ended defilements; and a lion, king of beasts. These are the two who are not startled by a crack of thunder.”</p>
<h3 class="subhead"> AN 2.60 </h3>
<p class="bodytext">“Fauns see two reasons not to use human speech. What two? Thinking: ‘May we not lie, and may we not misrepresent others with falsehoods.’ Fauns see two reasons not to use human speech.”</p>
<h3 class="subhead"> AN 2.61 </h3>
<p class="bodytext">“Mendicants, females die without getting enough of two things. What two? Sexual intercourse and giving birth. Females die without getting enough of these two things.”</p>
<h3 class="subhead"> AN 2.62 </h3>
<p class="bodytext">“Mendicants, I will teach you about living with bad people and living with good people. Listen and pay close attention, I will speak.”</p>
<p class="bodytext">“Yes, sir,” they replied. The Buddha said this:</p>
<p class="bodytext">“What is it like living with bad people? How do bad people live together?</p>
<p class="bodytext">It’s when a senior mendicant thinks: ‘No mendicant, whether senior, middle, or junior, should admonish me; and I shouldn’t admonish any mendicant, whether senior, middle, or junior. If a mendicant—whether senior, middle, or junior—were to admonish me, they wouldn’t be sympathetic, and I’d bother them by saying “No!” And anyway I wouldn’t deal with it even if I saw what I did wrong.’</p>
<p class="bodytext">And a middle or a junior mendicant also thinks: ‘No mendicant, whether senior, middle, or junior, should admonish me; and I shouldn’t admonish any mendicant, whether senior, middle, or junior. If a mendicant—whether senior, middle, or junior—were to admonish me, they wouldn’t be sympathetic, and I’d bother them by saying “No!” And anyway I wouldn’t deal with it even if I saw what I did wrong.’</p>
<p class="bodytext">That’s what it’s like living with bad people; that’s how bad people live together.</p>
<p class="bodytext">What is it like living with good people? How do good people live together? It’s when a senior mendicant thinks:</p>
<p class="bodytext">‘Any mendicant, whether senior, middle, or junior, should admonish me; and I should admonish any mendicant, whether senior, middle, or junior. If a mendicant—whether senior, middle, or junior—were to admonish me, they’d be sympathetic, so I wouldn’t bother them, but say “Thank you!” And I’d deal with it when I saw what I did wrong.’</p>
<p class="bodytext">And a middle or a junior mendicant also thinks: ‘Any mendicant, whether senior, middle, or junior, may admonish me; and I’ll admonish any mendicant, whether senior, middle, or junior. If a mendicant—whether senior, middle, or junior—were to admonish me, they’d be sympathetic, so I wouldn’t bother them, but say “Thank you!” And I’d deal with it when I saw what I did wrong.’</p>
<p class="bodytext">That’s what it’s like living with good people; that’s how good people live together.”</p>
<h3 class="subhead"> AN 2.63 </h3>
<p class="bodytext">“In a disciplinary issue, when the tale-bearing on both sides—with contempt for each other’s views, resentful, bitter, and exasperated—is not settled internally, you can expect that this disciplinary issue will be long, fractious, and troublesome, and the mendicants won’t live comfortably.</p>
<p class="bodytext">In a disciplinary issue, when the tale-bearing on both sides—with contempt for each other’s views, resentful, bitter, and exasperated—is well settled internally, you can expect that this disciplinary issue won’t lead to lasting acrimony and enmity, and the mendicants will live comfortably.”</p></div>
<h1 class="chapter">64–⁠76. Sukha Vagga</h1>
<div class="chaptxt">
<p class="title">7. Happiness</p>
<h3 class="subhead"> AN 2.64 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? The happiness of laypeople, and the happiness of renunciates. These are the two kinds of happiness. The better of these two kinds of happiness is the happiness of renunciates.”</p>
<h3 class="subhead"> AN 2.65 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Sensual happiness and the happiness of renunciation. These are the two kinds of happiness. The better of these two kinds of happiness is the happiness of renunciation.”</p>
<h3 class="subhead"> AN 2.66 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? The happiness of attachments, and the happiness of no attachments. These are the two kinds of happiness. The better of these two kinds of happiness is the happiness of no attachments.”</p>
<h3 class="subhead"> AN 2.67 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Defiled happiness and undefiled happiness. These are the two kinds of happiness. The better of these two kinds of happiness is the happiness of no defilements.”</p>
<h3 class="subhead"> AN 2.68 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Material happiness and spiritual happiness. These are the two kinds of happiness. The better of these two kinds of happiness is spiritual happiness.”</p>
<h3 class="subhead"> AN 2.69 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Noble happiness and ignoble happiness. These are the two kinds of happiness. The better of these two kinds of happiness is noble happiness.”</p>
<h3 class="subhead"> AN 2.70 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Physical happiness and mental happiness. These are the two kinds of happiness. The better of these two kinds of happiness is mental happiness.”</p>
<h3 class="subhead"> AN 2.71 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Happiness with rapture and happiness free of rapture. These are the two kinds of happiness. The better of these two kinds of happiness is happiness free of rapture.”</p>
<h3 class="subhead"> AN 2.72 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? The happiness of pleasure and the happiness of equanimity. These are the two kinds of happiness. The better of these two kinds of happiness is the happiness of equanimity.”</p>
<h3 class="subhead"> AN 2.73 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? The happiness of immersion and the happiness without immersion. These are the two kinds of happiness. The better of these two kinds of happiness is the happiness of immersion.”</p>
<h3 class="subhead"> AN 2.74 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Happiness that relies on rapture and happiness that relies on freedom from rapture. These are the two kinds of happiness. The better of these two kinds of happiness is happiness that relies on freedom from rapture.”</p>
<h3 class="subhead"> AN 2.75 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Happiness that relies on pleasure and happiness that relies on equanimity. These are the two kinds of happiness. The better of these two kinds of happiness is happiness that relies on equanimity.”</p>
<h3 class="subhead"> AN 2.76 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of happiness. What two? Happiness that relies on form and happiness that relies on the formless. These are the two kinds of happiness. The better of these two kinds of happiness is happiness that relies on the formless.”</p></div>
<h1 class="chapter">77–⁠86. Sanimitta Vagga</h1>
<div class="chaptxt">
<p class="title">8. With a Foundation</p>
<h3 class="subhead"> AN 2.77 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with a foundation, not without a foundation. By giving up that foundation, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.78 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with a source, not without a source. By giving up that source, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.79 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with a cause, not without a cause. By giving up that cause, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.80 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with conditions, not without conditions. By giving up those conditions, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.81 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with a reason, not without a reason. By giving up that reason, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.82 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with form, not without form. By giving up that form, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.83 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with feeling, not without feeling. By giving up that feeling, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.84 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with perception, not without perception. By giving up that perception, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.85 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with consciousness, not without consciousness. By giving up that consciousness, those bad, unskillful qualities do not occur.”</p>
<h3 class="subhead"> AN 2.86 </h3>
<p class="bodytext">“Bad, unskillful qualities, mendicants, arise with a conditioned basis, not without a conditioned basis. By giving up that conditioned basis, those bad, unskillful qualities do not occur.”</p></div>
<h1 class="chapter">87–⁠97. Dhamma Vagga</h1>
<div class="chaptxt">
<p class="title">9. Things</p>
<h3 class="subhead"> AN 2.87 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Freedom of heart and freedom by wisdom. These are the two things.”</p>
<h3 class="subhead"> AN 2.88 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Exertion, and not being distracted. These are the two things.”</p>
<h3 class="subhead"> AN 2.89 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Name and form. These are the two things.”</p>
<h3 class="subhead"> AN 2.90 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Knowledge and freedom. These are the two things.”</p>
<h3 class="subhead"> AN 2.91 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Views favoring continued existence and views favoring ending existence. These are the two things.”</p>
<h3 class="subhead"> AN 2.92 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Lack of conscience and prudence. These are the two things.”</p>
<h3 class="subhead"> AN 2.93 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Conscience and prudence. These are the two things.”</p>
<h3 class="subhead"> AN 2.94 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Being hard to admonish and having bad friends. These are the two things.”</p>
<h3 class="subhead"> AN 2.95 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Being easy to admonish and having good friends. These are the two things.”</p>
<h3 class="subhead"> AN 2.96 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Skill in the elements and skill in attention. These are the two things.”</p>
<h3 class="subhead"> AN 2.97 </h3>
<p class="bodytext">“There are, mendicants, these two things. What two? Skill in offenses and skill in rehabilitation from offenses. These are the two things.”</p></div>
<h1 class="chapter">98–⁠117. Bāla Vagga</h1>
<div class="chaptxt">
<p class="title">10. Fools</p>
<h3 class="subhead"> AN 2.98 </h3>
<p class="bodytext">“Mendicants, there are two fools. What two? One who takes responsibility for what has not come to pass, and one who doesn’t take responsibility for what has come to pass. These are the two fools.”</p>
<h3 class="subhead"> AN 2.99 </h3>
<p class="bodytext">“There are two who are astute. What two? One who doesn’t take responsibility for what has not come to pass, and one who does take responsibility for what has come to pass. These are the two who are astute.”</p>
<h3 class="subhead"> AN 2.100 </h3>
<p class="bodytext">“Mendicants, there are two fools. What two? One who perceives what is unallowable as allowable, and one who perceives what is allowable as unallowable. These are the two fools.”</p>
<h3 class="subhead"> AN 2.101 </h3>
<p class="bodytext">“There are two who are astute. What two? One who perceives what is unallowable as unallowable, and one who perceives what is allowable as allowable. These are the two who are astute.”</p>
<h3 class="subhead"> AN 2.102 </h3>
<p class="bodytext">“Mendicants, there are two fools. What two? One who perceives a non-offense as an offense, and one who perceives an offense as a non-offense. These are the two fools.”</p>
<h3 class="subhead"> AN 2.103 </h3>
<p class="bodytext">“There are two who are astute. What two? One who perceives a non-offense as a non-offense, and one who perceives an offense as an offense. These are the two who are astute.”</p>
<h3 class="subhead"> AN 2.104 </h3>
<p class="bodytext">“Mendicants, there are two fools. What two? One who perceives what is not the teaching as the teaching, and one who perceives the teaching as not the teaching. These are the two fools.”</p>
<h3 class="subhead"> AN 2.105 </h3>
<p class="bodytext">“There are two who are astute. What two? One who perceives the teaching as the teaching, and one who perceives what is not the teaching as not the teaching. These are the two who are astute.”</p>
<h3 class="subhead"> AN 2.106 </h3>
<p class="bodytext">“Mendicants, there are two fools. What two? One who perceives what is not the training as the training, and one who perceives what is the training as not the training. These are the two fools.”</p>
<h3 class="subhead"> AN 2.107 </h3>
<p class="bodytext">“There are two who are astute. What two? One who perceives what is not the training as not the training, and one who perceives what is the training as the training. These are the two who are astute.”</p>
<h3 class="subhead"> AN 2.108 </h3>
<p class="bodytext">“For these two, defilements grow. What two? One who is remorseful over something they shouldn’t be, and one who isn’t remorseful over something they should be. These are the two whose defilements grow.”</p>
<h3 class="subhead"> AN 2.109 </h3>
<p class="bodytext">“For these two, defilements don’t grow. What two? One who isn’t remorseful over something they shouldn’t be, and one who is remorseful over something they should be. These are the two whose defilements don’t grow.”</p>
<h3 class="subhead"> AN 2.110 </h3>
<p class="bodytext">“For these two, defilements grow. What two? One who perceives what is unallowable as allowable, and one who perceives what is allowable as unallowable. These are the two whose defilements grow.”</p>
<h3 class="subhead"> AN 2.111 </h3>
<p class="bodytext">“For these two, defilements don’t grow. What two? One who perceives what is unallowable as unallowable, and one who perceives what is allowable as allowable. These are the two whose defilements don’t grow.”</p>
<h3 class="subhead"> AN 2.112 </h3>
<p class="bodytext">“For these two, defilements grow. What two? One who perceives an offense as a non-offense, and one who perceives a non-offense as an offense. These are the two whose defilements grow.”</p>
<h3 class="subhead"> AN 2.113 </h3>
<p class="bodytext">“For these two, defilements don’t grow. What two? One who perceives an offense as an offense, and one who perceives a non-offense as a non-offense. These are the two whose defilements don’t grow.”</p>
<h3 class="subhead"> AN 2.114 </h3>
<p class="bodytext">“For these two, defilements grow. What two? One who perceives what is not the teaching as the teaching, and one who perceives the teaching as not the teaching. These are the two whose defilements grow.”</p>
<h3 class="subhead"> AN 2.115 </h3>
<p class="bodytext">“For these two, defilements don’t grow. What two? One who perceives the teaching as the teaching, and one who perceives what is not the teaching as not the teaching. These are the two whose defilements don’t grow.”</p>
<h3 class="subhead"> AN 2.116 </h3>
<p class="bodytext">“For these two, defilements grow. What two? One who perceives what is not the training as the training, and one who perceives what is the training as not the training. These are the two whose defilements grow.”</p>
<h3 class="subhead"> AN 2.117 </h3>
<p class="bodytext">“For these two, defilements don’t grow. What two? One who perceives what is not the training as not the training, and one who perceives what is the training as the training. These are the two whose defilements don’t grow.”</p></div>
<h1 class="chapter">118–⁠129. Āsāduppajaha Vagga</h1>
<div class="chaptxt">
<p class="chaphead">Tatiyapaṇṇāsaka</p>
<p class="title">11. Hopes That Are Hard to Give Up</p>
<h3 class="subhead"> AN 2.118 </h3>
<p class="bodytext">“These two hopes are hard to give up. What two? The hope for wealth and the hope for long life. These are two hopes that are hard to give up.”</p>
<h3 class="subhead"> AN 2.119 </h3>
<p class="bodytext">“These two people are rare in the world. What two? One who takes the initiative, and one who is grateful and thankful. These are the two people who are rare in the world.”</p>
<h3 class="subhead"> AN 2.120 </h3>
<p class="bodytext">“These two people are rare in the world. What two? One who is satisfied, and one who satisfies others. These are the two people who are rare in the world.”</p>
<h3 class="subhead"> AN 2.121 </h3>
<p class="bodytext">“These two people are hard to satisfy in the world. What two? One who continually hoards wealth, and one who continually wastes wealth. These are the two people who are hard to satisfy in the world.”</p>
<h3 class="subhead"> AN 2.122 </h3>
<p class="bodytext">“These two people are easy to satisfy in the world. What two? One who does not continually hoard wealth, and one who does not continually waste wealth. These are the two people who are easy to satisfy in the world.”</p>
<h3 class="subhead"> AN 2.123 </h3>
<p class="bodytext">“There are two conditions for the arising of greed. What two? The feature of beauty and improper attention. These are the two conditions for the arising of greed.”</p>
<h3 class="subhead"> AN 2.124 </h3>
<p class="bodytext">“There are two conditions for the arising of hate. What two? The feature of harshness and improper attention. These are the two conditions for the arising of hate.”</p>
<h3 class="subhead"> AN 2.125 </h3>
<p class="bodytext">“There are two conditions for the arising of wrong view. What two? The words of another and improper attention. These are the two conditions for the arising of wrong view.”</p>
<h3 class="subhead"> AN 2.126 </h3>
<p class="bodytext">“There are two conditions for the arising of right view. What two? The words of another and proper attention. These are the two conditions for the arising of right view.”</p>
<h3 class="subhead"> AN 2.127 </h3>
<p class="bodytext">“There are these two offenses. What two? A light offense and a serious offense. These are the two offenses.”</p>
<h3 class="subhead"> AN 2.128 </h3>
<p class="bodytext">“There are these two offenses. What two? An offense with corrupt intention and an offense without corrupt intention. These are the two offenses.”</p>
<h3 class="subhead"> AN 2.129 </h3>
<p class="bodytext">“There are these two offenses. What two? An offense requiring rehabilitation and an offense not requiring rehabilitation. These are the two offenses.”</p></div>
<h1 class="chapter">130–⁠140. Āyācana Vagga</h1>
<div class="chaptxt">
<p class="title">12. Aspiration</p>
<h3 class="subhead"> AN 2.130 </h3>
<p class="bodytext">“A faithful monk would rightly aspire: ‘May I be like Sāriputta and Moggallāna!’ These are a standard and a measure for my monk disciples, that is, Sāriputta and Moggallāna.”</p>
<h3 class="subhead"> AN 2.131 </h3>
<p class="bodytext">“A faithful nun would rightly aspire: ‘May I be like the nuns Khemā and Uppalavaṇṇā!’ These are a standard and a measure for my nun disciples, that is, the nuns Khemā and Uppalavaṇṇā.”</p>
<h3 class="subhead"> AN 2.132 </h3>
<p class="bodytext">“A faithful layman would rightly aspire: ‘May I be like the householder Citta and Hatthaka of Aḷavī!’ These are a standard and a measure for my male lay followers, that is, the householder Citta and Hatthaka of Aḷavī.”</p>
<h3 class="subhead"> AN 2.133 </h3>
<p class="bodytext">“A faithful laywoman would rightly aspire: ‘May I be like the laywomen Khujjuttarā and Veḷukaṇṭakī, Nanda’s mother!’ These are a standard and a measure for my female lay disciples, that is, the laywomen Khujjuttarā and Veḷukaṇṭakī, Nanda’s mother.”</p>
<h3 class="subhead"> AN 2.134 </h3>
<p class="bodytext">“When a foolish, incompetent bad person has two qualities they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma. What two? Without examining or scrutinizing, they praise those deserving of criticism and they criticize those deserving of praise. When a foolish, incompetent bad person has these two qualities they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma.</p>
<p class="bodytext">When an astute, competent good person has two qualities they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit. What two? After examining and scrutinizing, they criticize those deserving of criticism and they praise those deserving of praise. When an astute, competent good person has these two qualities they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit.”</p>
<h3 class="subhead"> AN 2.135 </h3>
<p class="bodytext">“When a foolish, incompetent bad person has two qualities they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma. What two? Without examining or scrutinizing, they arouse faith in things that are dubious, and they don’t arouse faith in things that are inspiring. When a foolish, incompetent bad person has these two qualities they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma.</p>
<p class="bodytext">When an astute, competent good person has two qualities they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit. What two? After examining or scrutinizing, they don’t arouse faith in things that are dubious, and they do arouse faith in things that are inspiring. When an astute, competent good person has these two qualities they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit.”</p>
<h3 class="subhead"> AN 2.136 </h3>
<p class="bodytext">“When a foolish, incompetent bad person acts wrongly toward two people they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma. What two? Mother and father. When a foolish, incompetent bad person acts wrongly toward these two people they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma.</p>
<p class="bodytext">When an astute, competent good person acts rightly toward two people they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit. What two? Mother and father. When an astute, competent good person acts rightly toward these two people they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit.”</p>
<h3 class="subhead"> AN 2.137 </h3>
<p class="bodytext">“When a foolish, incompetent bad person acts wrongly toward two people they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma. What two? The Realized One and a disciple of the Realized One. When a foolish, incompetent bad person acts wrongly toward these people they keep themselves broken and damaged. They deserve to be blamed and criticized by sensible people, and they make much bad karma.</p>
<p class="bodytext">When an astute, competent good person acts rightly toward two people they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit. What two? The Realized One and a disciple of the Realized One. When an astute, competent good person acts rightly toward these two people they keep themselves healthy and whole. They don’t deserve to be blamed and criticized by sensible people, and they make much merit.”</p>
<h3 class="subhead"> AN 2.138 </h3>
<p class="bodytext">“There are these two things. What two? Cleaning your own mind, and not grasping at anything in the world. These are the two things.”</p>
<h3 class="subhead"> AN 2.139 </h3>
<p class="bodytext">“There are these two things. What two? Anger and hostility. These are the two things.”</p>
<h3 class="subhead"> AN 2.140 </h3>
<p class="bodytext">“There are these two things. What two? Dispelling anger and dispelling hostility. These are the two things.”</p></div>
<h1 class="chapter">141–⁠150. Dāna Vagga</h1>
<div class="chaptxt">
<p class="title">13. Giving</p>
<h3 class="subhead"> AN 2.141 </h3>
<p class="bodytext">“There are these two gifts. What two? A gift of material things and a gift of the teaching. These are the two gifts. The better of these two gifts is the gift of the teaching.”</p>
<h3 class="subhead"> AN 2.142 </h3>
<p class="bodytext">“There are these two offerings. What two? An offering of material things and an offering of the teaching. These are the two offerings. The better of these two offerings is an offering of the teaching.”</p>
<h3 class="subhead"> AN 2.143 </h3>
<p class="bodytext">“There are these two acts of generosity. What two? Generosity with material things and generosity with the teaching. These are the two acts of generosity. The better of these two acts of generosity is generosity with the teaching.”</p>
<h3 class="subhead"> AN 2.144 </h3>
<p class="bodytext">“There are these two kinds of charity. What two? Charity in material things and charity in the teaching. These are the two kinds of charity. The better of these two kinds of charity is a charity in the teaching.”</p>
<h3 class="subhead"> AN 2.145 </h3>
<p class="bodytext">“There are these two riches. What two? Riches in material things and riches in the teaching. These are the two riches. The better of these two riches is riches in the teaching.”</p>
<h3 class="subhead"> AN 2.146 </h3>
<p class="bodytext">“There are these two kinds of enjoyment. What two? Enjoyment of material things and enjoyment of the teaching. These are the two kinds of enjoyment. The better of these two kinds of enjoyment is the enjoyment of the teaching.”</p>
<h3 class="subhead"> AN 2.147 </h3>
<p class="bodytext">“There are these two kinds of sharing. What two? Sharing material things and sharing the teaching. These are the two kinds of sharing. The better of these two kinds of sharing is sharing the teaching.”</p>
<h3 class="subhead"> AN 2.148 </h3>
<p class="bodytext">“There are these two kinds of inclusion. What two? Inclusion in material things and inclusion in the teaching. These are the two kinds of inclusion. The better of these two kinds of inclusion is inclusion in the teaching.”</p>
<h3 class="subhead"> AN 2.149 </h3>
<p class="bodytext">“There are these two kinds of support. What two? Support in material things and support in the teaching. These are the two kinds of support. The better of these two kinds of support is support in the teaching.”</p>
<h3 class="subhead"> AN 2.150 </h3>
<p class="bodytext">“There are these two kinds of sympathy. What two? Sympathy in material things and sympathy in the teaching. These are the two kinds of sympathy. The better of these two kinds of sympathy is sympathy in the teaching.”</p></div>
<h1 class="chapter">151–⁠162. Santhāra Vagga</h1>
<div class="chaptxt">
<p class="title">14. Welcome</p>
<h3 class="subhead"> AN 2.151 </h3>
<p class="bodytext">“There are these two kinds of welcome. What two? Welcome in material things and welcome in the teaching. These are the two kinds of welcome. The better of these two kinds of welcome is the welcome in the teaching.”</p>
<h3 class="subhead"> AN 2.152 </h3>
<p class="bodytext">“There are these two kinds of hospitality. What two? Hospitality in material things and hospitality in the teaching. These are the two kinds of hospitality. The better of these two kinds of hospitality is hospitality in the teaching.”</p>
<h3 class="subhead"> AN 2.153 </h3>
<p class="bodytext">“There are these two quests. What two? The quest for material things and the quest for the teaching. These are the two quests. The better of these two quests is the quest for the teaching.”</p>
<h3 class="subhead"> AN 2.154 </h3>
<p class="bodytext">“There are these two searches. What two? The search for material things and the search for the teaching. These are the two searches. The better of these two searches is the search for the teaching.”</p>
<h3 class="subhead"> AN 2.155 </h3>
<p class="bodytext">“There are these two kinds of seeking. What two? Seeking for material things and seeking for the teaching. These are the two kinds of seeking. The better of these two kinds of seeking is seeking for the teaching.”</p>
<h3 class="subhead"> AN 2.156 </h3>
<p class="bodytext">“There are these two kinds of worship. What two? Worship of material things and worship of the teaching. These are the two kinds of worship. The better of these two kinds of worship is worship of the teaching.”</p>
<h3 class="subhead"> AN 2.157 </h3>
<p class="bodytext">“There are these two ways of serving guests. What two? Serving guests with material things and serving guests with the teaching. These are the two ways of serving guests. The better of these two ways of serving guests is to serve them with the teaching.”</p>
<h3 class="subhead"> AN 2.158 </h3>
<p class="bodytext">“There are, mendicants, these two successes. What two? Success in material things and success in the teaching. These are the two successes. The better of these two successes is success in the teaching.”</p>
<h3 class="subhead"> AN 2.159 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of growth. What two? Growth in material things and growth in the teaching. These are the two kinds of growth. The better of these two kinds of growth is growth in the teaching.”</p>
<h3 class="subhead"> AN 2.160 </h3>
<p class="bodytext">“There are these two treasures. What two? The treasure of material things and the treasure of the teaching. These are the two treasures. The better of these two treasures is the treasure of the teaching.”</p>
<h3 class="subhead"> AN 2.161 </h3>
<p class="bodytext">“There are these two kinds of accumulation. What two? Accumulation of material things and accumulation of the teaching. These are the two kinds of accumulation. The better of these two kinds of accumulation is the accumulation of the teaching.”</p>
<h3 class="subhead"> AN 2.162 </h3>
<p class="bodytext">“There are, mendicants, these two kinds of increase. What two? Increase in material things and increase in the teaching. These are the two kinds of increase. The better of these two kinds of increase is increase in the teaching.”</p></div>
<h1 class="chapter">163–⁠179. Samāpatti Vagga</h1>
<div class="chaptxt">
<p class="title">15. Attainment</p>
<h3 class="subhead"> AN 2.163 </h3>
<p class="bodytext">“There are these two things. What two? Skill in meditative attainments and skill in emerging from those attainments. These are the two things.”</p>
<h3 class="subhead"> AN 2.164 </h3>
<p class="bodytext">“There are these two things. What two? Integrity and gentleness. These are the two things.”</p>
<h3 class="subhead"> AN 2.165 </h3>
<p class="bodytext">“There are these two things. What two? Patience and gentleness. These are the two things.”</p>
<h3 class="subhead"> AN 2.166 </h3>
<p class="bodytext">“There are these two things. What two? Friendliness and hospitality. These are the two things.”</p>
<h3 class="subhead"> AN 2.167 </h3>
<p class="bodytext">“There are these two things. What two? Harmlessness and purity. These are the two things.”</p>
<h3 class="subhead"> AN 2.168 </h3>
<p class="bodytext">“There are these two things. What two? Not guarding the sense doors and eating too much. These are the two things.”</p>
<h3 class="subhead"> AN 2.169 </h3>
<p class="bodytext">“There are these two things. What two? Guarding the sense doors and moderation in eating. These are the two things.”</p>
<h3 class="subhead"> AN 2.170 </h3>
<p class="bodytext">“There are these two things. What two? The power of reflection and the power of development. These are the two things.”</p>
<h3 class="subhead"> AN 2.171 </h3>
<p class="bodytext">“There are these two things. What two? The power of mindfulness and the power of immersion. These are the two things.”</p>
<h3 class="subhead"> AN 2.172 </h3>
<p class="bodytext">“There are these two things. What two? Serenity and discernment. These are the two things.”</p>
<h3 class="subhead"> AN 2.173 </h3>
<p class="bodytext">“There are these two things. What two? Failure in ethical conduct and failure in view. These are the two things.”</p>
<h3 class="subhead"> AN 2.174 </h3>
<p class="bodytext">“There are these two things. What two? Accomplishment in ethical conduct and accomplishment in view. These are the two things.”</p>
<h3 class="subhead"> AN 2.175 </h3>
<p class="bodytext">“There are these two things. What two? Purification of ethics and purification of view. These are the two things.”</p>
<h3 class="subhead"> AN 2.176 </h3>
<p class="bodytext">“There are these two things. What two? Purification of view and making an effort in line with that view. These are the two things.”</p>
<h3 class="subhead"> AN 2.177 </h3>
<p class="bodytext">“There are these two things. What two? To never be content with skillful qualities, and to never stop trying. These are the two things.”</p>
<h3 class="subhead"> AN 2.178 </h3>
<p class="bodytext">“There are these two things. What two? Lack of mindfulness and lack of situational awareness. These are the two things.”</p>
<h3 class="subhead"> AN 2.179 </h3>
<p class="bodytext">“There are these two things. What two? Mindfulness and situational awareness. These are the two things.”</p></div>
<h1 class="chapter">180–⁠229. Kodha Peyyāla Vagga</h1>
<div class="chaptxt">
<p class="chaphead">Peyyāla</p>
<p class="title">16. Abbreviated Texts Beginning with Anger</p>
<h3 class="subhead"> AN 2.180 </h3>
<p class="bodytext">“There are these two things. What two? Anger and hostility … offensiveness and contempt … jealousy and stinginess … deceit and deviousness … lack of conscience and prudence. These are the two things.”</p>
<h3 class="subhead"> AN 2.181–185 </h3>
<p class="bodytext">“There are these two things. What two? Freedom from anger and hostility … freedom from offensiveness and contempt … freedom from jealousy and stinginess … freedom from deceit and deviousness … conscience and prudence. These are the two things.”</p>
<h3 class="subhead"> AN 2.186–190 </h3>
<p class="bodytext">“Anyone who has two things lives in suffering. What two? Anger and hostility … offensiveness and contempt … jealousy and stinginess … deceit and deviousness … lack of conscience and prudence. Anyone who has these two things lives in suffering.”</p>
<h3 class="subhead"> AN 2.191–195 </h3>
<p class="bodytext">“Anyone who has these two things lives happily. What two? Freedom from anger and hostility … freedom from offensiveness and contempt … freedom from jealousy and stinginess … freedom from deceit and deviousness … conscience and prudence. Anyone who has these two things lives happily.”</p>
<h3 class="subhead"> AN 2.196–200 </h3>
<p class="bodytext">“These two things lead to the decline of a mendicant trainee. What two? Anger and hostility … offensiveness and contempt … jealousy and stinginess … deceit and deviousness … lack of conscience and prudence. These two things lead to the decline of a mendicant trainee.”</p>
<h3 class="subhead"> AN 2.201–205 </h3>
<p class="bodytext">“These two things don’t lead to the decline of a mendicant trainee. What two? Freedom from anger and hostility … freedom from offensiveness and contempt … freedom from jealousy and stinginess … freedom from deceit and deviousness … conscience and prudence. These two things don’t lead to the decline of a mendicant trainee.”</p>
<h3 class="subhead"> AN 2.206–210 </h3>
<p class="bodytext">“Anyone who has two things is cast down to hell. What two? Anger and hostility … offensiveness and contempt … jealousy and stinginess … deceit and deviousness … lack of conscience and prudence. Anyone who has these two things is cast down to hell.”</p>
<h3 class="subhead"> AN 2.211–215 </h3>
<p class="bodytext">“Anyone who has two things is raised up to heaven. What two? Freedom from anger and hostility … freedom from offensiveness and contempt … freedom from jealousy and stinginess … freedom from deceit and deviousness … conscience and prudence. Anyone who has these two things is raised up to heaven.”</p>
<h3 class="subhead"> AN 2.216–220 </h3>
<p class="bodytext">“When they have two things, some people, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell. What two? Anger and hostility … offensiveness and contempt … jealousy and stinginess … deceit and deviousness … lack of conscience and prudence. When they have two things, some people, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell.</p>
<h3 class="subhead"> AN 2.221–229 </h3>
<p class="bodytext">“When they have two things, some people—when their body breaks up, after death—are reborn in a good place, a heavenly realm. What two? Freedom from anger and hostility … freedom from offensiveness and contempt … freedom from jealousy and stinginess … freedom from deceit and deviousness … conscience and prudence. When they have these two things, some people—when their body breaks up, after death—are reborn in a good place, a heavenly realm.</p></div>
<h1 class="chapter">230–⁠279. Akusala Peyyāla Vagga</h1>
<div class="chaptxt">
<p class="title">17. Abbreviated Texts Beginning with the Unskillful</p>
<h3 class="subhead"> AN 2.230–279 </h3>
<p class="bodytext">“These two things are unskillful … are skillful … are blameworthy … are blameless … have suffering as outcome … have happiness as outcome … result in suffering … result in happiness … are hurtful … are not hurtful. What two? Freedom from anger and hostility … freedom from offensiveness and contempt … freedom from jealousy and stinginess … freedom from deceit and deviousness … conscience and prudence. These are the two things that are not hurtful.”</p></div>
<h1 class="chapter">280–⁠309. Vinaya Peyyāla Vagga</h1>
<div class="chaptxt">
<p class="title">18. Abbreviated Texts Beginning with the Training</p>
<h3 class="subhead"> AN 2.280 </h3>
<p class="bodytext">“For two reasons the Realized One laid down training rules for his disciples.</p>
<p class="bodytext">What two? For the well-being and comfort of the Saṅgha … For keeping difficult persons in check and for the comfort of good-hearted mendicants … For restraining defilements that affect the present life and protecting against defilements that affect lives to come … For restraining threats to the present life and protecting against threats to lives to come … For restraining faults that affect the present life and protecting against faults that affect lives to come … For restraining hazards that affect the present life and protecting against hazards that affect lives to come … For restraining unskillful qualities that affect the present life and protecting against unskillful qualities that affect lives to come … Out of sympathy for laypeople and for breaking up factions of mendicants with wicked desires … For inspiring confidence in those without it, and increasing confidence in those who have it … For the continuation of the true teaching and the support of the training. These are the two reasons why the Realized One laid down training rules for his disciples.”</p>
<h3 class="subhead"> AN 2.281–309 </h3>
<p class="bodytext">“For two reasons the Realized One laid down for his disciples the monastic code … the recitation of the monastic code … the suspension of the recitation of the monastic code … the invitation to admonish … the setting aside of the invitation to admonish … the disciplinary act of censure … placing under dependence … banishment … reconciliation … debarment … probation … being sent back to the beginning … penance … reinstatement … restoration … removal … ordination … an act with a motion … an act with a motion and one announcement … an act with a motion and three announcements … laying down what was not previously laid down … amending what was laid down … the settling of a disciplinary matter in the presence of those concerned … the settling of a disciplinary matter by accurate recollection … the settling of a disciplinary matter due to recovery from madness … the settling of a disciplinary matter due to the acknowledgement of the offense … the settling of a disciplinary matter by the decision of a majority … the settling of a disciplinary matter by a verdict of aggravated misconduct … the settling of a disciplinary matter by covering over with grass.</p>
<p class="bodytext">What two? For the well-being and comfort of the Saṅgha … For keeping difficult persons in check and for the comfort of good-hearted mendicants … For restraining defilements that affect the present life and protecting against defilements that affect lives to come … For restraining threats to the present life and protecting against threats to lives to come … For restraining faults that affect the present life and protecting against faults that affect lives to come … For restraining hazards that affect the present life and protecting against hazards that affect lives to come … For restraining unskillful qualities that affect the present life and protecting against unskillful qualities that affect lives to come … Out of sympathy for laypeople and for breaking up factions of mendicants with wicked desires … For inspiring confidence in those without it, and increasing confidence in those who have it … For the continuation of the true teaching and the support of the training.</p>
<p class="bodytext">These are the two reasons why the Realized One laid down the settlement of a disciplinary matter by covering over with grass for his disciples.”</p></div>
<h1 class="chapter">310–⁠479. Rāga Peyyāla Vagga</h1>
<div class="chaptxt">
<p class="title">19. Abbreviated Texts Beginning with Greed</p>
<h3 class="subhead"> AN 2.310–321 </h3>
<p class="bodytext">“For insight into greed, two things should be developed. What two? Serenity and discernment. For insight into greed, these two things should be developed.”</p>
<p class="bodytext">“For the complete understanding … finishing … giving up … ending … vanishing … fading away … cessation … giving away … letting go of greed, two things should be developed.”</p>
<h3 class="subhead"> AN 2.322–479 </h3>
<p class="bodytext">“Of hate … delusion … anger … hostility … offensiveness … contempt … jealousy … stinginess … deceit … deviousness … obstinacy … aggression … conceit … arrogance … vanity … negligence … for insight … complete understanding … finishing … giving up … ending … vanishing … fading away … cessation … giving away … letting go … two things should be developed. What two? Serenity and discernment. For the letting go of negligence, these two things should be developed.”</p>
<p class="bodytext">That is what the Buddha said. Satisfied, the mendicants were happy with what the Buddha said.</p>
<p class="centered">The Book of the Twos is finished.</p></div>
<div end="ed" class="end"></div>`

document.getElementById('loaddata').innerHTML = mulaen_2_4_2 
searchhelper()
bookhelper()
var chapterhelper = document.createElement('script')
chapterhelper.src = `chaptertoggle.js`
document.head.appendChild(chapterhelper)