var mulaen_2_4_1 = `
<div id="table_main">
<div id="table_name">Table of contents</div></div>
<p class="namo">॥ Namo tassa bhagavato arahato sammāsambuddhassa ॥</p>
<p class="bookname"> 1. Ekakanipāta</p>
<p class="author">Translated by Bhikkhu Sujato</p>
<p class="centered">Numbered Discourses 1</p>
<h1 class="chapter">1–⁠10. Cittapariyādāna Vagga</h1>
<div class="chaptxt">
<p class="title">1. Sights, Etc.</p>
<h3 class="subhead"> AN 1.1 </h3>
<p class="bodytext"> So I have heard.  At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery. There the Buddha addressed the mendicants, “Mendicants!”</p>
<p class="bodytext">“Venerable sir,” they replied. The Buddha said this:</p>
<p class="bodytext">“Mendicants, I do not see a single sight that occupies a man’s mind like the sight of a woman. The sight of a woman occupies a man’s mind.”</p>
<h3 class="subhead"> AN 1.2 </h3>
<p class="bodytext">“Mendicants, I do not see a single sound that occupies a man’s mind like the sound of a woman. The sound of a woman occupies a man’s mind.”</p>
<h3 class="subhead"> AN 1.3 </h3>
<p class="bodytext">“Mendicants, I do not see a single smell that occupies a man’s mind like the smell of a woman. The smell of a woman occupies a man’s mind.”</p>
<h3 class="subhead"> AN 1.4 </h3>
<p class="bodytext">“Mendicants, I do not see a single taste that occupies a man’s mind like the taste of a woman. The taste of a woman occupies a man’s mind.”</p>
<h3 class="subhead"> AN 1.5 </h3>
<p class="bodytext">“Mendicants, I do not see a single touch that occupies a man’s mind like the touch of a woman. The touch of a woman occupies a man’s mind.”</p>
<h3 class="subhead"> AN 1.6 </h3>
<p class="bodytext">“Mendicants, I do not see a single sight that occupies a woman’s mind like the sight of a man. The sight of a man occupies a woman’s mind.”</p>
<h3 class="subhead"> AN 1.7 </h3>
<p class="bodytext">“Mendicants, I do not see a single sound that occupies a woman’s mind like the sound of a man. The sound of a man occupies a woman’s mind.”</p>
<h3 class="subhead"> AN 1.8 </h3>
<p class="bodytext">“Mendicants, I do not see a single smell that occupies a woman’s mind like the smell of a man. The smell of a man occupies a woman’s mind.”</p>
<h3 class="subhead"> AN 1.9 </h3>
<p class="bodytext">“Mendicants, I do not see a single taste that occupies a woman’s mind like the taste of a man. The taste of a man occupies a woman’s mind.”</p>
<h3 class="subhead"> AN 1.10 </h3>
<p class="bodytext">“Mendicants, I do not see a single touch that occupies a woman’s mind like the touch of a man. The touch of a man occupies a woman’s mind.”</p></div>
<h1 class="chapter">11–⁠20. Nīvaraṇappahāṇa Vagga</h1>
<div class="chaptxt">
<p class="title">2. Giving Up the Hindrances</p>
<h3 class="subhead"> AN 1.11 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to sensual desire, or, when it has arisen, makes it increase and grow like the feature of beauty. When you attend improperly to the feature of beauty, sensual desire arises, and once arisen it increases and grows.”</p>
<h3 class="subhead"> AN 1.12 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to ill will, or, when it has arisen, makes it increase and grow like the feature of harshness. When you attend improperly to the feature of harshness, ill will arises, and once arisen it increases and grows.”</p>
<h3 class="subhead"> AN 1.13 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to dullness and drowsiness, or, when they have arisen, makes them increase and grow like discontent, sloth, yawning, sleepiness after eating, and mental sluggishness. When you have a sluggish mind, dullness and drowsiness arise, and once arisen they increase and grow.”</p>
<h3 class="subhead"> AN 1.14 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to restlessness and remorse, or, when they have arisen, makes them increase and grow like an unsettled mind. When you have no peace of mind, restlessness and remorse arise, and once arisen they increase and grow.”</p>
<h3 class="subhead"> AN 1.15 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to doubt, or, when it has arisen, makes it increase and grow like improper attention. When you attend improperly, doubt arises, and once arisen it increases and grows.”</p>
<h3 class="subhead"> AN 1.16 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that prevents sensual desire from arising, or, when it has arisen, abandons it like the feature of ugliness. When you attend properly to the feature of ugliness, sensual desire does not arise, or, if it has already arisen, it’s given up.”</p>
<h3 class="subhead"> AN 1.17 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that prevents ill will from arising, or, when it has arisen, abandons it like the heart’s release by love. When you attend properly on the heart’s release by love, ill will does not arise, or, if it has already arisen, it’s given up.”</p>
<h3 class="subhead"> AN 1.18 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that prevents dullness and drowsiness from arising, or, when they have arisen, gives them up like the elements of initiative, persistence, and vigor. When you’re energetic, dullness and drowsiness do not arise, or, if they’ve already arisen, they’re given up.”</p>
<h3 class="subhead"> AN 1.19 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that prevents restlessness and remorse from arising, or, when they have arisen, gives them up like peace of mind. When your mind is peaceful, restlessness and remorse do not arise, or, if they’ve already arisen, they’re given up.”</p>
<h3 class="subhead"> AN 1.20 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that prevents doubt from arising, or, when it has arisen, gives it up like proper attention. When you attend properly, doubt does not arise, or, if it’s already arisen, it’s given up.”</p></div>
<h1 class="chapter">21–⁠30. Akammaniya Vagga</h1>
<div class="chaptxt">
<p class="title">3. Useless</p>
<h3 class="subhead"> AN 1.21 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not developed like this, is as useless as the mind. An undeveloped mind is useless.”</p>
<h3 class="subhead"> AN 1.22 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is developed like this, is as workable as the mind. A developed mind is workable.”</p>
<h3 class="subhead"> AN 1.23 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not developed like this, is so very harmful as the mind. An undeveloped mind is very harmful.”</p>
<h3 class="subhead"> AN 1.24 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is developed like this, is so very beneficial as the mind. A developed mind is very beneficial.”</p>
<h3 class="subhead"> AN 1.25 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not developed, with such untapped potential, is so very harmful as the mind. An undeveloped mind, with untapped potential, is very harmful.”</p>
<h3 class="subhead"> AN 1.26 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is developed, with its potential realized, is so very beneficial as the mind. A developed mind, with its potential realized, is very beneficial.”</p>
<h3 class="subhead"> AN 1.27 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not developed and cultivated, is so very harmful as the mind. An undeveloped and uncultivated mind is very harmful.”</p>
<h3 class="subhead"> AN 1.28 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is developed and cultivated, is so very beneficial as the mind. A developed and cultivated mind is very beneficial.”</p>
<h3 class="subhead"> AN 1.29 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not developed and cultivated, brings such suffering as the mind. An undeveloped and uncultivated mind brings suffering.”</p>
<h3 class="subhead"> AN 1.30 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is developed and cultivated, brings such happiness as the mind. A developed and cultivated mind brings happiness.”</p></div>
<h1 class="chapter">31–⁠40. Adanta Vagga</h1>
<div class="chaptxt">
<p class="title">4. Wild</p>
<h3 class="subhead"> AN 1.31 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not tamed, is so very harmful as the mind. A wild mind is very harmful.”</p>
<h3 class="subhead"> AN 1.32 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is tamed, is so very beneficial as the mind. A tamed mind is very beneficial.”</p>
<h3 class="subhead"> AN 1.33 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not guarded, is so very harmful as the mind. An unguarded mind is very harmful.”</p>
<h3 class="subhead"> AN 1.34 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is guarded, is so very beneficial as the mind. A guarded mind is very beneficial.”</p>
<h3 class="subhead"> AN 1.35 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not protected, is so very harmful as the mind. An unprotected mind is very harmful.”</p>
<h3 class="subhead"> AN 1.36 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is protected, is so very beneficial as the mind. A protected mind is very beneficial.”</p>
<h3 class="subhead"> AN 1.37 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it’s not restrained, is so very harmful as the mind. An unrestrained mind is very harmful.”</p>
<h3 class="subhead"> AN 1.38 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is restrained, is so very beneficial as the mind. A restrained mind is very beneficial.”</p>
<h3 class="subhead"> AN 1.39 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is not tamed, guarded, protected, and restrained, is so very harmful as the mind. An untamed, unguarded, unprotected, and unrestrained mind is very harmful.”</p>
<h3 class="subhead"> AN 1.40 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that, when it is tamed, guarded, protected, and restrained, is so very beneficial as the mind. A tamed, guarded, protected, and restrained mind is very beneficial.”</p></div>
<h1 class="chapter">41–⁠50. Paṇihitaaccha Vagga</h1>
<div class="chaptxt">
<p class="title">5. A Spike</p>
<h3 class="subhead"> AN 1.41 </h3>
<p class="bodytext">“Mendicants, suppose a spike of rice or barley was pointing the wrong way. If you trod on it with hand or foot, there’s no way it could break the skin and produce blood. Why is that? Because the spike is pointing the wrong way. In the same way, a mendicant whose mind is pointing the wrong way cannot break ignorance, produce knowledge, and realize extinguishment. Why is that? Because their mind is pointing the wrong way.”</p>
<h3 class="subhead"> AN 1.42 </h3>
<p class="bodytext">“Mendicants, suppose a spike of rice or barley was pointing the right way. If you trod on it with hand or foot, it may well break the skin and produce blood. Why is that? Because the spike is pointing the right way. In the same way, a mendicant whose mind is pointing the right way can break ignorance, produce knowledge, and realize extinguishment. Why is that? Because the mind is pointing the right way.”</p>
<h3 class="subhead"> AN 1.43 </h3>
<p class="bodytext">“Mendicants, when I’ve comprehended the mind of a person whose mind is corrupted, I understand: ‘If this person were to die right now, they would be cast down to hell.’ Why is that? Because their mind is corrupted. Depravity of mind is the reason why some sentient beings, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell.”</p>
<h3 class="subhead"> AN 1.44 </h3>
<p class="bodytext">“Mendicants, when I’ve comprehended the mind of a person whose mind is confident, I understand: ‘If this person were to die right now, they would be raised up to heaven.’ Why is that? Because their mind is clear. Clarity of mind is the reason why some sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.”</p>
<h3 class="subhead"> AN 1.45 </h3>
<p class="bodytext">“Suppose, mendicants, there was a lake that was cloudy, murky, and muddy. A person with good eyesight standing on the bank would not see the mussel shells, gravel and pebbles, and schools of fish swimming about or staying still. Why is that? Because the water is clouded. In the same way, that a mendicant whose mind is clouded would know what’s for their own good, the good of another, or the good of both; or that they would realize any superhuman distinction in knowledge and vision worthy of the noble ones: this is not possible. Why is that? Because their mind is clouded.”</p>
<h3 class="subhead"> AN 1.46 </h3>
<p class="bodytext">“Suppose, mendicants, there was a lake that was transparent, clear, and unclouded. A person with good eyesight standing on the bank would see the mussel shells, gravel and pebbles, and schools of fish swimming about or staying still. Why is that? Because the water is unclouded. In the same way, that a mendicant whose mind is not clouded would know what’s for their own good, the good of another, or the good of both; or that they would realize any superhuman distinction in knowledge and vision worthy of the noble ones: this is possible. Why is that? Because their mind is unclouded.”</p>
<h3 class="subhead"> AN 1.47 </h3>
<p class="bodytext">“Just as, mendicants, the <i>papra</i>is said to be the best kind of tree in terms of its pliability and workability, so too, I do not see a single thing that’s as pliable and workable as the mind, when it is developed and cultivated. A mind that is developed and cultivated is pliable and workable.”</p>
<h3 class="subhead"> AN 1.48 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that’s as quick to change as the mind. So much so that it’s not easy to give a simile for how quickly the mind changes.”</p>
<h3 class="subhead"> AN 1.49 </h3>
<p class="bodytext">“This mind, mendicants, is radiant. But it’s corrupted by passing corruptions.”</p>
<h3 class="subhead"> AN 1.50 </h3>
<p class="bodytext">“This mind, mendicants, is radiant. And it is freed from passing corruptions.”</p></div>
<h1 class="chapter">51–⁠60. Accharāsaṅghāta Vagga</h1>
<div class="chaptxt">
<p class="title">6. Finger Snap</p>
<h3 class="subhead"> AN 1.51 </h3>
<p class="bodytext">“This mind, mendicants, is radiant. But it is corrupted by passing corruptions. An uneducated ordinary person does not truly understand this. So I say that the uneducated ordinary person has no development of the mind.”</p>
<h3 class="subhead"> AN 1.52 </h3>
<p class="bodytext">“This mind, mendicants, is radiant. And it is freed from passing corruptions. An educated noble disciple truly understands this. So I say that the educated noble disciple has development of the mind.”</p>
<h3 class="subhead"> AN 1.53 </h3>
<p class="bodytext">“If, mendicants, a mendicant cultivates a mind of love even as long as a finger snap, they’re called a mendicant who does not lack absorption, who follows the Teacher’s instructions, who responds to advice, and who does not eat the country’s alms in vain. How much more so those who make much of it!”</p>
<h3 class="subhead"> AN 1.54 </h3>
<p class="bodytext">“If, mendicants, a mendicant develops a mind of love even as long as a finger snap, they’re called a mendicant who does not lack absorption, who follows the Teacher’s instructions, who responds to advice, and who does not eat the country’s alms in vain. How much more so those who make much of it!”</p>
<h3 class="subhead"> AN 1.55 </h3>
<p class="bodytext">“If, mendicants, a mendicant focuses on a mind of love even as long as a finger snap, they’re called a mendicant who does not lack absorption, who follows the Teacher’s instructions, who responds to advice, and who does not eat the country’s alms in vain. How much more so those who make much of it!”</p>
<h3 class="subhead"> AN 1.56 </h3>
<p class="bodytext">“Mendicants, whatever qualities are unskillful, part of the unskillful, on the side of the unskillful, all of them are preceded by the mind. Mind arises first, and unskillful qualities follow right behind.”</p>
<h3 class="subhead"> AN 1.57 </h3>
<p class="bodytext">“Mendicants, whatever qualities are skillful, part of the skillful, on the side of the skillful, all of them are preceded by the mind. Mind arises first, and skillful qualities follow right behind.”</p>
<h3 class="subhead"> AN 1.58 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like negligence. When you’re negligent, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.59 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like diligence. When you’re diligent, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.60 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like laziness. When you’re lazy, unskillful qualities arise and skillful qualities decline.”</p></div>
<h1 class="chapter">61-70. Vīriyārambhādi Vagga</h1>
<div class="chaptxt">
<p class="title">7. Arousing Energy</p>
<h3 class="subhead"> AN 1.61 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like arousing energy. When you’re energetic, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.62 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like having many wishes. When you have many wishes, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.63 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like having few wishes. When you have few wishes, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.64 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like lack of contentment. When you lack contentment, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.65 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like contentment. When you’re contented, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.66 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like improper attention. When you attend improperly, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.67 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like proper attention. When you attend properly, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.68 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like lack of situational awareness. When you lack situational awareness, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.69 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like situational awareness. When you have situational awareness, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.70 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like bad friends. When you have bad friends, unskillful qualities arise and skillful qualities decline.”</p></div>
<h1 class="chapter">71–⁠81. Kalyāṇamittādi Vagga</h1>
<div class="chaptxt">
<p class="title">8. Good Friends</p>
<h3 class="subhead"> AN 1.71 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like good friends. When you have good friends, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.72 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like pursuing bad habits and not good habits. When you pursue bad habits and not good habits, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.73 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like pursuing good habits and not bad habits. When you pursue good habits and not bad habits, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.74 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that prevents the awakening factors from arising, or, if they’ve already arisen, prevents them from being fully developed like improper attention. When you attend improperly, the awakening factors don’t arise, or, if they’ve already arisen, they’re not fully developed.”</p>
<h3 class="subhead"> AN 1.75 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to the awakening factors, or, if they’ve already arisen, fully develops them like proper attention. When you attend properly, the awakening factors arise, or, if they’ve already arisen, they’re fully developed.”</p>
<h3 class="subhead"> AN 1.76 </h3>
<p class="bodytext">“Loss of relatives, mendicants, is a small thing. Wisdom is the worst thing to lose.”</p>
<h3 class="subhead"> AN 1.77 </h3>
<p class="bodytext">“Growth of relatives, mendicants, is a small thing. Wisdom is the best thing to grow.</p>
<p class="bodytext">So you should train like this: ‘We will grow in wisdom.’ That’s how you should train.”</p>
<h3 class="subhead"> AN 1.78 </h3>
<p class="bodytext">“Loss of wealth, mendicants, is a small thing. Wisdom is the worst thing to lose.”</p>
<h3 class="subhead"> AN 1.79 </h3>
<p class="bodytext">“Growth of wealth, mendicants, is a small thing. Wisdom is the best thing to grow.</p>
<p class="bodytext">So you should train like this: ‘We will grow in wisdom.’ That’s how you should train.”</p>
<h3 class="subhead"> AN 1.80 </h3>
<p class="bodytext">“Loss of fame, mendicants, is a small thing. Wisdom is the worst thing to lose.”</p>
<h3 class="subhead"> AN 1.81 </h3>
<p class="bodytext">“Growth of fame, mendicants, is a small thing. Wisdom is the best thing to grow.</p>
<p class="bodytext">So you should train like this: ‘We will grow in wisdom.’ That’s how you should train.”</p></div>
<h1 class="chapter">82–⁠97. Pamādādi Vagga</h1>
<div class="chaptxt">
<p class="title">9. Negligence</p>
<h3 class="subhead"> AN 1.82 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as negligence. Negligence is very harmful.”</p>
<h3 class="subhead"> AN 1.83 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as diligence. Diligence is very beneficial.”</p>
<h3 class="subhead"> AN 1.84 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as laziness. Laziness is very harmful.”</p>
<h3 class="subhead"> AN 1.85 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as arousing energy. Arousing energy is very beneficial.”</p>
<h3 class="subhead"> AN 1.86 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as having many wishes. Having many wishes is very harmful.”</p>
<h3 class="subhead"> AN 1.87 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as having few wishes. Having few wishes is very beneficial.”</p>
<h3 class="subhead"> AN 1.88 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as lack of contentment. Lack of contentment is very harmful.”</p>
<h3 class="subhead"> AN 1.89 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as contentment. Contentment is very beneficial.”</p>
<h3 class="subhead"> AN 1.90 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as improper attention. Improper attention is very harmful.”</p>
<h3 class="subhead"> AN 1.91 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as proper attention. Proper attention is very beneficial.”</p>
<h3 class="subhead"> AN 1.92 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as lack of situational awareness. Lack of situational awareness is very harmful.”</p>
<h3 class="subhead"> AN 1.93 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as situational awareness. Situational awareness is very beneficial.”</p>
<h3 class="subhead"> AN 1.94 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as bad friends. Bad friends are very harmful.”</p>
<h3 class="subhead"> AN 1.95 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as good friends. Good friends are very beneficial.”</p>
<h3 class="subhead"> AN 1.96 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very harmful as pursuing bad habits and not good habits. Pursuing bad habits and not good habits is very harmful.”</p>
<h3 class="subhead"> AN 1.97 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very beneficial as pursuing good habits and not bad habits. Pursuing good habits and not bad habits is very beneficial.”</p></div>
<h1 class="chapter">98–⁠139. Dutiyapamādādi Vagga</h1>
<div class="chaptxt">
<p class="title">10. Negligence (2nd)</p>
<h3 class="subhead"> AN 1.98 </h3>
<p class="bodytext">“Taking into account interior factors, mendicants, I do not see a single one that is so very harmful as negligence. Negligence is very harmful.”</p>
<h3 class="subhead"> AN 1.99 </h3>
<p class="bodytext">“Taking into account interior factors, mendicants, I do not see a single one that is so very beneficial as diligence. Diligence is very beneficial.”</p>
<h3 class="subhead"> AN 1.100 </h3>
<p class="bodytext">“Taking into account interior factors, mendicants, I do not see a single one that is so very harmful as laziness. Laziness is very harmful.”</p>
<h3 class="subhead"> AN 1.101 </h3>
<p class="bodytext">“Taking into account interior factors, mendicants, I do not see a single one that is so very beneficial as arousing energy. Arousing energy is very beneficial.”</p>
<h3 class="subhead"> AN 1.102–109 </h3>
<p class="bodytext">“Taking into account interior factors, mendicants, I do not see a single one that is so very harmful as having many wishes … having few wishes … lack of contentment … contentment … improper attention … proper attention … lack of situational awareness … situational awareness …”</p>
<h3 class="subhead"> AN 1.110 </h3>
<p class="bodytext">“Taking into account exterior factors, mendicants, I do not see a single one that is so very harmful as bad friends. Bad friends are very harmful.”</p>
<h3 class="subhead"> AN 1.111 </h3>
<p class="bodytext">“Taking into account exterior factors, mendicants, I do not see a single one that is so very beneficial as good friends. Good friends are very beneficial.”</p>
<h3 class="subhead"> AN 1.112 </h3>
<p class="bodytext">“Taking into account interior factors, mendicants, I do not see a single one that is so very harmful as pursuing bad habits and not good habits. Pursuing bad habits and not good habits is very harmful.”</p>
<h3 class="subhead"> AN 1.113 </h3>
<p class="bodytext">“Taking into account interior factors, mendicants, I do not see a single one that is so very beneficial as pursuing good habits and not bad habits. Pursuing good habits and not bad habits is very beneficial.”</p>
<h3 class="subhead"> AN 1.114 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that leads to the decline and disappearance of the true teaching like negligence. Negligence leads to the decline and disappearance of the true teaching.”</p>
<h3 class="subhead"> AN 1.115 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that leads to the continuation, persistence, and enduring of the true teaching like diligence. Diligence leads to the continuation, persistence, and enduring of the true teaching.”</p>
<h3 class="subhead"> AN 1.116 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that leads to the decline and disappearance of the true teaching like laziness. Laziness leads to the decline and disappearance of the true teaching.”</p>
<h3 class="subhead"> AN 1.117 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that leads to the continuation, persistence, and enduring of the true teaching like arousing energy. Arousing energy leads to the continuation, persistence, and enduring of the true teaching.”</p>
<h3 class="subhead"> AN 1.118–128 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that leads to the decline and disappearance of the true teaching like having many wishes … having few wishes … lack of contentment … contentment … improper attention … proper attention … lack of situational awareness … situational awareness … bad friends … good friends … pursuing bad habits and not good habits. Pursuing bad habits and not good habits leads to the decline and disappearance of the true teaching.”</p>
<h3 class="subhead"> AN 1.129 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that leads to the continuation, persistence, and enduring of the true teaching like pursuing good habits and not bad habits. Pursuing good habits and not bad habits leads to the continuation, persistence, and enduring of the true teaching”</p>
<h3 class="subhead"> AN 1.130 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain what is not the teaching as the teaching are acting for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans. They make much bad karma and make the true teaching disappear.”</p>
<h3 class="subhead"> AN 1.131 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain what is the teaching as not the teaching are acting for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans. They make much bad karma and make the true teaching disappear.”</p>
<h3 class="subhead"> AN 1.132–139 </h3>
<p class="bodytext">“Those mendicants who explain what is not found in the texts on monastic training as found in those texts … what is found in the texts on monastic training as not found in those texts … what was not spoken and stated by the Realized One as spoken and stated by the Realized One … what was spoken and stated by the Realized One as not spoken and stated by the Realized One … what was not practiced by the Realized One as practiced by the Realized One … what was practiced by the Realized One as not practiced by the Realized One … what was not prescribed by the Realized One as prescribed by the Realized One … what was prescribed by the Realized One as not prescribed by the Realized One are acting for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans. They make much bad karma and make the true teaching disappear.”</p></div>
<h1 class="chapter">140–⁠149. Adhamma Vagga</h1>
<div class="chaptxt">
<p class="title">11. Not the Teaching</p>
<h3 class="subhead"> AN 1.140 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain what is not the teaching as not the teaching are acting for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans. They make much merit and make the true teaching continue.”</p>
<h3 class="subhead"> AN 1.141 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain what is the teaching as the teaching are acting for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans. They make much merit and make the true teaching continue.”</p>
<h3 class="subhead"> AN 1.142–149 </h3>
<p class="bodytext">“Those mendicants who explain what is not found in the texts on monastic training as not found in the texts on monastic training … what is found in the texts on monastic training as found in the texts on monastic training … what was not spoken and stated by the Realized One as not spoken and stated by the Realized One … what was spoken and stated by the Realized One as spoken and stated by the Realized One … what was not practiced by the Realized One as not practiced by the Realized One … what was practiced by the Realized One as practiced by the Realized One … what was not prescribed by the Realized One as not prescribed by the Realized One … what was prescribed by the Realized One as prescribed by the Realized One … are acting for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans. They make much merit and make the true teaching continue.”</p></div>
<h1 class="chapter">150–⁠169. Anāpatti Vagga</h1>
<div class="chaptxt">
<p class="title">12. Non-offense</p>
<h3 class="subhead"> AN 1.150 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain non-offense as an offense are acting for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans. They make much bad karma and make the true teaching disappear.”</p>
<h3 class="subhead"> AN 1.151 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain an offense as non-offense are acting for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans. Those mendicants make much bad karma and make the true teaching disappear.”</p>
<h3 class="subhead"> AN 1.152–159 </h3>
<p class="bodytext">“Those mendicants who explain a light offense as a serious offense … a serious offense as a light offense … an offense committed with corrupt intention as an offense not committed with corrupt intention … an offense not committed with corrupt intention as an offense committed with corrupt intention … an offense requiring rehabilitation as an offense not requiring rehabilitation … an offense not requiring rehabilitation as an offense requiring rehabilitation … an offense with redress as an offense without redress … an offense without redress as an offense with redress are acting for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans. Those mendicants make much bad karma and make the true teaching disappear.”</p>
<h3 class="subhead"> AN 1.160 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain non-offense as non-offense are acting for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans. They make much merit and make the true teaching continue.”</p>
<h3 class="subhead"> AN 1.161 </h3>
<p class="bodytext">“Mendicants, those mendicants who explain an offense as an offense are acting for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans. They make much merit and make the true teaching continue.”</p>
<h3 class="subhead"> AN 1.162–169 </h3>
<p class="bodytext">“Those mendicants who explain a light offense as a light offense … a serious offense as a serious offense … an offense committed with corrupt intention as an offense committed with corrupt intention … an offense not committed with corrupt intention as an offense not committed with corrupt intention … an offense requiring rehabilitation as an offense requiring rehabilitation … an offense not requiring rehabilitation as an offense not requiring rehabilitation … an offense with redress as an offense with redress … an offense without redress as an offense without redress are acting for the welfare and happiness of the people, for the benefit, welfare, and happiness of the people, of gods and humans. They make much merit and make the true teaching continue.”</p></div>
<h1 class="chapter">170–⁠187. Ekapuggala Vagga</h1>
<div class="chaptxt">
<p class="title">13. One Person</p>
<h3 class="subhead"> AN 1.170 </h3>
<p class="bodytext">“One person, mendicants, arises in the world for the welfare and happiness of the people, out of compassion for the world, for the benefit, welfare, and happiness of gods and humans. What one person? The Realized One, the perfected one, the fully awakened Buddha. This is the one person, mendicants, who arises in the world for the welfare and happiness of the people, out of compassion for the world, for the benefit, welfare, and happiness of gods and humans.”</p>
<h3 class="subhead"> AN 1.171 </h3>
<p class="bodytext">“The appearance of one person, mendicants, is rare in the world. What one person? The Realized One, the perfected one, the fully awakened Buddha. This is the one person, mendicants, whose appearance is rare in the world.”</p>
<h3 class="subhead"> AN 1.172 </h3>
<p class="bodytext">“One person, mendicants, arises in the world who is an incredible human being. What one person? The Realized One, the perfected one, the fully awakened Buddha. This is the one person, mendicants, who arises in the world who is an incredible human being.”</p>
<h3 class="subhead"> AN 1.173 </h3>
<p class="bodytext">“The death of one person, mendicants, is regretted by many people. What one person? The Realized One, the perfected one, the fully awakened Buddha. This is the one person, mendicants, whose death is regretted by many people.”</p>
<h3 class="subhead"> AN 1.174 </h3>
<p class="bodytext">“One person, mendicants, arises in the world unique, without peer or counterpart, incomparable, matchless, unrivaled, unequaled, without equal, the best of bipeds. What one person? The Realized One, the perfected one, the fully awakened Buddha. This is the one person, mendicants, who arises in the world unique, without peer or counterpart, incomparable, matchless, unrivaled, unequaled, without equal, the best of bipeds.”</p>
<h3 class="subhead"> AN 1.175–186 </h3>
<p class="bodytext">“With the appearance of one person, mendicants, there is the appearance of a great eye, a great light, a great radiance, and the six unsurpassable things; the realization of the four kinds of textual analysis; the penetration of many and diverse elements; the realization of the fruit of knowledge and freedom; the realization of the fruits of stream-entry, once-return, non-return, and perfection. What one person? The Realized One, the perfected one, the fully awakened Buddha. This is the one person whose appearance brings the appearance of a great eye, a great light, a great radiance, and the six unsurpassable things; the realization of the four kinds of textual analysis; the penetration of many and diverse elements; the realization of the fruit of knowledge and release; the realization of the fruits of stream-entry, once-return, non-return, and perfection.”</p>
<h3 class="subhead"> AN 1.187 </h3>
<p class="bodytext">“Mendicants, I do not see a single other person who rightly keeps rolling the supreme Wheel of Dhamma that was rolled forth by the Realized One like Sāriputta. Sāriputta rightly keeps rolling the supreme Wheel of Dhamma that was rolled forth by the Realized One.”</p></div>
<h1 class="chapter">188-267. Etadagga Vagga</h1><div class="chaptxt">
<p class="title">14. First</p>
<h3 class="subhead"> AN 1.188–197 </h3>
<p class="bodytext">“The foremost of my monk disciples in seniority is Aññākoṇḍañña.</p>
<p class="bodytext">… with great wisdom is Sāriputta.</p>
<p class="bodytext">… with psychic power is Mahāmoggallāna.</p>
<p class="bodytext">… who advocate austerities is Mahākassapa.</p>
<p class="bodytext">… with clairvoyance is Anuruddha.</p>
<p class="bodytext">… from eminent families is Bhaddiya Kāḷigodhāyaputta.</p>
<p class="bodytext">… with a charming voice is Lakuṇṭaka Bhaddiya.</p>
<p class="bodytext">… with a lion’s roar is Piṇḍolabhāradvāja.</p>
<p class="bodytext">… who speak on the teaching is Puṇṇa Mantāṇiputta.</p>
<p class="bodytext">… who explain in detail the meaning of a brief statement is Mahākaccāna.”</p>
<p class="title">15. Second</p>
<h3 class="subhead"> AN 1.198–208 </h3>
<p class="bodytext">“The foremost of my monk disciples in creating a mind-made body is Cūḷapanthaka.</p>
<p class="bodytext">… who are skilled in the evolution of consciousness is Cūḷapanthaka.</p>
<p class="bodytext">… who are skilled in the evolution of perception is Mahāpanthaka.</p>
<p class="bodytext">… who live without conflict is Subhūti.</p>
<p class="bodytext">… who are worthy of a religious donation is Subhūti.</p>
<p class="bodytext">… who stay in the wilderness is Revata of the Acacia Wood.</p>
<p class="bodytext">… who practice absorption is Kaṅkhārevata.</p>
<p class="bodytext">… who are energetic is Soṇa Koḷivisa.</p>
<p class="bodytext">… who are good speakers is Soṇa Kuṭikaṇṇa.</p>
<p class="bodytext">… who receive many possessions is Sīvali.</p>
<p class="bodytext">… who are strong in faith is Vakkalī.”</p>
<p class="title">16. Third</p>
<h3 class="subhead"> AN 1.209–218 </h3>
<p class="bodytext">“The foremost of my monk disciples who want to train is Rāhula.</p>
<p class="bodytext">… who went forth out of faith is Raṭṭhapāla.</p>
<p class="bodytext">… who are the first to pick up a ballot slip is Kuṇḍadhāna.</p>
<p class="bodytext">… who are eloquent poets is Vaṅgīsa.</p>
<p class="bodytext">… who are impressive all around is Upasena Vaṅgantaputta.</p>
<p class="bodytext">… who assign lodgings is Dabba Mallaputta.</p>
<p class="bodytext">… who are beloved of the deities is Pilindavaccha.</p>
<p class="bodytext">… with swift insight is Bāhiya Dārucīriya.</p>
<p class="bodytext">… with brilliant speech is Kassapa the Prince.</p>
<p class="bodytext">… who have attained the methods of textual analysis is Mahākoṭṭhita.”</p>
<p class="title">17. Fourth</p>
<h3 class="subhead"> AN 1.219–234 </h3>
<p class="bodytext">“The foremost of my monk disciples who are very learned is Ānanda.</p>
<p class="bodytext">… with a good memory is Ānanda.</p>
<p class="bodytext">… with an extensive range is Ānanda.</p>
<p class="bodytext">… in retention is Ānanda.</p>
<p class="bodytext">… as a personal attendant is Ānanda.</p>
<p class="bodytext">… with a large congregation is Uruvelakassapa.</p>
<p class="bodytext">… who inspire lay families is Kāḷudāyī.</p>
<p class="bodytext">… with good health is Bakkula.</p>
<p class="bodytext">… who recollect past lives is Sobhita.</p>
<p class="bodytext">… who have memorized the texts on monastic training is Upāli.</p>
<p class="bodytext">… who advise the nuns is Nandaka.</p>
<p class="bodytext">… who guard the sense doors is Nanda.</p>
<p class="bodytext">… who advise the monks is Mahākappina.</p>
<p class="bodytext">… who are skilled in the fire element is Sāgata.</p>
<p class="bodytext">… who inspire eloquent teachings is Rādha.</p>
<p class="bodytext">… who wear coarse robes is Mogharāja.”</p>
<p class="title">18. Fifth</p>
<h3 class="subhead"> AN 1.235–247 </h3>
<p class="bodytext">“The foremost of my nun disciples in seniority is Mahāpajāpatī Gotamī.</p>
<p class="bodytext">… with great wisdom is Khemā.</p>
<p class="bodytext">… with psychic power is Uppalavaṇṇā.</p>
<p class="bodytext">… who have memorized the texts on monastic training is Paṭācārā.</p>
<p class="bodytext">… who speak on the teaching is Dhammadinnā.</p>
<p class="bodytext">… who practice absorption is Nandā.</p>
<p class="bodytext">… who are energetic is Soṇā.</p>
<p class="bodytext">… with clairvoyance is Sakulā.</p>
<p class="bodytext">… with swift insight is Bhaddā Kuṇḍalakesā.</p>
<p class="bodytext">… who recollect past lives is Bhaddā Kāpilānī.</p>
<p class="bodytext">… who have attained great insight is Bhaddakaccānā.</p>
<p class="bodytext">… who wear coarse robes is Kisāgotamī.</p>
<p class="bodytext">… who are strong in faith is Siṅgālakamātā.”</p>
<p class="title">19. Sixth</p>
<h3 class="subhead"> AN 1.248–257 </h3>
<p class="bodytext">“The foremost of my laymen in first going for refuge are the merchants Tapussa and Bhallika.</p>
<p class="bodytext">… as a donor is the householder Sudatta Anāthapiṇḍika.</p>
<p class="bodytext">… who speak on the teaching is the householder Citta Macchikāsaṇḍika.</p>
<p class="bodytext">… who attract a congregation by the four ways of being inclusive is Hatthaka Āḷavaka.</p>
<p class="bodytext">… who donate fine things is Mahānāma Sakka.</p>
<p class="bodytext">… who donate nice things is the householder Ugga of Vesālī.</p>
<p class="bodytext">… who attend on the Saṅgha is the householder Uggata of Hatthi Village.</p>
<p class="bodytext">… who have experiential confidence is Sūrambaṭṭha.</p>
<p class="bodytext">… who have confidence in a person is Jīvaka Komārabhacca.</p>
<p class="bodytext">… who are intimate is the householder Nakula’s father.”</p>
<p class="title">20. Seventh</p>
<h3 class="subhead"> AN 1.258–267 </h3>
<p class="bodytext">“The foremost of my laywomen in first going for refuge is Sujātā Seniyadhītā.</p>
<p class="bodytext">… as a donor is Visākhā, Migāra’s mother.</p>
<p class="bodytext">… who are very learned is Khujjuttarā.</p>
<p class="bodytext">… who dwell in love is Sāmāvatī.</p>
<p class="bodytext">… who practice absorption is Uttarānandamātā.</p>
<p class="bodytext">… who give fine things is Suppavāsā Koliyadhītā.</p>
<p class="bodytext">… who care for the sick is the laywoman Suppiyā.</p>
<p class="bodytext">… who have experiential confidence is Kātiyānī.</p>
<p class="bodytext">… who are intimate is the householder Nakula’s mother.</p>
<p class="bodytext">… whose confidence is based on oral transmission is the laywoman Kāḷī of Kuraraghara.”</p></div>
<h1 class="chapter">268-295. Aṭṭhāna Vagga</h1>
<div class="chaptxt">
<p class="title">21. First</p>
<h3 class="subhead"> AN 1.268 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to take any condition as permanent. That is not possible. But it is possible for an ordinary person to take some condition as permanent. That is possible.”</p>
<h3 class="subhead"> AN 1.269 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to take any condition as pleasant. But it is possible for an ordinary person to take some condition as pleasant.”</p>
<h3 class="subhead"> AN 1.270 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to take anything as self. But it is possible for an ordinary person to take something as self.”</p>
<h3 class="subhead"> AN 1.271 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to murder their mother. But it is possible for an ordinary person to murder their mother.”</p>
<h3 class="subhead"> AN 1.272 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to murder their father. But it is possible for an ordinary person to murder their father.”</p>
<h3 class="subhead"> AN 1.273 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to murder a perfected one. But it is possible for an ordinary person to murder a perfected one.”</p>
<h3 class="subhead"> AN 1.274 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to injure a Realized One with malicious intent. But it is possible for an ordinary person to injure a Realized One with malicious intent.”</p>
<h3 class="subhead"> AN 1.275 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to cause a schism in the Saṅgha. But it is possible for an ordinary person to cause a schism in the Saṅgha.”</p>
<h3 class="subhead"> AN 1.276 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a person accomplished in view to acknowledge another teacher. But it is possible for an ordinary person to acknowledge another teacher.”</p>
<h3 class="subhead"> AN 1.277 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for two perfected ones, fully awakened Buddhas to arise in the same solar system at the same time. But it is possible for just one perfected one, a fully awakened Buddha, to arise in one solar system.”</p>
<p class="title">22. Second</p>
<h3 class="subhead"> AN 1.278 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for two wheel-turning monarchs to arise in the same solar system at the same time. But it is possible for just one wheel-turning monarch to arise in one solar system.”</p>
<h3 class="subhead"> AN 1.279 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a woman to be a perfected one, a fully awakened Buddha. But it is possible for a man to be a perfected one, a fully awakened Buddha.”</p>
<h3 class="subhead"> AN 1.280 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a woman to be a wheel-turning monarch. But it is possible for a man to be a wheel-turning monarch.”</p>
<h3 class="subhead"> AN 1.281–283 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a woman to perform the role of Sakka, Māra, or Brahmā. But it is possible for a man to perform the role of Sakka, Māra, or Brahmā.”</p>
<h3 class="subhead"> AN 1.284 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a likable, desirable, agreeable result to come from bad bodily conduct. But it is possible for an unlikable, undesirable, disagreeable result to come from bad bodily conduct.”</p>
<h3 class="subhead"> AN 1.285–286 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for a likable, desirable, agreeable result to come from bad verbal … bad mental conduct. But it is possible for an unlikable, undesirable, disagreeable result to come from bad verbal … bad mental conduct.”</p>
<p class="title">23. Third</p>
<h3 class="subhead"> AN 1.287 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for an unlikable, undesirable, disagreeable result to come from good bodily conduct. But it is possible for a likable, desirable, agreeable result to come from good bodily conduct.”</p>
<h3 class="subhead"> AN 1.288–289 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen for an unlikable, undesirable, disagreeable result to come from good verbal … good mental conduct. But it is possible for a likable, desirable, agreeable result to come from good verbal … good mental conduct.”</p>
<h3 class="subhead"> AN 1.290 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen that someone who has engaged in bad bodily conduct, could for that reason alone, when their body breaks up, after death, be reborn in a good place, a heavenly realm. But it is possible that someone who has engaged in bad bodily conduct could, for that reason alone, when their body breaks up, after death, be reborn in a place of loss, a bad place, the underworld, hell.”</p>
<h3 class="subhead"> AN 1.291–292 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen that someone who has engaged in bad verbal … bad mental conduct could, for that reason alone, when their body breaks up, after death, be reborn in a good place, a heavenly realm. But it is possible that someone who has engaged in bad verbal … bad mental conduct could, for that reason alone, when their body breaks up, after death, be reborn in a place of loss, a bad place, the underworld, hell.”</p>
<h3 class="subhead"> AN 1.293 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen that someone who has engaged in good bodily conduct could, for that reason alone, when their body breaks up, after death, be reborn in a place of loss, the underworld, a lower realm, hell. But it is possible that someone who has engaged in good bodily conduct could, for that reason alone, when their body breaks up, after death, be reborn in a good place, a heavenly realm.”</p>
<h3 class="subhead"> AN 1.294–295 </h3>
<p class="bodytext">“It is impossible, mendicants, it cannot happen that someone who has engaged in good verbal … good mental conduct could, for that reason alone, when their body breaks up, after death, be reborn in a place of loss, a bad place, the underworld, hell. But it is possible that someone who has engaged in good verbal … good mental conduct could, for that reason alone, when their body breaks up, after death, be reborn in a good place, heavenly realm.”</p></div>
<h1 class="chapter">296-377. Ekadhamma Vagga</h1>
<div class="chaptxt">
<p class="title">24. First</p>
<h3 class="subhead"> AN 1.296 </h3>
<p class="bodytext">“One thing, mendicants, when developed and cultivated, leads solely to disillusionment, dispassion, cessation, peace, insight, awakening, and extinguishment. What one thing? Recollection of the Buddha. This one thing, when developed and cultivated, leads solely to disillusionment, dispassion, cessation, peace, insight, awakening, and extinguishment.”</p>
<h3 class="subhead"> AN 1.297–305 </h3>
<p class="bodytext">“One thing, mendicants, when developed and cultivated, leads solely to disillusionment, dispassion, cessation, peace, insight, awakening, and extinguishment. What one thing? Recollection of the teaching … Recollection of the Saṅgha … Recollection of ethical conduct … Recollection of generosity … Recollection of the deities … Mindfulness of breathing … Mindfulness of death … Mindfulness of the body … Recollection of peace. This one thing, when developed and cultivated, leads solely to disillusionment, dispassion, cessation, peace, insight, awakening, and extinguishment.”</p>
<p class="title">25. Second</p>
<h3 class="subhead"> AN 1.306 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or, when they have arisen, makes them increase and grow like wrong view. When you have wrong view, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.307 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or, when they have arisen, makes them increase and grow like right view. When you have right view, unarisen skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.308 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to unskillful qualities, or makes skillful qualities decline like wrong view. When you have wrong view, unskillful qualities arise and skillful qualities decline.”</p>
<h3 class="subhead"> AN 1.309 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to skillful qualities, or makes unskillful qualities decline like right view. When you have right view, skillful qualities arise and unskillful qualities decline.”</p>
<h3 class="subhead"> AN 1.310 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to wrong view, and once arisen, makes it grow like improper attention. When you attend improperly, wrong view arises, and once arisen it grows.”</p>
<h3 class="subhead"> AN 1.311 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that gives rise to right view, or, once it has already arisen, makes it grow like proper attention. When you attend properly, right view arises, and once arisen it grows.”</p>
<h3 class="subhead"> AN 1.312 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that causes sentient beings to be reborn, when their body breaks up, after death, in a place of loss, a bad place, the underworld, hell like wrong view. It is because they have wrong view that sentient beings, when their body breaks up, after death, are reborn in a place of loss, a bad place, the underworld, hell.”</p>
<h3 class="subhead"> AN 1.313 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that causes sentient beings to be reborn, when their body breaks up, after death, in a good place, a heavenly realm like right view. It is because they have right view that sentient beings, when their body breaks up, after death, are reborn in a good place, a heavenly realm.”</p>
<h3 class="subhead"> AN 1.314 </h3>
<p class="bodytext">“Mendicants, when an individual has wrong view, whatever bodily, verbal, or mental deeds they undertake in line with that view, their intentions, aims, wishes, and choices all lead to what is unlikable, undesirable, disagreeable, harmful, and suffering. Why is that? Because their view is bad. Suppose a seed of neem, angled gourd, or bitter gourd was planted in moist earth. Whatever nutrients it takes up from the earth and water would lead to its bitter, acerbic, and unpleasant taste. Why is that? Because the seed is bad. In the same way, when an individual has wrong view, whatever bodily, verbal, or mental deeds they undertake in line with that view, their intentions, aims, wishes, and choices all lead to what is unlikable, undesirable, disagreeable, harmful, and suffering. Why is that? Because their view is bad.”</p>
<h3 class="subhead"> AN 1.315 </h3>
<p class="bodytext">“Mendicants, when an individual has right view, whatever bodily, verbal, or mental deeds they undertake in line with that view, their intentions, aims, wishes, and choices all lead to what is likable, desirable, agreeable, beneficial, and pleasant. Why is that? Because their view is good. Suppose a seed of sugar cane, fine rice, or grape was planted in moist earth. Whatever nutrients it takes up from the earth and water would lead to its sweet, pleasant, and delicious taste. Why is that? Because the seed is good. In the same way, when an individual has right view, whatever bodily, verbal, or mental deeds they undertake in line with that view, their intentions, aims, wishes, and choices all lead to what is likable, desirable, agreeable, beneficial, and pleasant. Why is that? Because their view is good.”</p>
<p class="title">26. Third</p>
<h3 class="subhead"> AN 1.316 </h3>
<p class="bodytext">“One person, mendicants, arises in the world for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans. What one person? Someone with wrong view, whose perspective is distorted. They draw many people away from the true teaching and establish them in false teachings. This is one person who arises in the world for the hurt and unhappiness of the people, for the harm, hurt, and suffering of gods and humans.”</p>
<h3 class="subhead"> AN 1.317 </h3>
<p class="bodytext">“One person, mendicants, arises in the world for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans. What one person? Someone with right view, whose perspective is undistorted. They draw many people away from false teachings and establish them in the true teaching. This is one person who arises in the world for the welfare and happiness of the people, for the benefit, welfare, and happiness of gods and humans.”</p>
<h3 class="subhead"> AN 1.318 </h3>
<p class="bodytext">“Mendicants, I do not see a single thing that is so very blameworthy as wrong view. Wrong view is the most blameworthy thing of all.”</p>
<h3 class="subhead"> AN 1.319 </h3>
<p class="bodytext">“Mendicants, I do not see a single other person who acts for the hurt and unhappiness of the people, for the harm, hurt, and suffering of many people, of gods and humans like that silly man, Makkhali. Just as a trap set at the mouth of a river would bring harm, suffering, calamity, and disaster for many fish, so too that silly man, Makkhali, is a trap for humans, it seems to me. He has arisen in the world for the harm, suffering, calamity, and disaster of many beings.”</p>
<h3 class="subhead"> AN 1.320 </h3>
<p class="bodytext">“Mendicants, the one who encourages someone in a poorly explained teaching and training, the one who they encourage, and the one who practices accordingly all make much bad karma. Why is that? Because the teaching is poorly explained.”</p>
<h3 class="subhead"> AN 1.321 </h3>
<p class="bodytext">“Mendicants, the one who encourages someone in a well explained teaching and training, the one who they encourage, and the one who practices accordingly all make much merit. Why is that? Because the teaching is well explained.”</p>
<h3 class="subhead"> AN 1.322 </h3>
<p class="bodytext">“Mendicants, in a poorly explained teaching and training, the donor should know moderation, not the recipient. Why is that? Because the teaching is poorly explained.”</p>
<h3 class="subhead"> AN 1.323 </h3>
<p class="bodytext">“Mendicants, in a well explained teaching and training, the recipient should know moderation, not the donor. Why is that? Because the teaching is well explained.”</p>
<h3 class="subhead"> AN 1.324 </h3>
<p class="bodytext">“Mendicants, in a poorly explained teaching and training an energetic person lives in suffering. Why is that? Because the teaching is poorly explained.”</p>
<h3 class="subhead"> AN 1.325 </h3>
<p class="bodytext">“Mendicants, in a well explained teaching and training a lazy person lives in suffering. Why is that? Because the teaching is well explained.”</p>
<h3 class="subhead"> AN 1.326 </h3>
<p class="bodytext">“Mendicants, in a poorly explained teaching and training a lazy person lives happily. Why is that? Because the teaching is poorly explained.”</p>
<h3 class="subhead"> AN 1.327 </h3>
<p class="bodytext">“Mendicants, in a well explained teaching and training an energetic person lives happily. Why is that? Because the teaching is well explained.”</p>
<h3 class="subhead"> AN 1.328 </h3>
<p class="bodytext">“Just as, mendicants, even a tiny bit of fecal matter still stinks, so too I don’t approve of even a tiny bit of continued existence, not even as long as a finger snap.”</p>
<h3 class="subhead"> AN 1.329–332 </h3>
<p class="bodytext">“Just as even a tiny bit of urine, or spit, or pus, or blood still stinks, so too I don’t approve of even a tiny bit of continued existence, not even as long as a finger snap.”</p>
<p class="title">27. Fourth</p>
<h3 class="subhead"> AN 1.333 </h3>
<p class="bodytext">“Just as, mendicants, in India the delightful parks, woods, meadows, and lotus ponds are few, while the hilly terrain, inaccessible riverlands, stumps and thorns, and rugged mountains are many; so too the sentient beings born on land are few, while those born in water are many.</p>
<h3 class="subhead"> AN 1.334 </h3>
<p class="bodytext">… so too the sentient beings reborn as humans are few, while those not reborn as humans are many.</p>
<p class="bodytext">… so too the sentient beings reborn in civilized countries are few, while those reborn in the borderlands, among strange barbarian tribes, are many.</p>
<h3 class="subhead"> AN 1.335 </h3>
<p class="bodytext">… so too the sentient beings who are wise, bright, clever, and able to distinguish what is well said from what is poorly said are few, while the sentient beings who are witless, dull, stupid, and unable to distinguish what is well said from what is poorly said are many.</p>
<h3 class="subhead"> AN 1.336 </h3>
<p class="bodytext">… so too the sentient beings who have the noble eye of wisdom are few, while those who are ignorant and confused are many.</p>
<h3 class="subhead"> AN 1.337 </h3>
<p class="bodytext">… so too the sentient beings who get to see a Realized One are few, while those who don’t get to see a Realized One are many.</p>
<h3 class="subhead"> AN 1.338 </h3>
<p class="bodytext">… so too the sentient beings who get to hear the teaching and training proclaimed by a Realized One are few, while those sentient beings who don’t get to hear the teaching and training proclaimed by a Realized One are many.</p>
<h3 class="subhead"> AN 1.339 </h3>
<p class="bodytext">… so too the sentient beings who remember the teachings they hear are few, while those who don’t remember the teachings are many.</p>
<h3 class="subhead"> AN 1.340 </h3>
<p class="bodytext">… so too the sentient beings who examine the meaning of the teachings they have memorized are few, while those who don’t examine the meaning of the teachings are many.</p>
<h3 class="subhead"> AN 1.341 </h3>
<p class="bodytext">… so too the sentient beings who understand the meaning and the teaching and practice accordingly are few, while those who understand the meaning and the teaching but don’t practice accordingly are many.</p>
<h3 class="subhead"> AN 1.342 </h3>
<p class="bodytext">… so too the sentient beings inspired by inspiring places are few, while those who are uninspired are many.</p>
<h3 class="subhead"> AN 1.343 </h3>
<p class="bodytext">… so too the sentient beings who, being inspired, strive effectively are few, while those who, even though inspired, don’t strive effectively are many.</p>
<h3 class="subhead"> AN 1.344 </h3>
<p class="bodytext">… so too the sentient beings who, relying on letting go, gain immersion, gain unification of mind are few, while those who don’t gain immersion, don’t gain unification of mind relying on letting go are many.</p>
<h3 class="subhead"> AN 1.345 </h3>
<p class="bodytext">… so too the sentient beings who get the best food and flavors are few, while those who don’t get the best food and flavors, but get by with scraps in an alms bowl are many.</p>
<h3 class="subhead"> AN 1.346 </h3>
<p class="bodytext">… so too the sentient beings who get the essence of the meaning, the essence of the teaching, and the essence of freedom are few, while the sentient beings who don’t get the essence of the meaning, the essence of the teaching, and the essence of freedom are many.</p>
<p class="bodytext">So you should train like this: ‘We will get the essence of the meaning, the essence of the teaching, the essence of freedom.’ That’s how you should train.”</p>
<h3 class="subhead"> AN 1.347–349 </h3>
<p class="bodytext">“Just as, mendicants, in India the delightful parks, woods, meadows, and lotus ponds are few, while the hilly terrain, inaccessible riverlands, stumps and thorns, and rugged mountains are many; so too, those who die as humans and are reborn as humans are few, while those who die as humans and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.350–352 </h3>
<p class="bodytext">“… the sentient beings who die as humans and are reborn as gods are few, while those who die as humans and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.353–355 </h3>
<p class="bodytext">“… the sentient beings who die as gods and are reborn as gods are few, while those who die as gods and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.356–358 </h3>
<p class="bodytext">“… the sentient beings who die as gods and are reborn as humans are few, while those who die as gods and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.359–361 </h3>
<p class="bodytext">“… the sentient beings who die in hell and are reborn as humans are few, while those who die in hell and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.362–364 </h3>
<p class="bodytext">“… the sentient beings who die in hell and are reborn as gods are few, while those who die in hell and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.365–367 </h3>
<p class="bodytext">“… the sentient beings who die as animals and are reborn as humans are few, while those who die as animals and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.368–370 </h3>
<p class="bodytext">“… the sentient beings who die as animals and are reborn as gods are few, while those who die as animals and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.371–373 </h3>
<p class="bodytext">“… the sentient beings who die as ghosts and are reborn as humans are few, while those who die as ghosts and are reborn in hell, or the animal realm, or the ghost realm are many.”</p>
<h3 class="subhead"> AN 1.374–377 </h3>
<p class="bodytext">“… the sentient beings who die as ghosts and are reborn as gods are few, while those who die as ghosts and are reborn in hell, or the animal realm, or the ghost realm are many.”</p></div>
<h1 class="chapter">378–⁠393. Pasādakaradhamma Vagga</h1>
<div class="chaptxt">
<p class="title">28. Inspirational</p>
<h3 class="subhead"> AN 1.378–393 </h3>
<p class="bodytext">“Mendicants, this is definitely something worth having, that is, living in the wilderness … eating only alms-food … wearing rag robes … having just three robes … teaching Dhamma … memorizing the texts on monastic training … being very learned … being respected … being well-presented … having a following … having a large following … coming from a good family … being handsome … being a good speaker … having few wishes … having good health.”</p></div>
<h1 class="chapter">394–⁠574. Aparaaccharāsaṅghāta Vagga</h1>
<div class="chaptxt">
<p class="title">29. Another Chapter on a Finger Snap</p>
<h3 class="subhead"> AN 1.394 </h3>
<p class="bodytext">“If, mendicants, a mendicant develops the first absorption, even as long as a finger snap, they are called a mendicant who does not lack absorption, who follows the Teacher’s instructions, who responds to advice, and who does not eat the country’s alms in vain. How much more so those who make much of it!”</p>
<h3 class="subhead"> AN 1.395–401 </h3>
<p class="bodytext">“If, mendicants, a mendicant develops the second … third … or fourth absorption … or the heart’s release by love … or the heart’s release by compassion … or the heart’s release by rejoicing … or the heart’s release by equanimity, even as long as a finger snap …</p>
<h3 class="subhead"> AN 1.402–405 </h3>
<p class="bodytext">If a mendicant meditates by observing an aspect of the body … feelings … mind … principles—keen, aware, and mindful, rid of desire and aversion for the world, even for the time of a finger snap …</p>
<h3 class="subhead"> AN 1.406–409 </h3>
<p class="bodytext">If they generate enthusiasm, try, make an effort, exert the mind, and strive so that bad, unskillful qualities don’t arise, even for the time of a finger snap … If they generate enthusiasm, try, make an effort, exert the mind, and strive so that bad, unskillful qualities that have arisen are given up, even for the time of a finger snap … If they generate enthusiasm, try, make an effort, exert the mind, and strive so that skillful qualities that have not arisen do arise, even for the time of a finger snap … If they generate enthusiasm, try, make an effort, exert the mind, and strive so that skillful qualities that have arisen remain, are not lost, but increase, mature, and are fulfilled by development, even for the time of a finger snap …</p>
<h3 class="subhead"> AN 1.410–413 </h3>
<p class="bodytext">If they develop the basis of psychic power that has immersion due to enthusiasm, and active effort … the basis of psychic power that has immersion due to energy, and active effort … the basis of psychic power that has immersion due to mental development, and active effort … the basis of psychic power that has immersion due to inquiry, and active effort, even for the time of a finger snap …</p>
<h3 class="subhead"> AN 1.414–418 </h3>
<p class="bodytext">If they develop the faculty of faith … the faculty of energy … the faculty of mindfulness … the faculty of immersion … the faculty of wisdom, even for the time of a finger snap …</p>
<h3 class="subhead"> AN 1.419–423 </h3>
<p class="bodytext">If they develop the power of faith … the power of energy … the power of mindfulness … the power of immersion … the power of wisdom, even for the time of a finger snap …</p>
<h3 class="subhead"> AN 1.424–430 </h3>
<p class="bodytext">If they develop the awakening factor of mindfulness … the awakening factor of investigation of principles … the awakening factor of energy … the awakening factor of rapture … the awakening factor of tranquility … the awakening factor of immersion … the awakening factor of equanimity, even for the time of a finger snap …</p>
<h3 class="subhead"> AN 1.431–438 </h3>
<p class="bodytext">If they develop right view … right thought … right speech … right action … right livelihood … right effort … right mindfulness … right immersion, even for the time of a finger snap …</p>
<h3 class="subhead"> AN 1.439–446 </h3>
<p class="bodytext">Perceiving form internally, they see visions externally, limited, both pretty and ugly. Having mastered this, they are aware that: ‘I know and see.’ … Perceiving form internally, they see visions externally, limitless, both pretty and ugly. Having mastered this, they are aware that: ‘I know and see.’ … Not perceiving form internally, they see visions externally, limited, both pretty and ugly. Having mastered this, they are aware that: ‘I know and see.’ … Not perceiving form internally, they see visions externally, limitless, both pretty and ugly. Having mastered this, they are aware that: ‘I know and see.’ … Not perceiving form internally, they see visions externally that are blue, with blue color, blue hue, and blue tint. Having mastered this, they are aware that: ‘I know and see.’ … Not perceiving form internally, they see visions externally that are yellow, with yellow color, yellow hue, and yellow tint. Having mastered this, they are aware that: ‘I know and see.’ … Not perceiving form internally, they see visions externally that are red, with red color, red hue, and red tint. Having mastered this, they are aware that: ‘I know and see.’ … Not perceiving form internally, they see visions externally that are white, with white color, white hue, and white tint. Having mastered this, they are aware that: ‘I know and see.’ …</p>
<h3 class="subhead"> AN 1.447–454 </h3>
<p class="bodytext">Having physical form, they see visions … not perceiving form internally, they see visions externally … they’re focused only on beauty … going totally beyond perceptions of form, with the ending of perceptions of impingement, not focusing on perceptions of diversity, aware that ‘space is infinite’, they enter and remain in the dimension of infinite space … going totally beyond the dimension of infinite space, aware that ‘consciousness is infinite’, they enter and remain in the dimension of infinite consciousness … going totally beyond the dimension of infinite consciousness, aware that ‘there is nothing at all’, they enter and remain in the dimension of nothingness … going totally beyond the dimension of nothingness, they enter and remain in the dimension of neither perception nor non-perception … going totally beyond the dimension of neither perception nor non-perception, they enter and remain in the cessation of perception and feeling …</p>
<h3 class="subhead"> AN 1.455–464 </h3>
<p class="bodytext">They develop the meditation on universal earth … the meditation on universal water … the meditation on universal fire … the meditation on universal air … the meditation on universal blue … the meditation on universal yellow … the meditation on universal red … the meditation on universal white … the meditation on universal space … the meditation on universal consciousness …</p>
<h3 class="subhead"> AN 1.465–474 </h3>
<p class="bodytext">They develop the perception of ugliness … the perception of death … the perception of the repulsiveness of food … the perception of dissatisfaction with the whole world … the perception of impermanence … the perception of suffering in impermanence … the perception of not-self in suffering … the perception of giving up … the perception of fading away … the perception of cessation …</p>
<h3 class="subhead"> AN 1.475–484 </h3>
<p class="bodytext">They develop the perception of impermanence … the perception of not-self … the perception of death … the perception of the repulsiveness of food … the perception of dissatisfaction with the whole world … the perception of a skeleton … the perception of the worm-infested corpse … the perception of the livid corpse … the perception of the split open corpse … the perception of the bloated corpse …</p>
<h3 class="subhead"> AN 1.485–494 </h3>
<p class="bodytext">They develop the recollection of the Buddha … the recollection of the teaching … the recollection of the Saṅgha … the recollection of ethical conduct … the recollection of generosity … the recollection of the deities … mindfulness of breathing … the recollection of death … mindfulness of the body … the recollection of peace …</p>
<h3 class="subhead"> AN 1.495–534 </h3>
<p class="bodytext">They develop the faculty of faith together with the first absorption … the faculty of energy … the faculty of mindfulness … the faculty of immersion … the faculty of wisdom … the power of faith … the power of energy … the power of mindfulness … the power of immersion … the power of wisdom together with the first absorption …</p>
<h3 class="subhead"> AN 1.535–574 </h3>
<p class="bodytext">Together with the second absorption … the third absorption … the fourth absorption … love … compassion … rejoicing … They develop the faculty of faith together with equanimity … They develop the faculty of energy … the faculty of mindfulness … the faculty of immersion … the faculty of wisdom … the power of faith … the power of energy … the power of mindfulness … the power of immersion … the power of wisdom. That mendicant is called a mendicant who does not lack absorption, who follows the Teacher’s instructions, who responds to advice, and who does not eat the country’s alms in vain. How much more so those who make much of it!”</p></div>
<h1 class="chapter">575–⁠615. Kāyagatāsati Vagga</h1>
<div class="chaptxt">
<p class="title">30. Mindfulness of the Body</p>
<h3 class="subhead"> AN 1.575 </h3>
<p class="bodytext">“Mendicants, anyone who brings into their mind the great ocean includes all of the streams that run into it. In the same way, anyone who has developed and cultivated mindfulness of the body includes all of the skillful qualities that play a part in realization.”</p>
<h3 class="subhead"> AN 1.576–582 </h3>
<p class="bodytext">“One thing, mendicants, when developed and cultivated leads to great urgency … great benefit … great sanctuary … mindfulness and awareness … gaining knowledge and vision … blissful meditation in the present life … the realization of the fruit of knowledge and freedom. What one thing? Mindfulness of the body. This one thing, when developed and cultivated, leads to great urgency … great benefit … great sanctuary … mindfulness and awareness … gaining knowledge and vision … a happy abiding in the present life … the realization of the fruit of knowledge and freedom.”</p>
<h3 class="subhead"> AN 1.583 </h3>
<p class="bodytext">“When one thing, mendicants, is developed and cultivated the body and mind become tranquil, thinking and considering settle down, and all of the qualities that play a part in realization are fully developed. What one thing? Mindfulness of the body. When this one thing is developed and cultivated, the body and mind become tranquil, thinking and considering settle down, and all of the qualities that play a part in realization are fully developed.”</p>
<h3 class="subhead"> AN 1.584 </h3>
<p class="bodytext">“When one thing, mendicants, is developed and cultivated, unskillful qualities do not arise, and, if they’ve already arisen, they are given up. What one thing? Mindfulness of the body. When this one thing is developed and cultivated, unskillful qualities do not arise, and, if they’ve already arisen, they are given up.”</p>
<h3 class="subhead"> AN 1.585 </h3>
<p class="bodytext">“When one thing, mendicants, is developed and cultivated, skillful qualities arise, and, once they’ve arisen, they increase and grow. What one thing? Mindfulness of the body. When this one thing is developed and cultivated, skillful qualities arise, and, once they’ve arisen, they increase and grow.”</p>
<h3 class="subhead"> AN 1.586 </h3>
<p class="bodytext">“When one thing, mendicants, is developed and cultivated, ignorance is given up, knowledge arises, the conceit ‘I am’ is given up, the underlying tendencies are uprooted, and the fetters are given up. What one thing? Mindfulness of the body. When this one thing is developed and cultivated, ignorance is given up, knowledge arises, the conceit ‘I am’ is given up, the underlying tendencies are uprooted, and the fetters are given up.”</p>
<h3 class="subhead"> AN 1.587–588 </h3>
<p class="bodytext">“One thing, mendicants, when developed and cultivated leads to demolition by wisdom … to extinguishment by not grasping. What one thing? Mindfulness of the body. This one thing, mendicants, when developed and cultivated leads to demolition by wisdom … to extinguishment by not grasping.”</p>
<h3 class="subhead"> AN 1.589–591 </h3>
<p class="bodytext">“When one thing is developed and cultivated there is the penetration of many elements … the penetration of diverse elements … the analysis of many elements. What one thing? Mindfulness of the body. When this one thing is developed and cultivated there is the penetration of many elements … the penetration of diverse elements … the analysis of many elements.”</p>
<h3 class="subhead"> AN 1.592–595 </h3>
<p class="bodytext">“One thing, mendicants, when developed and cultivated leads to the realization of the fruit of stream-entry … once-return … non-return … perfection. What one thing? Mindfulness of the body. This one thing, when developed and cultivated, leads to the realization of the fruit of stream-entry … once-return … non-return … perfection.”</p>
<h3 class="subhead"> AN 1.596–615 </h3>
<p class="bodytext">“One thing, mendicants, when developed and cultivated, leads to the getting of wisdom … the growth of wisdom … the increase of wisdom … to great wisdom … to widespread wisdom … to abundant wisdom … to deep wisdom … to extraordinary wisdom … to vast wisdom … to much wisdom … to fast wisdom … to light wisdom … to laughing wisdom … to swift wisdom … to sharp wisdom … to penetrating wisdom. What one thing? Mindfulness of the body. This one thing, when developed and cultivated, leads to the getting of wisdom … the growth of wisdom … the increase of wisdom … to great wisdom … to widespread wisdom … to abundant wisdom … to deep wisdom … to extraordinary wisdom … to vast wisdom … to much wisdom … to fast wisdom … to light wisdom … to laughing wisdom … to swift wisdom … to sharp wisdom … to penetrating wisdom.”</p></div>
<h1 class="chapter">616–⁠627. Amata Vagga</h1>
<div class="chaptxt">
<p class="title">31. The Deathless</p>
<h3 class="subhead"> AN 1.616 </h3>
<p class="bodytext">“Mendicants, those who don’t enjoy mindfulness of the body don’t enjoy the deathless. Those who enjoy mindfulness of the body enjoy the deathless.”</p>
<h3 class="subhead"> AN 1.617 </h3>
<p class="bodytext">“Mendicants, those who haven’t enjoyed mindfulness of the body haven’t enjoyed the deathless. Those who have enjoyed mindfulness of the body have enjoyed the deathless.”</p>
<h3 class="subhead"> AN 1.618 </h3>
<p class="bodytext">“Mendicants, those who have lost mindfulness of the body have lost the deathless. Those who haven’t lost mindfulness of the body haven’t lost the deathless.”</p>
<h3 class="subhead"> AN 1.619 </h3>
<p class="bodytext">“Mendicants, those who have missed out on mindfulness of the body have missed out on the deathless. Those who have undertaken mindfulness of the body have not missed out on the deathless.”</p>
<h3 class="subhead"> AN 1.620 </h3>
<p class="bodytext">“Mendicants, those who have neglected mindfulness of the body have neglected the deathless. Those who have not neglected mindfulness of the body have not neglected the deathless.”</p>
<h3 class="subhead"> AN 1.621 </h3>
<p class="bodytext">“Mendicants, those who have forgotten mindfulness of the body have forgotten the deathless. Those who haven’t forgotten mindfulness of the body haven’t forgotten the deathless.”</p>
<h3 class="subhead"> AN 1.622 </h3>
<p class="bodytext">“Mendicants, those who haven’t cultivated mindfulness of the body haven’t cultivated the deathless. Those who have cultivated mindfulness of the body have cultivated the deathless.”</p>
<h3 class="subhead"> AN 1.623 </h3>
<p class="bodytext">“Mendicants, those who haven’t developed mindfulness of the body haven’t developed the deathless. Those who have developed mindfulness of the body have developed the deathless.”</p>
<h3 class="subhead"> AN 1.624 </h3>
<p class="bodytext">“Mendicants, those who haven’t practiced mindfulness of the body haven’t practiced the deathless. Those who have practiced mindfulness of the body have practiced the deathless.”</p>
<h3 class="subhead"> AN 1.625 </h3>
<p class="bodytext">“Mendicants, those who haven’t had insight into mindfulness of the body haven’t had insight into the deathless. Those who have had insight into mindfulness of the body have had insight into the deathless.”</p>
<h3 class="subhead"> AN 1.626 </h3>
<p class="bodytext">“Mendicants, those who haven’t completely understood mindfulness of the body haven’t completely understood the deathless. Those who have completely understood mindfulness of the body have completely understood the deathless.”</p>
<h3 class="subhead"> AN 1.627 </h3>
<p class="bodytext">“Mendicants, those who haven’t realized mindfulness of the body haven’t realized the deathless. Those who have realized mindfulness of the body have realized the deathless.”</p>
<p class="bodytext">The thousand discourses of the Ones are completed.</p>
<p class="bodytext">That is what the Buddha said. Satisfied, the mendicants were happy with what the Buddha said.</p>
<p class="centered">The Book of the Ones is finished.</p></div>
<div end="ed" class="end"></div>`

document.getElementById('loaddata').innerHTML = mulaen_2_4_1 
searchhelper()
bookhelper()
var chapterhelper = document.createElement('script')
chapterhelper.src = `chaptertoggle.js`
document.head.appendChild(chapterhelper)