var mulaen_2_5_1 = `
<div id="table_main">
<div id="table_name">Table Of Contents</div></div>
<p class="namo">॥ Namo tassa bhagavato arahato sammāsambuddhassa ॥</p>
<p class="bookname">Khuddakapāṭha</p>
<p class="author">Translated by Bhikkhu Ānandajoti</p>
<h1 class="chapter">Going for Refuge</h1>
<div class="chaptxt">
<p class="chaphead">short readings 1</p>
<p class="bodytext">I go to the Buddha for refuge.</p>
<p class="bodytext">I go to the Dhamma for refuge.</p>
<p class="bodytext">I go to the Sangha for refuge.</p>
<p class="bodytext">For a second time I go to the Buddha for refuge.</p>
<p class="bodytext">For a second time I go to the Dhamma for refuge.</p>
<p class="bodytext">For a second time I go to the Sangha for refuge.</p>
<p class="bodytext">For a third time I go to the Buddha for refuge.</p>
<p class="bodytext">For a third time I go to the Dhamma for refuge.</p>
<p class="bodytext">For a third time I go to the Sangha for refuge.</p></div>
<h1 class="chapter">The Ten Training Rules</h1>
<div class="chaptxt">
<p class="chaphead">short readings 2</p>
<p class="bodytext">I undertake the training rule of refraining from killing living creatures</p>
<p class="bodytext">I undertake the training rule of refraining from taking what has not been given</p>
<p class="bodytext">I undertake the training rule of refraining from unchastity</p>
<p class="bodytext">I undertake the training rule of refraining from false speech</p>
<p class="bodytext">I undertake the training rule of refraining from liquor, wines, or intoxicants which cause heedlessness.</p>
<p class="bodytext">I undertake the training rule of refraining from eating at the wrong time</p>
<p class="bodytext">I undertake the training rule of refraining from dances, songs, music, and watching shows</p>
<p class="bodytext">I undertake the training rule of refraining from adorning or ornamenting myself by wearing garlands, scents, or ointments</p>
<p class="bodytext">I undertake the training rule of refraining from lofty or grand beds</p>
<p class="bodytext">I undertake the training rule of refraining from accepting gold or money</p></div>
<h1 class="chapter">The Ten Training Rules</h1>
<div class="chaptxt">
<p class="chaphead">short readings 3</p>
<p class="bodytext">I undertake the training rule of refraining from killing living creatures</p>
<p class="bodytext">I undertake the training rule of refraining from taking what has not been given</p>
<p class="bodytext">I undertake the training rule of refraining from unchastity</p>
<p class="bodytext">I undertake the training rule of refraining from false speech</p>
<p class="bodytext">I undertake the training rule of refraining from liquor, wines, or intoxicants which cause heedlessness.</p>
<p class="bodytext">I undertake the training rule of refraining from eating at the wrong time</p>
<p class="bodytext">I undertake the training rule of refraining from dances, songs, music, and watching shows</p>
<p class="bodytext">I undertake the training rule of refraining from adorning or ornamenting myself by wearing garlands, scents, or ointments</p>
<p class="bodytext">I undertake the training rule of refraining from lofty or grand beds</p>
<p class="bodytext">I undertake the training rule of refraining from accepting gold or money</p></div>
<h1 class="chapter">The Questions to the Boy</h1>
<div class="chaptxt">
<p class="chaphead">short readings 4</p>
<p class="bodytext">What is said to be one?</p>
<p class="bodytext">All beings subsist on food.</p>
<p class="bodytext">What is said to be two?</p>
<p class="bodytext">Mind and body.</p>
<p class="bodytext">What is said to be three?</p>
<p class="bodytext">The three feelings.</p>
<p class="bodytext">What is said to be four?</p>
<p class="bodytext">The four noble truths.</p>
<p class="bodytext">What is said to be five?</p>
<p class="bodytext">The five constituent groups of mind and body that provide fuel for attachment.</p>
<p class="bodytext">What is said to be six?</p>
<p class="bodytext">The six internal sense spheres.</p>
<p class="bodytext">What is said to be seven?</p>
<p class="bodytext">The seven factors of Awakening.</p>
<p class="bodytext">What is said to be eight?</p>
<p class="bodytext">The noble path with eight factors.</p>
<p class="bodytext">What is said to be nine?</p>
<p class="bodytext">The nine abodes of beings.</p>
<p class="bodytext">What is said to be ten?</p>
<p class="bodytext">When endowed with ten factors he is said to be Worthy.</p></div>
<h1 class="chapter">The Discourse on the Blessings</h1>
<div class="chaptxt">
<p class="chaphead">short readings 5</p>
<p class="bodytext">this is what i heard: At one time the Gracious One was dwelling near Sāvatthi, at Anāthapiṇḍika’s grounds in Jeta’s Wood. Then a certain god, at the end of the night, having lit up the whole of Jeta’s Wood with his surpassing beauty, approached the Gracious One, and after approaching and worshipping the Gracious One, he stood on one side. While standing on one side that god recited this verse to the Gracious One:</p>
<p class="gatha0">“Many are the gods and the men</p>
<p class="gatha">who have thought about the blessings</p>
<p class="gatha">hoping for safety:</p>
<p class="gatha">now please say what is a supreme blessing.”</p>
<p class="gatha0">“Not associating with fools,</p>
<p class="gatha">with the wise associating,</p>
<p class="gatha">honouring those worthy of honour:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Living in a suitable place,</p>
<p class="gatha">formerly having done good deeds,</p>
<p class="gatha">having the right aspiration for oneself:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Having great learning and craft,</p>
<p class="gatha">being disciplined and well trained,</p>
<p class="gatha">and whatever words are well spoken:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Attending on one’s mother and father,</p>
<p class="gatha">looking after one’s wife and sons,</p>
<p class="gatha">having work that is not confusing:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Giving, and living by the Dhamma,</p>
<p class="gatha">and looking after one’s relatives, </p>
<p class="gatha">performing actions that are blameless:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Abstaining, refraining from bad deeds,</p>
<p class="gatha">restraint from intoxicating drink,</p>
<p class="gatha">being heedful regarding all things:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Having respect and being humble,</p>
<p class="gatha">being satisfied and grateful,</p>
<p class="gatha">listening to the Dhamma at the right time:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Being patient and easily spoken to,</p>
<p class="gatha">having sight of ascetics,</p>
<p class="gatha">discussing the Dhamma at the right time:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Austerity, living spiritually,</p>
<p class="gatha">insight into the noble truths,</p>
<p class="gatha">and experiencing Emancipation:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“He whose mind does not waver,</p>
<p class="gatha">when it is touched by things of this world,</p>
<p class="gatha">being griefless, dustless, and secure:</p>
<p class="gatha">this is a supreme blessing.</p>
<p class="gatha0">“Having done as here directed,</p>
<p class="gatha">being undefeated everywhere,</p>
<p class="gatha">they go everywhere in safety:</p>
<p class="gatha">for them this is a supreme blessing.”</p>
<p class="centered">The Discourse on the Blessings is Finished</p></div>
<h1 class="chapter">The Discourse on the Treasures</h1>
<div class="chaptxt">
<p class="chaphead">short readings 6</p>
<p class="gatha0">Whatever beings have come together here,</p>
<p class="gatha">whether of the earth or in the firmament,</p>
<p class="gatha">may the minds of all those beings be happy,</p>
<p class="gatha">and may they listen carefully to what is said.</p>
<p class="gatha0">Therefore, all of you beings, be attentive,</p>
<p class="gatha">be friendly towards this generation of men,</p>
<p class="gatha">they who bring offerings by day and by night,</p>
<p class="gatha">as they are heedful please protect them.</p>
<p class="gatha0">Whatever riches there are—here or hereafter</p>
<p class="gatha">or in the heavens—that excellent treasure</p>
<p class="gatha">is not equal unto the Realised One—</p>
<p class="gatha">this excellent treasure is in the Buddha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Craving’s end, dispassion, deathlessness, excellence—</p>
<p class="gatha">that which the concentrated Sakyan sage attained—</p>
<p class="gatha">there is nothing that is equal to the Dhamma—</p>
<p class="gatha">this excellent treasure is in the Dhamma:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">That which the great Buddha praised as being pure—</p>
<p class="gatha">the concentration said to have immediate result—</p>
<p class="gatha">no equal to that concentration is found—</p>
<p class="gatha">this excellent treasure is in the Dhamma:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Those eight individuals praised by the good—</p>
<p class="gatha">there are these four pairs of persons—</p>
<p class="gatha">those disciples of the Fortunate One are worthy of gifts,</p>
<p class="gatha">those things that have been given to them have great fruit—</p>
<p class="gatha">this excellent treasure is in the Sangha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Those who have firm minds that are devoted to</p>
<p class="gatha">Gotama’s teaching, being free from sense desire—</p>
<p class="gatha">having attained and entered the deathless—</p>
<p class="gatha">are enjoying the stillness, obtained for free—</p>
<p class="gatha">this excellent treasure is in the Sangha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Just as a locking post stuck fast in the earth</p>
<p class="gatha">does not waver on account of the four winds,</p>
<p class="gatha">just like this, I say, is the person who is true,</p>
<p class="gatha">the one who sees the noble truths completely—</p>
<p class="gatha">this excellent treasure is in the Sangha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Those who clearly distinguish the noble truths,</p>
<p class="gatha">which have been well preached by the one with great wisdom,</p>
<p class="gatha">no matter how great they become in heedlessness</p>
<p class="gatha">still they do not take up an eighth existence—</p>
<p class="gatha">this excellent treasure is in the Sangha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Together with his attainment of seeing Emancipation</p>
<p class="gatha">there are three things that are given up:</p>
<p class="gatha">embodiment view, uncertainty, and</p>
<p class="gatha">whatever grasping at virtue and practices there is.</p>
<p class="gatha">He is free from rebirth in the four lower worlds,</p>
<p class="gatha">and he is incapable of the six great crimes—</p>
<p class="gatha">this excellent treasure is in the Sangha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Whatever bad actions he performs</p>
<p class="gatha">by way of body, speech, or mind,</p>
<p class="gatha">he is incapable of covering it up:</p>
<p class="gatha">this incapacity is said of one who has seen the state of peace—</p>
<p class="gatha">this excellent treasure is in the Sangha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">Just like a tall woodland tree crowned with flowers</p>
<p class="gatha">in the summer months, in the early summer,</p>
<p class="gatha">just like this he preached the Dhamma which is best,</p>
<p class="gatha">which goes to Emancipation, the highest benefit—</p>
<p class="gatha">this excellent treasure is in the Buddha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">The best one, knowing the best, gave the best, brought the best,</p>
<p class="gatha">he preached the best Dhamma, which is unsurpassed—</p>
<p class="gatha">this excellent treasure is in the Buddha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="gatha0">The old is destroyed, and nothing new is produced,</p>
<p class="gatha">their minds are unexcited by future rebirth,</p>
<p class="gatha">they have destroyed the seeds, and have no desire for growth,</p>
<p class="gatha">the wise are still, just as this lamp is still—</p>
<p class="gatha">this excellent treasure is in the Sangha:</p>
<p class="gatha">by virtue of this truth may there be safety!</p>
<p class="bodytext">Spoken by Sakka, lord of the gods:</p>
<p class="gatha0">Whatever beings have come together here,</p>
<p class="gatha">whether of the earth or in the firmament,</p>
<p class="gatha">we all revere the realised Buddha who is</p>
<p class="gatha">honoured by gods and men—may there be safety!</p>
<p class="gatha0">Whatever beings have come together here,</p>
<p class="gatha">whether of the earth or in the firmament,</p>
<p class="gatha">we all revere the realised Dhamma which is</p>
<p class="gatha">honoured by gods and men—may there be safety!</p>
<p class="gatha0">Whatever beings have come together here,</p>
<p class="gatha">whether of the earth or in the firmament,</p>
<p class="gatha">we all revere the realised Sangha which is</p>
<p class="gatha">honoured by gods and men—may there be safety!</p>
<p class="centered">The Discourse on the Treasures is Finished</p></div>
<h1 class="chapter">The Beyond the Walls Discourse</h1>
<div class="chaptxt">
<p class="chaphead">short readings 7</p>
<p class="gatha0">They stand beyond the walls,</p>
<p class="gatha">and at the junctions and crossroads,</p>
<p class="gatha">they stand at the door-posts,</p>
<p class="gatha">having come to their former homes.</p>
<p class="gatha0">But when abundant food and drink,</p>
<p class="gatha">both staple and non-staple, is prepared,</p>
<p class="gatha">no one remembers these</p>
<p class="gatha">beings, because of their past unwholesome deeds,</p>
<p class="gatha0">Thus those who are compassionate</p>
<p class="gatha">give to their departed relatives,</p>
<p class="gatha">at the right time, pure, excellent,</p>
<p class="gatha">suitable drink and food.</p>
<p class="gatha0">Thinking: “May this go to our relatives,</p>
<p class="gatha">may our relatives be happy!”</p>
<p class="gatha">Those who have gathered,</p>
<p class="gatha">the departed relatives who have assembled</p>
<p class="gatha">around the food and drink,</p>
<p class="gatha">respectfully offer their thanks:</p>
<p class="gatha0">saying: “ May our relatives live long!</p>
<p class="gatha">Those to whom we owe this gain,</p>
<p class="gatha">for we have been honoured,</p>
<p class="gatha">those who give are not without reward!”</p>
<p class="gatha0">For in that place there is no ploughing,</p>
<p class="gatha">and cattle-rearing is not found there,</p>
<p class="gatha">similarly there is no trading,</p>
<p class="gatha">or buying and selling of gold.</p>
<p class="gatha0">The departed in that place who have died, have to subsist on gifts.</p>
<p class="gatha">Just as water that rains on the highlands, flows down to the lowlands,</p>
<p class="gatha">so too what has been given here</p>
<p class="gatha">is of benefit to the departed.</p>
<p class="gatha0">Just as rivers that are full</p>
<p class="gatha">flow and fill up the ocean,</p>
<p class="gatha">so too what has been given here</p>
<p class="gatha">is of benefit to the departed.</p>
<p class="gatha0">Thinking: “He gave to me, he worked for me,</p>
<p class="gatha">he was my relative, my friend, my companion,”</p>
<p class="gatha">he should give gifts for the departed,</p>
<p class="gatha">remembering what they have done before.</p>
<p class="gatha0">For no tears, or grief,</p>
<p class="gatha">or any other lamentations,</p>
<p class="gatha">are of any use to the departed,</p>
<p class="gatha">as long as their relatives continue grieving in this way.</p>
<p class="gatha0">But that gift that has been given,</p>
<p class="gatha">and well placed in the Sangha,</p>
<p class="gatha">is of benefit to them for a long time,</p>
<p class="gatha">immediately it is of benefit.</p>
<p class="gatha0">This then is the definition of a relative’s duties—</p>
<p class="gatha">and by this great honour has been done to the departed,</p>
<p class="gatha">strength has also been given to the monks,</p>
<p class="gatha">and no little merit has been produced by you!</p>
<p class="centered">The Beyond the Walls Discourse is Finished</p></div>
<h1 class="chapter">The Discourse on the Amount of Savings</h1>
<div class="chaptxt">
<p class="chaphead">short readings 8</p>
<p class="gatha0">A man stores his savings</p>
<p class="gatha">in a deep pit close to water thinking:</p>
<p class="gatha">“When a duty or need has arisen</p>
<p class="gatha">it will be there to help me,</p>
<p class="gatha0">to free me from a king if slandered, or from molestation</p>
<p class="gatha">from a thief, or from a debt, or famine, or accident.”</p>
<p class="gatha">For this kind of help, savings are stored up in the world.</p>
<p class="gatha0">Although it is well stored</p>
<p class="gatha">in a deep pit, close to water,</p>
<p class="gatha">still, it cannot help him in all things on every occasion,</p>
<p class="gatha0">for perhaps those savings are removed from that place,</p>
<p class="gatha">or he forgets the signs telling where they lie,</p>
<p class="gatha">or nāgas take them away,</p>
<p class="gatha">or yakkhas carry them off,</p>
<p class="gatha0">or the heirs he dislikes</p>
<p class="gatha">extract them unseen,</p>
<p class="gatha">and when his merit comes to an end</p>
<p class="gatha">all of it will be destroyed.</p>
<p class="gatha0">But that woman or man who through giving, virtue,</p>
<p class="gatha">restraint, and self-control has well stored up his savings, </p>
<p class="gatha">placing them in a shrine, or in the Sangha,</p>
<p class="gatha">or in an individual, or a guest,</p>
<p class="gatha0">or in his mother or father,</p>
<p class="gatha">also in an elder brother,</p>
<p class="gatha">those savings are well stored up,</p>
<p class="gatha">they follow one, they do not decay.</p>
<p class="gatha0">Riches he gives up when he has to leave this life</p>
<p class="gatha">but this goes along with him.</p>
<p class="gatha">It is not shared with others,</p>
<p class="gatha">no thief carries those savings away,</p>
<p class="gatha0">the wise man should make merit, </p>
<p class="gatha">for those savings follow one along.</p>
<p class="gatha">These savings satisfy every desire of gods and men,</p>
<p class="gatha">whatever they wish for,</p>
<p class="gatha">through this merit they receive all.</p>
<p class="gatha0">A good appearance, a good voice,</p>
<p class="gatha">a good shape, a good form,</p>
<p class="gatha">sovereignty, and a retinue,</p>
<p class="gatha">through this merit they receive all.</p>
<p class="gatha0">A local kingship, an empire,</p>
<p class="gatha">and whatever happiness a Wheel-Rolling King has,</p>
<p class="gatha">also godly kingship in the heavens,</p>
<p class="gatha">through this merit they receive all.</p>
<p class="gatha0">Human good fortune,</p>
<p class="gatha">delight in the world of the gods,</p>
<p class="gatha">even the attainment of Emancipation,</p>
<p class="gatha">through this merit they receive all.</p>
<p class="gatha0">With the attainment of good friends,</p>
<p class="gatha">devotion to systematic thought,</p>
<p class="gatha">there is the power of understanding and freedom,</p>
<p class="gatha">through this merit they receive all.</p>
<p class="gatha0">The discriminations, and the liberations,</p>
<p class="gatha">and whatever perfections the disciples have,</p>
<p class="gatha">Independent Awakening, the Buddhas’ ground,</p>
<p class="gatha">through this merit they receive all.</p>
<p class="gatha0">So this is of great benefit,</p>
<p class="gatha">that is to say, the attainment of merit,</p>
<p class="gatha">therefore the wise and intelligent always praise the making of merit.</p>
<p class="centered">The Discourse on the Amount of Savings is Finished</p></div>
<h1 class="chapter">The Discourse on Friendliness Meditation</h1>
<div class="chaptxt">
<p class="chaphead">short readings 9</p>
<p class="gatha0">What should be done by one skilful in good, who has comprehended the state of peace:</p>
<p class="gatha">he ought to be able, straight, and upright, easy to speak to, meek, without conceit,</p>
<p class="gatha0">satisfied with little, easy to support, free from duties, and light in living,</p>
<p class="gatha">with faculties at peace, prudent, not forward, and greedless among the families,</p>
<p class="gatha0">he should not do the slightest thing whereby others who are wise might find fault with him.</p>
<p class="gatha">“May all beings be happy and secure, may all beings in their hearts be happy!</p>
<p class="gatha0">Whatsoever breathing beings there are—trembling, firm, or any other beings,</p>
<p class="gatha">whether they be long or great, of middle size, short, tiny, or of compact body,</p>
<p class="gatha0">those who are seen, and those who are unseen, those who live far away, those who are near,</p>
<p class="gatha">those who are born, and those who still seek birth—may all beings in their hearts be happy!”</p>
<p class="gatha0">No one should cheat another, nor should he despise anyone wherever they be,</p>
<p class="gatha">he should not long for suffering for another because of anger or resentment.</p>
<p class="gatha0">In the same way as a mother would protect her son, her only son, with her life,</p>
<p class="gatha">so toward all beings he should develop the measureless thought of friendliness.</p>
<p class="gatha0">Towards the whole wide world he should develop the measureless thought of friendliness,</p>
<p class="gatha">above, below, and across the middle, without barriers, hate, or enemy.</p>
<p class="gatha0">Standing, walking, sitting, lying, for as long as he is without torpor,</p>
<p class="gatha">he should be resolved on this mindfulness, for this, they say here, is the true spiritual life.</p>
<p class="gatha0">Without going back to wrong views, virtuous, and endowed with true insight,</p>
<p class="gatha">having removed all greed for sense pleasures, he will never come to lie in a womb again.</p>
<p class="centered">The Discourse on Friendliness Meditation is Finished</p>
<p class="centered">THE TEXT OF THE SHORT READINGS IS FINISHED</p></div>
<div end="ed" class="end"></div>`

document.getElementById('loaddata').innerHTML = mulaen_2_5_1
searchhelper()
bookhelper()
var chapterhelper = document.createElement('script')
chapterhelper.src = `chaptertoggle.js`
document.head.appendChild(chapterhelper)